// Package bootstrapsource shows what `rasqlgen bootstrap` writes: a schema
// package generated directly from a live database, with no hand-written
// Tables function to keep in sync. The database here is a throwaway SQLite
// file the generate directive below creates and drops itself, so the
// example needs no server.
package bootstrapsource

// The directive the documentation shows, kept here rather than written out
// in prose so the example is generated by the exact line a reader copies.
// It runs with this directory as its working directory, which is what makes
// the relative output path in gen/main.go resolve.
//
//go:generate go run ./gen
