// Package bootstrapsource documents the supported compatibility workflow for
// `rasqlgen bootstrap`: it writes a schema package directly from a live
// database, with no hand-written Tables function to keep in sync. New
// projects should normally own a generator program created by `rasqlgen init`.
// The database here is a throwaway SQLite file the generate directive below
// creates and drops itself, so the example needs no server.
package bootstrapsource

// The directive the documentation shows, kept here rather than written out
// in prose so the example is generated by the exact line a reader copies.
// It runs with this directory as its working directory, which is what makes
// the relative output path in gen/main.go resolve.
//
//go:generate go run ./gen
