//go:build unix

package rasql_test

import (
	"context"
	"database/sql"
	"testing"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/dialect"
	"github.com/lestrrat-go/rasql/inspect"
	"github.com/lestrrat-go/rasql/internal/dbtest"
	"github.com/stretchr/testify/require"
)

// TestInsertIntoAlwaysIdentityColumnAgainstLiveDatabases proves, against a
// real PostgreSQL server, that rasql.Insert into a table with an ALWAYS
// identity primary key succeeds and the server assigns the key --
// typedInsertMany leaves the column out of the INSERT column list, rather
// than being refused by the server the way it would be if the column
// reached the statement (PostgreSQL: "cannot insert a non-DEFAULT value").
// The descriptor driving Insert comes from inspect.Table, the same
// descriptor a real caller would build from a live database, not a
// hand-built schema.TableDef, so this exercises the inspect and typed-write
// halves of identity support together.
func TestInsertIntoAlwaysIdentityColumnAgainstLiveDatabases(t *testing.T) {
	ctx := context.Background()
	database := dbtest.PostgreSQLDB(t)

	// render.CreateTable does render an ALWAYS identity column on
	// PostgreSQL (see render/identity_render_integration_test.go), but the
	// table is created directly here to keep this test focused on the
	// typed write path rather than also depending on render's behavior.
	_, err := database.ExecContext(ctx, "CREATE TABLE live_write_members (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)")
	require.NoError(t, err, "create live table with an ALWAYS identity column")

	inspector, err := inspect.New(database, dialect.PostgreSQL())
	require.NoError(t, err, "create inspector")
	definition, err := inspector.Table(ctx, "live_write_members")
	require.NoError(t, err, "inspect the table this test just created")

	db, err := rasql.New(database, dialect.PostgreSQL())
	require.NoError(t, err, "create rasql db")
	type member struct {
		ID   int64  `rasql:"id"`
		Name string `rasql:"name"`
	}
	members, err := rasql.TableOf[member](definition)
	require.NoError(t, err, "build a typed table from the inspected descriptor")

	// The point under test: this must succeed, and the ID supplied here
	// (999) must never reach the server -- if it did, and the server
	// obeyed it, the assertion below that the server itself assigned a
	// small sequential key would still pass by accident, so it is chosen
	// far outside the range live_write_members' own sequence would ever
	// produce on a fresh table.
	_, err = rasql.Insert(ctx, db, members, member{ID: 999, Name: "Ada"})
	require.NoError(t, err, "insert into a table with an ALWAYS identity column must succeed: the identity column must not reach the INSERT statement")

	var assignedID int64
	err = database.QueryRowContext(ctx, "SELECT id FROM live_write_members WHERE name = $1", "Ada").Scan(&assignedID)
	require.NoError(t, err, "read the inserted row back directly")
	require.NotEqual(t, int64(999), assignedID, "the server, not the caller, must have assigned the identity column")
	require.Equal(t, int64(1), assignedID, "a fresh table's default identity sequence starts at 1")
}

// TestInsertIntoByDefaultIdentityColumnKeepsExplicitValueAgainstLiveDatabases
// proves, against real PostgreSQL and MySQL servers, that rasql.Insert
// into a table with a BY DEFAULT identity column (PostgreSQL's own
// GENERATED BY DEFAULT AS IDENTITY, and MySQL's AUTO_INCREMENT, which is
// BY DEFAULT-shaped) keeps an explicit value rather than the server
// overwriting it -- the one place the two identity generations differ in
// the typed write path (see the comment on the Identity == IdentityAlways
// check in typedInsertMany).
func TestInsertIntoByDefaultIdentityColumnKeepsExplicitValueAgainstLiveDatabases(t *testing.T) {
	for _, test := range []struct {
		name             string
		open             func(*testing.T) *sql.DB
		dialect          dialect.Dialect
		createTableQuery string
		selectIDQuery    string
	}{
		{
			name:             "postgresql",
			open:             dbtest.PostgreSQLDB,
			dialect:          dialect.PostgreSQL(),
			createTableQuery: "CREATE TABLE live_write_legacy_members (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)",
			selectIDQuery:    "SELECT id FROM live_write_legacy_members WHERE name = $1",
		},
		{
			name:             "mysql",
			open:             dbtest.MySQLDB,
			dialect:          dialect.MySQL(),
			createTableQuery: "CREATE TABLE live_write_legacy_members (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL) ENGINE=InnoDB",
			selectIDQuery:    "SELECT id FROM live_write_legacy_members WHERE name = ?",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			ctx := context.Background()
			database := test.open(t)

			_, err := database.ExecContext(ctx, test.createTableQuery)
			require.NoError(t, err, "create live table with a BY DEFAULT identity column")

			inspector, err := inspect.New(database, test.dialect)
			require.NoError(t, err, "create inspector")
			definition, err := inspector.Table(ctx, "live_write_legacy_members")
			require.NoError(t, err, "inspect the table this subtest just created")

			db, err := rasql.New(database, test.dialect)
			require.NoError(t, err, "create rasql db")
			type member struct {
				ID   int64  `rasql:"id"`
				Name string `rasql:"name"`
			}
			members, err := rasql.TableOf[member](definition)
			require.NoError(t, err, "build a typed table from the inspected descriptor")

			_, err = rasql.Insert(ctx, db, members, member{ID: 7, Name: "Grace"})
			require.NoError(t, err, "insert an explicit value into a BY DEFAULT identity column must succeed")

			var keptID int64
			err = database.QueryRowContext(ctx, test.selectIDQuery, "Grace").Scan(&keptID)
			require.NoError(t, err, "read the inserted row back directly")
			require.Equal(t, int64(7), keptID, "a BY DEFAULT identity column must keep the explicit value rather than the server overwriting it")
		})
	}
}
