//go:build unix

package rasql_test

import (
	"context"
	"database/sql"
	"strings"
	"testing"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/dialect"
	"github.com/lestrrat-go/rasql/internal/dbtest"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
	"github.com/stretchr/testify/require"
)

type liveMutationRow struct{ ID int64 }
type liveMutationDecoder struct{ schema rasql.ResultSchema }

func (d liveMutationDecoder) ResultSchema() rasql.ResultSchema { return d.schema }
func (liveMutationDecoder) Presence() []rasql.Presence         { return nil }
func (d liveMutationDecoder) DecodeRow(source rasql.ScanSource, row *liveMutationRow) error {
	return source.Scan(&row.ID)
}

func liveMutationProjection(t *testing.T, table rasql.Table[liveMutationRow]) rasql.Projection[liveMutationRow] {
	t.Helper()
	schemaValue, err := rasql.NewResultSchema(rasql.ResultColumn{Name: "id", Type: schema.IntegerType{}})
	require.NoError(t, err)
	relation, err := rasql.SourceOf[liveMutationRow](table, "")
	require.NoError(t, err)
	id, err := rasql.BindColumn[liveMutationRow, int64](relation, "id", "")
	require.NoError(t, err)
	projection, err := rasql.NewProjection([]rasql.ProjectionItem{rasql.Item("id", id.Expr(), schema.IntegerType{}, "")}, liveMutationDecoder{schema: schemaValue})
	require.NoError(t, err)
	return projection
}

func liveMutationTable(t *testing.T, name string) rasql.Table[liveMutationRow] {
	t.Helper()
	return rasql.MustTableOf[liveMutationRow](schema.TableDef{
		Name:       name,
		PrimaryKey: []string{"id"},
		Columns: []schema.ColumnDef{
			{Name: "id", Type: schema.IntegerType{}, Identity: schema.IdentityByDefault},
			{Name: "required_text", Type: schema.TextType{}},
			{Name: "default_text", Type: schema.TextType{}, Default: "'db-default'"},
		},
	})
}

func quoteLiveIdentifier(t *testing.T, d dialect.Dialect, name string) string {
	t.Helper()
	quoted, err := d.QuoteIdentifier(name)
	require.NoError(t, err)
	return quoted
}

func runLiveMutation(t *testing.T, database *sql.DB, dialectValue dialect.Dialect, profileID, createSQL string) {
	t.Helper()
	name := dbtest.UniqueName(t, "rasql_r2_mutation_items")
	quotedName := quoteLiveIdentifier(t, dialectValue, name)
	createSQL = strings.ReplaceAll(createSQL, "{name}", quotedName)
	_, err := database.ExecContext(t.Context(), createSQL)
	require.NoError(t, err)
	t.Cleanup(func() { _, _ = database.ExecContext(context.Background(), "DROP TABLE "+quotedName) })
	db, err := rasql.New(database, dialectValue)
	require.NoError(t, err)
	profile, err := rasql.DiscoverEngineProfile(t.Context(), db, profileID)
	require.NoError(t, err)
	executor, err := rasql.AsExecutor(db, profile)
	require.NoError(t, err)
	table := liveMutationTable(t, name)
	required := query.TypedColumnOf[liveMutationRow, string](table.Column("required_text"))
	defaultText := query.TypedColumnOf[liveMutationRow, string](table.Column("default_text"))
	create, err := rasql.NewCreatePlan(table, rasql.SetField(required, "live"), rasql.DefaultField(defaultText))
	require.NoError(t, err)
	outcome, err := rasql.ExecMutation(t.Context(), executor, create)
	require.NoError(t, err)
	require.Equal(t, int64(1), outcome.Affected)
	require.Equal(t, rasql.DurabilityCommitted, outcome.Durability)
	projection := liveMutationProjection(t, table)
	returned, err := rasql.Returning(create, projection)
	require.NoError(t, err)
	values, err := rasql.All(t.Context(), executor, returned)
	if dialectValue.Name() == "mysql" {
		require.Error(t, err)
		require.Empty(t, values)
		return
	}
	require.NoError(t, err)
	require.Len(t, values, 1)
}

func TestPostgreSQLMutation(t *testing.T) {
	runLiveMutation(t, dbtest.PostgreSQLDB(t), dialect.PostgreSQL(), "postgresql-17", `CREATE TABLE {name} (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, required_text TEXT NOT NULL, default_text TEXT NOT NULL DEFAULT 'db-default')`)
}

func TestMySQLMutation(t *testing.T) {
	runLiveMutation(t, dbtest.MySQLDB(t), dialect.MySQL(), "mysql-8.4", "CREATE TABLE {name} (id BIGINT AUTO_INCREMENT PRIMARY KEY, required_text VARCHAR(255) NOT NULL, default_text VARCHAR(255) NOT NULL DEFAULT 'db-default')")
}
