//go:build unix

package rasql_test

import (
	"context"
	"database/sql"
	"testing"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/dialect"
	"github.com/lestrrat-go/rasql/internal/dbtest"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
	"github.com/stretchr/testify/require"
)

func TestLivePostgreSQLMutationUpdateDeleteReturning(t *testing.T) {
	database := dbtest.PostgreSQLDB(t)
	name := dbtest.UniqueName(t, "rasql_r2_update_delete")
	quoted, err := dialect.PostgreSQL().QuoteIdentifier(name)
	require.NoError(t, err)
	_, err = database.ExecContext(t.Context(), "CREATE TABLE "+quoted+" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, required_text TEXT NOT NULL)")
	require.NoError(t, err)
	t.Cleanup(func() { _, _ = database.ExecContext(context.Background(), "DROP TABLE "+quoted) })
	executor := liveExecutor(t, database, dialect.PostgreSQL(), "postgresql-17")
	table := rasql.MustTableOf[liveMutationRow](schema.TableDef{Name: name, PrimaryKey: []string{"id"}, Columns: []schema.ColumnDef{{Name: "id", Type: schema.IntegerType{}, Identity: schema.IdentityByDefault}, {Name: "required_text", Type: schema.TextType{}}}})
	id := query.TypedColumnOf[liveMutationRow, int64](table.Column("id"))
	value := query.TypedColumnOf[liveMutationRow, string](table.Column("required_text"))
	create, err := rasql.NewCreatePlan(table, rasql.SetField(value, "before"))
	require.NoError(t, err)
	_, err = rasql.ExecMutation(t.Context(), executor, create)
	require.NoError(t, err)
	patch, err := rasql.NewPatchPlan(table, query.EqualValue(id, int64(1)), rasql.SetField(value, "after"))
	require.NoError(t, err)
	returned, err := rasql.Returning(patch, liveMutationProjection(t, table))
	require.NoError(t, err)
	row, err := rasql.One(t.Context(), executor, returned)
	require.NoError(t, err)
	require.Equal(t, int64(1), row.ID)
	var stored string
	require.NoError(t, database.QueryRowContext(t.Context(), "SELECT required_text FROM "+quoted+" WHERE id = 1").Scan(&stored))
	require.Equal(t, "after", stored)
	deletePlan, err := rasql.NewDeletePlan(table, query.EqualValue(id, int64(1)))
	require.NoError(t, err)
	returned, err = rasql.Returning(deletePlan, liveMutationProjection(t, table))
	require.NoError(t, err)
	row, err = rasql.One(t.Context(), executor, returned)
	require.NoError(t, err)
	require.Equal(t, int64(1), row.ID)
}

func TestLiveMySQLAtomicMutationBatch(t *testing.T) {
	database := dbtest.MySQLDB(t)
	name := dbtest.UniqueName(t, "rasql_r2_atomic")
	quoted, err := dialect.MySQL().QuoteIdentifier(name)
	require.NoError(t, err)
	_, err = database.ExecContext(t.Context(), "CREATE TABLE "+quoted+" (id BIGINT AUTO_INCREMENT PRIMARY KEY, required_text VARCHAR(255) NOT NULL)")
	require.NoError(t, err)
	t.Cleanup(func() { _, _ = database.ExecContext(context.Background(), "DROP TABLE "+quoted) })
	executor := liveExecutor(t, database, dialect.MySQL(), "mysql-8.4")
	table := rasql.MustTableOf[liveMutationRow](schema.TableDef{Name: name, PrimaryKey: []string{"id"}, Columns: []schema.ColumnDef{{Name: "id", Type: schema.IntegerType{}, Identity: schema.IdentityByDefault}, {Name: "required_text", Type: schema.TextType{}}}})
	value := query.TypedColumnOf[liveMutationRow, string](table.Column("required_text"))
	first, err := rasql.NewCreatePlan(table, rasql.SetField(value, "one"))
	require.NoError(t, err)
	second, err := rasql.NewCreatePlan(table, rasql.SetField(value, "two"))
	require.NoError(t, err)
	outcome, err := rasql.ExecMutationBatch(t.Context(), executor, []rasql.MutationPlan{first, second}, rasql.BulkOptions{Atomic: true})
	require.NoError(t, err)
	require.Equal(t, []rasql.InputOutcome{rasql.InputApplied, rasql.InputApplied}, outcome.Inputs)
}

func liveExecutor(t *testing.T, database *sql.DB, dialectValue dialect.Dialect, profileID string) rasql.Executor {
	t.Helper()
	db, err := rasql.New(database, dialectValue)
	require.NoError(t, err)
	profile, err := rasql.DiscoverEngineProfile(t.Context(), db, profileID)
	require.NoError(t, err)
	executor, err := rasql.AsExecutor(db, profile)
	require.NoError(t, err)
	return executor
}
