// Code generated by rasqlgen; DO NOT EDIT.

package generated

import (
	"context"
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
)

type AuditLogRow struct {
	ID     int64
	Action string
}

var auditLogDefinition = schema.TableDef{
	Kind:       schema.ObjectKind("table"),
	Operations: schema.Operation(3),
	Name:       "audit_log",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "action", Type: schema.TextType{}},
	},
	PrimaryKey: []string{"id"},
}

var auditLogTable = rasql.MustTableOf[AuditLogRow](auditLogDefinition)

type auditLogTableHandle = rasql.Table[AuditLogRow]

type AuditLogTable struct {
	auditLogTableHandle
	AuditLogExpressions
}

func newAuditLogTable(handle auditLogTableHandle) AuditLogTable {
	return AuditLogTable{auditLogTableHandle: handle, AuditLogExpressions: bindAuditLogExpressions(handle)}
}

func AuditLog() AuditLogTable { return newAuditLogTable(auditLogTable) }

func (t AuditLogTable) Ref() query.TableRef { return t.auditLogTableHandle.Ref() }

func (t AuditLogTable) As(alias string) (AuditLogTable, error) {
	aliased, err := t.auditLogTableHandle.As(alias)
	if err != nil {
		return AuditLogTable{}, err
	}
	return newAuditLogTable(aliased), nil
}

func (t AuditLogTable) InSchema(namespace string) (AuditLogTable, error) {
	moved, err := t.auditLogTableHandle.InSchema(namespace)
	if err != nil {
		return AuditLogTable{}, err
	}
	return newAuditLogTable(moved), nil
}

// AuditLogHandle returns the typed table inside t, which the constructors in
// the rasql package take: rasql.NewCreatePlan, rasql.NewPatchPlan and
// rasql.NewDeletePlan. Reach for it to write a column whose builder setter
// this package could not generate.
func AuditLogHandle(t AuditLogTable) rasql.Table[AuditLogRow] { return t.auditLogTableHandle }

type AuditLogExpressions struct {
	ID     rasql.Column[AuditLogRow, int64]
	Action rasql.Column[AuditLogRow, string]
}

type OptionalAuditLogExpressions struct {
	ID     rasql.NullColumn[AuditLogRow, int64]
	Action rasql.NullColumn[AuditLogRow, string]
}

func bindAuditLogExpressions(source auditLogTableHandle) AuditLogExpressions {
	return AuditLogExpressions{
		ID:     rasqlgenColumn(source, "id", "", rasql.BindColumn[AuditLogRow, int64]),
		Action: rasqlgenColumn(source, "action", "", rasql.BindColumn[AuditLogRow, string]),
	}
}

// Optional names every column of t as it appears on the nullable side
// of an outer join, where the whole row may be absent.
func (t AuditLogTable) Optional() OptionalAuditLogExpressions {
	source := rasql.Optional[AuditLogRow](t.auditLogTableHandle)
	return OptionalAuditLogExpressions{
		ID:     rasqlgenColumn(source, "id", "", rasql.BindOptionalColumn[AuditLogRow, int64]),
		Action: rasqlgenColumn(source, "action", "", rasql.BindOptionalColumn[AuditLogRow, string]),
	}
}

var auditLogResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "action", Type: schema.TextType{}, Codec: ""},
}
var auditLogResultSchema = rasqlgenResultSchema(auditLogResultColumns)

type auditLogDecoder struct{}

func (auditLogDecoder) ResultSchema() rasql.ResultSchema { return auditLogResultSchema }
func (auditLogDecoder) Presence() []rasql.Presence       { return nil }
func (auditLogDecoder) DecodeRow(source rasql.ScanSource, row *AuditLogRow) error {
	return source.Scan(&row.ID, &row.Action)
}

func (row *AuditLogRow) ScanRow(source rasql.ScanSource) error {
	return auditLogDecoder{}.DecodeRow(source, row)
}

var auditLogOptionalResultSchema = rasqlgenOptionalResultSchema(auditLogResultColumns)

type auditLogOptionalDecoder struct{}

func (auditLogOptionalDecoder) ResultSchema() rasql.ResultSchema { return auditLogOptionalResultSchema }
func (auditLogOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("AuditLog", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (auditLogOptionalDecoder) DecodeRow(source rasql.ScanSource, row *AuditLogRow) error {
	var IDValue rasql.Nullable[int64]
	var ActionValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &ActionValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(ActionValue, &row.Action)
	return nil
}

func AuditLogProjection(source AuditLogTable) (rasql.Projection[AuditLogRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", source.AuditLogExpressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("action", source.AuditLogExpressions.Action.Expr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, auditLogDecoder{})
}

func OptionalAuditLogProjection(source OptionalAuditLogExpressions) (rasql.Projection[AuditLogRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", source.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("action", source.Action.NullExpr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, auditLogOptionalDecoder{})
}

func AuditLogGraphKey(source AuditLogTable) (rasql.GraphKey[AuditLogRow], error) {
	return rasql.NewGraphKey[AuditLogRow](rasql.KeyPart[AuditLogRow, int64](source.AuditLogExpressions.ID, func(row AuditLogRow) int64 { return row.ID }))
}

func AuditLogIDPageKey(source AuditLogTable, direction rasql.PageDirection) (rasql.PageKey[AuditLogRow], error) {
	return rasqlgenPageKey(direction, source.AuditLogExpressions.ID.Expr(), func(row AuditLogRow) int64 { return row.ID })
}

func AuditLogActionPageKey(source AuditLogTable, direction rasql.PageDirection) (rasql.PageKey[AuditLogRow], error) {
	return rasqlgenPageKey(direction, source.AuditLogExpressions.Action.Expr(), func(row AuditLogRow) string { return row.Action })
}

var auditLogMutationColumns = bindAuditLogExpressions(auditLogTable)

type AuditLogCreate struct {
	table  rasql.Table[AuditLogRow]
	fields []rasql.MutationField[AuditLogRow]
}

func (v AuditLogCreate) ID(value int64) AuditLogCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(auditLogMutationColumns.ID, value))
	return v
}
func (v AuditLogCreate) Action(value string) AuditLogCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(auditLogMutationColumns.Action, value))
	return v
}
func (v AuditLogCreate) Plan() (rasql.CreatePlan[AuditLogRow], error) {
	return rasql.NewCreatePlan(v.table, v.fields...)
}

func (v AuditLogCreate) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t AuditLogTable) Create() AuditLogCreate { return AuditLogCreate{table: t.auditLogTableHandle} }
