// Code generated by rasqlgen; DO NOT EDIT.

package generated

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
)

type AuditLogRow struct {
	ID     int64
	Action string
}

var auditLogDefinition = schema.TableDef{
	Kind:       schema.ObjectKind("table"),
	Operations: schema.Operation(3),
	Name:       "audit_log",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "action", Type: schema.TextType{}},
	},
	PrimaryKey: []string{"id"},
}

var auditLogTable = rasql.MustTableOf[AuditLogRow](auditLogDefinition)

type AuditLogTable struct{ rasql.Table[AuditLogRow] }

func AuditLog() AuditLogTable { return AuditLogTable{Table: auditLogTable} }

func (t AuditLogTable) Source(alias string) (rasql.TypedRelation[AuditLogRow], error) {
	return rasql.SourceOf[AuditLogRow](t.Table, alias)
}

type AuditLogColumns struct{}

type AuditLogExpressions struct {
	ID     rasql.Column[AuditLogRow, int64]
	Action rasql.Column[AuditLogRow, string]
}

type OptionalAuditLogExpressions struct {
	ID     rasql.NullColumn[AuditLogRow, int64]
	Action rasql.NullColumn[AuditLogRow, string]
}

func (AuditLogColumns) Bind(source rasql.TypedRelation[AuditLogRow]) (AuditLogExpressions, error) {
	var err error
	result := AuditLogExpressions{
		ID:     rasqlgenBind(&err, source, "id", "", rasql.BindColumn[AuditLogRow, int64]),
		Action: rasqlgenBind(&err, source, "action", "", rasql.BindColumn[AuditLogRow, string]),
	}
	return result, err
}

func (AuditLogColumns) BindOptional(source rasql.OptionalRelation[AuditLogRow]) (OptionalAuditLogExpressions, error) {
	var err error
	result := OptionalAuditLogExpressions{
		ID:     rasqlgenBind(&err, source, "id", "", rasql.BindOptionalColumn[AuditLogRow, int64]),
		Action: rasqlgenBind(&err, source, "action", "", rasql.BindOptionalColumn[AuditLogRow, string]),
	}
	return result, err
}

var auditLogResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "action", Type: schema.TextType{}, Codec: ""},
}
var auditLogResultSchema = rasqlgenResultSchema(auditLogResultColumns)

type auditLogDecoder struct{}

func (auditLogDecoder) ResultSchema() rasql.ResultSchema { return auditLogResultSchema }
func (auditLogDecoder) Presence() []rasql.Presence       { return nil }
func (auditLogDecoder) DecodeRow(source rasql.ScanSource, row *AuditLogRow) error {
	return source.Scan(&row.ID, &row.Action)
}

func (row *AuditLogRow) ScanRow(source rasql.ScanSource) error {
	return auditLogDecoder{}.DecodeRow(source, row)
}

var auditLogOptionalResultSchema = rasqlgenOptionalResultSchema(auditLogResultColumns)

type auditLogOptionalDecoder struct{}

func (auditLogOptionalDecoder) ResultSchema() rasql.ResultSchema { return auditLogOptionalResultSchema }
func (auditLogOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("AuditLog", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (auditLogOptionalDecoder) DecodeRow(source rasql.ScanSource, row *AuditLogRow) error {
	var IDValue rasql.Nullable[int64]
	var ActionValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &ActionValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(ActionValue, &row.Action)
	return nil
}

func AuditLogProjection(expressions AuditLogExpressions) (rasql.Projection[AuditLogRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", expressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("action", expressions.Action.Expr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, auditLogDecoder{})
}

func OptionalAuditLogProjection(expressions OptionalAuditLogExpressions) (rasql.Projection[AuditLogRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", expressions.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("action", expressions.Action.NullExpr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, auditLogOptionalDecoder{})
}

func AuditLogGraphKey(source rasql.TypedRelation[AuditLogRow]) (rasql.GraphKey[AuditLogRow], error) {
	expressions, err := (AuditLogColumns{}).Bind(source)
	if err != nil {
		return rasql.GraphKey[AuditLogRow]{}, err
	}
	return rasql.NewGraphKey[AuditLogRow](rasql.KeyPart[AuditLogRow, int64](expressions.ID, func(row AuditLogRow) int64 { return row.ID }))
}

func AuditLogIDPageKey(source rasql.TypedRelation[AuditLogRow], direction rasql.PageDirection) (rasql.PageKey[AuditLogRow], error) {
	expressions, err := (AuditLogColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.ID.Expr(), func(row AuditLogRow) int64 { return row.ID })
}

func AuditLogActionPageKey(source rasql.TypedRelation[AuditLogRow], direction rasql.PageDirection) (rasql.PageKey[AuditLogRow], error) {
	expressions, err := (AuditLogColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.Action.Expr(), func(row AuditLogRow) string { return row.Action })
}

var auditLogMutationColumns = func() AuditLogExpressions {
	source, err := AuditLog().Source("")
	if err != nil {
		panic(err)
	}
	value, err := (AuditLogColumns{}).Bind(source)
	if err != nil {
		panic(err)
	}
	return value
}()

type AuditLogCreate struct {
	fields []rasql.MutationField[AuditLogRow]
}

func NewAuditLogCreate() AuditLogCreate { return AuditLogCreate{} }
func (v AuditLogCreate) ID(value int64) AuditLogCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(auditLogMutationColumns.ID, value))
	return v
}
func (v AuditLogCreate) Action(value string) AuditLogCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(auditLogMutationColumns.Action, value))
	return v
}
func (v AuditLogCreate) Plan() (rasql.CreatePlan[AuditLogRow], error) {
	return rasql.NewCreatePlan(AuditLog().Table, v.fields...)
}
