// Package querygen emits Go source from a compiled named query. It reads a
// namedsql.QueryDef, the plain description namedsql hands out for this
// purpose, rather than namedsql's own internals.
package querygen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"strconv"
	"strings"

	"github.com/lestrrat-go/rasql/internal/schemagen"
	"github.com/lestrrat-go/rasql/namedsql"
	"github.com/lestrrat-go/rasql/schema"
)

// GoSource returns a Go function that creates this static statement. A bind
// that names no column generates an any parameter unless an explicit binding
// supplies its type. A bind that names a column resolves it against tables
// and generates its nullable or non-null Go type; tables is optional and
// needed only when at least one bind names a column.
func GoSource(def namedsql.QueryDef, packageName string, functionName string, tables ...schema.TableDef) ([]byte, error) {
	return GoSourceInDir("", def, packageName, functionName, tables...)
}

func GoSourceInDir(dir string, def namedsql.QueryDef, packageName string, functionName string, tables ...schema.TableDef) ([]byte, error) {
	if def.Name == "" || strings.TrimSpace(def.SQL) == "" {
		return nil, fmt.Errorf("namedsql: invalid compiled template")
	}
	if !isUsableGoIdentifier(packageName) {
		return nil, fmt.Errorf("namedsql: invalid package name %q", packageName)
	}
	if !isUsableGoIdentifier(functionName) {
		return nil, fmt.Errorf("namedsql %q: invalid function name %q", def.Name, functionName)
	}
	if def.Result != nil && def.ResultType != "" && (!isUsableGoIdentifier(def.ResultType) || def.ResultType[0] < 'A' || def.ResultType[0] > 'Z') {
		return nil, fmt.Errorf("namedsql %q: invalid exported result type %q", def.Name, def.ResultType)
	}
	if functionName == "init" || (packageName == "main" && functionName == "main") {
		return nil, fmt.Errorf("namedsql %q: function name %q cannot be generated in package %q", def.Name, functionName, packageName)
	}
	reservedNames := map[string]struct{}{
		packageName:  {},
		functionName: {},
	}
	for _, bind := range def.Binds {
		if !isUsableGoIdentifier(bind.Name) {
			return nil, fmt.Errorf("namedsql %q: parameter %q cannot be a Go identifier", def.Name, bind.Name)
		}
		reservedNames[bind.Name] = struct{}{}
	}
	stmtName := availableGoIdentifier("stmt", reservedNames)
	defaultParameterType := "any"
	if functionName == "any" {
		defaultParameterType = "interface{}"
	}

	parameterTypes := make([]string, len(def.Binds))
	parameterRefs := make([]schemagen.BindingRef, len(def.Binds))
	parameterBound := make([]bool, len(def.Binds))
	parameterNullable := make([]bool, len(def.Binds))
	needsTime := false
	bindingSet := schemagen.NewBindingSet(schemagen.BindingSetOptions{Dir: dir, Reserved: bindingReservedNames(packageName, functionName, stmtName, def)})
	for index, bind := range def.Binds {
		var column schema.ColumnDef
		if bind.Column == "" {
			if bind.Binding == nil {
				parameterTypes[index] = defaultParameterType
				continue
			}
			column = schema.ColumnDef{Name: bind.Name, Type: schema.TextType{}, GoBinding: bind.Binding.Go.Clone()}
			parameterNullable[index] = bind.Binding.Nullable
		} else {
			var err error
			column, err = resolveColumn(bind, tables)
			if err != nil {
				return nil, fmt.Errorf("namedsql %q: %w", def.Name, err)
			}
			if bind.Binding != nil {
				column.GoBinding = bind.Binding.Go.Clone()
				parameterNullable[index] = bind.Binding.Nullable
			} else {
				parameterNullable[index] = column.Nullable
			}
		}
		ref, err := bindingSet.Add(column)
		if err != nil {
			return nil, fmt.Errorf("namedsql %q: %w", def.Name, err)
		}
		parameterRefs[index] = ref
		parameterBound[index] = true
	}
	if err := bindingSet.Finalize(); err != nil {
		return nil, fmt.Errorf("namedsql %q: %w", def.Name, err)
	}
	for index := range parameterTypes {
		if !parameterBound[index] {
			parameterTypes[index] = defaultParameterType
			continue
		}
		parameterType, err := bindingSet.Type(parameterRefs[index], parameterNullable[index])
		if err != nil {
			return nil, fmt.Errorf("namedsql %q: %w", def.Name, err)
		}
		parameterTypes[index] = parameterType
		if parameterType == "time.Time" {
			needsTime = true
		}
	}

	timeName := "time"
	typed := def.Result != nil
	typedMany := typed && def.Result.Cardinality == 0
	if needsTime || typed {
		timeName = availableGoIdentifier("time", reservedNames)
		for index, parameterType := range parameterTypes {
			if parameterType == "time.Time" {
				parameterTypes[index] = timeName + ".Time"
			}
		}
	}
	bindingImports := bindingSet.Imports()
	if typed {
		for _, column := range def.Result.Columns {
			bindingImports = append(bindingImports, column.Binding.Imports...)
		}
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\n")
	source.WriteString("package ")
	source.WriteString(packageName)
	source.WriteString("\n\n")
	stmtImport := "\"github.com/lestrrat-go/rasql/stmt\""
	if stmtName != "stmt" {
		stmtImport = stmtName + " " + stmtImport
	}
	if needsTime {
		// The standard library goes in its own group above rasql's, which is
		// what gofmt's convention and every hand-written file here do. gofmt
		// sorts within a group but never splits one, so emitting the blank
		// line is this generator's job rather than the formatter's.
		source.WriteString("import (\n\t")
		if timeName != "time" {
			source.WriteString(timeName)
			source.WriteByte(' ')
		}
		if typed {
			source.WriteString("\"context\"\n\t\"fmt\"\n")
			if typedMany {
				source.WriteString("\t\"iter\"\n")
			}
		}
		if needsTime {
			source.WriteString("\"time\"\n")
		}
		writeBindingImports(&source, bindingImports)
		if typed {
			source.WriteString("\t\"github.com/lestrrat-go/rasql\"\n")
		}
		source.WriteString("\n\t")
		source.WriteString(stmtImport)
		source.WriteString("\n)\n\n")
	} else if len(bindingImports) > 0 || typed {
		source.WriteString("import (\n")
		if typed {
			source.WriteString("\t\"context\"\n\t\"fmt\"\n")
			if typedMany {
				source.WriteString("\t\"iter\"\n")
			}
			source.WriteString("\t\"github.com/lestrrat-go/rasql\"\n")
		}
		writeBindingImports(&source, bindingImports)
		source.WriteString("\n\t")
		source.WriteString(stmtImport)
		source.WriteString("\n)\n\n")
	} else {
		source.WriteString("import ")
		source.WriteString(stmtImport)
		source.WriteString("\n\n")
	}
	source.WriteString("func ")
	source.WriteString(functionName)
	source.WriteByte('(')
	for index, bind := range def.Binds {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(bind.Name)
		source.WriteByte(' ')
		source.WriteString(parameterTypes[index])
	}
	source.WriteString(") ")
	source.WriteString(stmtName)
	source.WriteString(".Statement {\n\treturn ")
	source.WriteString(stmtName)
	source.WriteString(".New(")
	source.WriteString(strconv.Quote(def.SQL))
	for _, name := range def.Parameters {
		source.WriteString(", ")
		source.WriteString(name)
	}
	source.WriteString(")\n}\n")
	if typed {
		resultType := def.ResultType
		if resultType == "" {
			resultType = functionName + "Row"
		}
		source.WriteString("\ntype " + resultType + " struct {\n")
		for _, column := range def.Result.Columns {
			typ := column.Binding.Type
			if column.Nullable && column.Binding.NullableType != "" {
				typ = column.Binding.NullableType
			} else if column.Nullable && !strings.HasPrefix(typ, "*") {
				typ = "*" + typ
			}
			source.WriteString("\t" + exportedName(column.Name) + " " + typ + " `rasql:\"" + column.Name + "\"`\n")
		}
		source.WriteString("}\n\nfunc (r *" + resultType + ") ScanDestinations(columns []string) ([]any, error) {\n\tm := rasql.NewScanMask(" + strconv.Itoa(len(def.Result.Columns)) + "); dest := make([]any, len(columns))\n\tfor i, name := range columns { switch name {\n")
		for index, column := range def.Result.Columns {
			source.WriteString("\tcase " + strconv.Quote(column.Name) + ": if !m.Mark(" + strconv.Itoa(index) + ") { return nil, fmt.Errorf(\"duplicate result column\") }; dest[i] = &r." + exportedName(column.Name) + "\n")
		}
		source.WriteString("\tdefault: return nil, fmt.Errorf(\"unknown result column %s\", name) } }; return dest, nil\n}\n")
		helperName := "Query" + functionName
		if def.Result.Cardinality != 0 {
			helperName += "One"
		}
		source.WriteString("\nfunc " + helperName + "(ctx context.Context, db rasql.DB")
		for index, bind := range def.Binds {
			source.WriteString(", " + bind.Name + " " + parameterTypes[index])
		}
		switch def.Result.Cardinality {
		case 0:
			source.WriteString(") (iter.Seq2[" + resultType + ", error], error) { return rasql.QueryRendered[" + resultType + "](ctx, db, " + functionName + "(")
		case 1:
			source.WriteString(") (" + resultType + ", bool, error) { return rasql.QueryRenderedOptional[" + resultType + "](ctx, db, " + functionName + "(")
		default:
			source.WriteString(") (" + resultType + ", error) { return rasql.QueryRenderedOne[" + resultType + "](ctx, db, " + functionName + "(")
		}
		for index, bind := range def.Binds {
			if index > 0 {
				source.WriteString(", ")
			}
			source.WriteString(bind.Name)
		}
		source.WriteString(")) }\n")
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("namedsql %q: format source: %w", def.Name, err)
	}
	return formatted, nil
}

func exportedName(name string) string {
	var out strings.Builder
	upper := true
	for _, r := range name {
		if r == '_' || r == '-' || r == ' ' {
			upper = true
			continue
		}
		if upper {
			out.WriteString(strings.ToUpper(string(r)))
			upper = false
		} else {
			out.WriteRune(r)
		}
	}
	if out.Len() == 0 {
		return "Result"
	}
	result := out.String()
	for suffix, replacement := range map[string]string{"Id": "ID", "Url": "URL", "Uri": "URI", "Http": "HTTP", "Api": "API"} {
		if strings.HasSuffix(result, suffix) {
			result = strings.TrimSuffix(result, suffix) + replacement
		}
	}
	return result
}

func writeBindingImports(source *bytes.Buffer, imports []schema.GoImport) {
	for _, imported := range imports {
		source.WriteString("\t")
		if imported.Name != "" {
			source.WriteString(imported.Name)
			source.WriteByte(' ')
		}
		source.WriteString(strconv.Quote(imported.Path))
		source.WriteByte('\n')
	}
}

func bindingReservedNames(packageName, functionName, stmtName string, def namedsql.QueryDef) []string {
	reserved := []string{packageName, functionName, stmtName, "stmt", "time"}
	for _, bind := range def.Binds {
		reserved = append(reserved, bind.Name)
	}
	return reserved
}

// resolveColumn looks bind up among tables and returns the column it names.
// Matching is exact and case-sensitive on schema name, table name and
// column name: a descriptor's names come from inspection verbatim, and
// folding case would guess wrong on some engine.
//
// A two-part reference matches on table name alone, ignoring
// TableDef.Schema; two descriptors sharing that name is an error asking the
// writer to qualify it, the same rule applyHints already applies to hint
// keys. A three-part reference matches TableDef.Schema and TableDef.Name
// together. A ref that does not resolve is always an error: there is no
// fallback to any.
func resolveColumn(bind namedsql.BindDef, tables []schema.TableDef) (schema.ColumnDef, error) {
	if len(tables) == 0 {
		return schema.ColumnDef{}, fmt.Errorf("bind %q names %s, but no table descriptors were supplied", bind.Name, refString(bind))
	}

	matches := make([]schema.TableDef, 0, 1)
	for _, table := range tables {
		if bind.Schema != "" {
			if table.Schema == bind.Schema && table.Name == bind.Table {
				matches = append(matches, table)
			}
			continue
		}
		if table.Name == bind.Table {
			matches = append(matches, table)
		}
	}

	switch len(matches) {
	case 0:
		return schema.ColumnDef{}, fmt.Errorf("bind %q names %s: no descriptor names table %s", bind.Name, refString(bind), refTableString(bind))
	case 1:
		column, ok := matches[0].Column(bind.Column)
		if !ok {
			return schema.ColumnDef{}, fmt.Errorf("bind %q names %s: table %s has no column %s", bind.Name, refString(bind), refTableString(bind), bind.Column)
		}
		return column, nil
	default:
		return schema.ColumnDef{}, fmt.Errorf("bind %q names %s: two descriptors name table %s; qualify it as schema.table.column", bind.Name, refString(bind), refTableString(bind))
	}
}

func isUsableGoIdentifier(name string) bool {
	return name != "_" && token.IsIdentifier(name)
}

func availableGoIdentifier(base string, reserved map[string]struct{}) string {
	for index := 0; ; index++ {
		name := base
		if index > 0 {
			name += strconv.Itoa(index)
		}
		if _, exists := reserved[name]; !exists {
			return name
		}
	}
}

// refString returns the column reference as written, for error messages:
// "schema.table.column" for a schema-qualified reference, "table.column"
// otherwise.
func refString(bind namedsql.BindDef) string {
	if bind.Schema != "" {
		return bind.Schema + "." + bind.Table + "." + bind.Column
	}
	return bind.Table + "." + bind.Column
}

// refTableString returns the table part of the reference as written:
// "schema.table" for a schema-qualified reference, "table" otherwise.
func refTableString(bind namedsql.BindDef) string {
	if bind.Schema != "" {
		return bind.Schema + "." + bind.Table
	}
	return bind.Table
}
