package querygen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/lestrrat-go/rasql/internal/compilerir"
)

// TypedInput is the immutable compiler output needed for one native query.
type TypedInput struct {
	Package, Function, Engine, SQL, Operation, Cardinality string
	Result, Projection, Decoder                            string
	Parameters, Results                                    []TypedValue
	Imports                                                []compilerir.GoImport
	ArgumentNames                                          []string
}

type TypedValue struct {
	Semantic compilerir.SemanticValue
	Go       compilerir.GoField
}

type sourceBuilder struct{ bytes.Buffer }

func (b *sourceBuilder) WriteString(value string) *sourceBuilder {
	_, _ = b.Buffer.WriteString(value)
	return b
}
func (b *sourceBuilder) Byte(value byte) *sourceBuilder { _ = b.WriteByte(value); return b }

// TypedGoSource emits a lock-backed constructor. It deliberately emits only
// plan construction; callers choose All, Maybe, One, Rows, or ExecMutation.
func TypedGoSource(in TypedInput) ([]byte, error) {
	if in.Package == "" || in.Function == "" || strings.TrimSpace(in.SQL) == "" || in.Engine == "" {
		return nil, fmt.Errorf("querygen: incomplete typed query")
	}
	if in.Operation == "exec" {
		return typedMutationSource(in)
	}
	if len(in.Results) == 0 {
		return nil, fmt.Errorf("querygen: typed query %q has no results", in.Function)
	}
	if in.Result == "" {
		in.Result = in.Function + "Result"
	}
	if in.Projection == "" {
		in.Projection = in.Function + "Projection"
	}
	if in.Decoder == "" {
		in.Decoder = in.Function + "Decoder"
	}
	var b sourceBuilder
	b.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\npackage ")
	b.WriteString(in.Package)
	writeImports(&b, in.Imports, true, append(append([]TypedValue(nil), in.Parameters...), in.Results...))
	b.WriteString("type ").WriteString(in.Result).WriteString(" struct {\n")
	for _, value := range in.Results {
		field := value.Go
		b.WriteString("\t").WriteString(exported(field.Name)).Byte(' ').WriteString(field.Type).WriteString("\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("type ").WriteString(in.Decoder).WriteString(" struct{}\n")
	b.WriteString("func (").WriteString(in.Decoder).WriteString(") ResultSchema() rasql.ResultSchema { return ").WriteString(in.Decoder).WriteString("Schema() }\n")
	b.WriteString("func (").WriteString(in.Decoder).WriteString(") Presence() []rasql.Presence { return nil }\n")
	b.WriteString("func (").WriteString(in.Decoder).WriteString(") DecodeRow(s rasql.ScanSource, r *").WriteString(in.Result).WriteString(") error {\n")
	b.WriteString("\tif err := s.Scan(")
	for i, value := range in.Results {
		field := value.Go
		if i > 0 {
			b.WriteString(", ")
		}
		name := exported(field.Name)
		b.WriteString("&r.").WriteString(name)
	}
	b.WriteString("); err != nil { return err }\n")
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString("func ").WriteString(in.Decoder).WriteString("Schema() rasql.ResultSchema { s, _ := rasql.NewResultSchema(\n")
	for _, value := range in.Results {
		field := value.Go
		typ, err := renderSchemaType(value.Semantic)
		if err != nil {
			return nil, fmt.Errorf("result %q: %w", field.Name, err)
		}
		b.WriteString("\t\trasql.ResultColumn{Name: ").WriteString(strconv.Quote(field.Name)).WriteString(", Type: ")
		b.WriteString(typ).WriteString(", Nullable: ").WriteString(fmt.Sprint(field.Nullable)).WriteString(", Codec: ").WriteString(strconv.Quote(field.Codec)).WriteString("},\n")
	}
	b.WriteString("\t); return s }\n\n")
	b.WriteString("func ").WriteString(in.Function).Byte('(')
	writeParams(&b, in.Parameters)
	b.WriteString(") (rasql.Query[").WriteString(in.Result).WriteString("], error) {\n")
	b.WriteString("\tprojection, err := rasql.NativeProjection[").WriteString(in.Result).WriteString("](").WriteString(in.Decoder).WriteString("{}); if err != nil { return rasql.Query[").WriteString(in.Result).WriteString("]{}, err }; return rasql.Native[").WriteString(in.Result).WriteString("](rasql.NativeStatement{Engine: ").WriteString(strconv.Quote(in.Engine)).WriteString(", SQL: ").WriteString(strconv.Quote(in.SQL)).WriteString(", Args: ")
	writeArgs(&b, in.Parameters, in.ArgumentNames)
	b.WriteString("}, projection, rasql.").WriteString(cardinality(in.Cardinality)).WriteString(")\n}\n")
	return format.Source(b.Bytes())
}

func typedMutationSource(in TypedInput) ([]byte, error) {
	var b sourceBuilder
	b.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\npackage ").WriteString(in.Package).WriteString("\n\n")
	writeImports(&b, in.Imports, false, in.Parameters)
	b.WriteString("func ").WriteString(in.Function).Byte('(')
	writeParams(&b, in.Parameters)
	b.WriteString(") (rasql.MutationPlan, error) { return rasql.NativeMutation(rasql.NativeStatement{Engine: ").WriteString(strconv.Quote(in.Engine)).WriteString(", SQL: ").WriteString(strconv.Quote(in.SQL)).WriteString(", Args: ")
	writeArgs(&b, in.Parameters, in.ArgumentNames)
	b.WriteString("}) }\n")
	return format.Source(b.Bytes())
}

func writeParams(b *sourceBuilder, values []TypedValue) {
	fields := make([]compilerir.GoField, len(values))
	for i := range values {
		fields[i] = values[i].Go
	}
	for i, field := range fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name).Byte(' ').WriteString(field.Type)
	}
}
func writeArgs(b *sourceBuilder, values []TypedValue, names []string) {
	fields := make([]compilerir.GoField, len(values))
	for i := range values {
		fields[i] = values[i].Go
	}
	b.WriteString("[]rasql.NativeArgument{")
	if len(names) == 0 {
		names = make([]string, len(fields))
		for i := range fields {
			names[i] = fields[i].Name
		}
	}
	byName := make(map[string]compilerir.GoField, len(fields))
	for _, field := range fields {
		byName[field.Name] = field
	}
	for _, name := range names {
		field, ok := byName[name]
		if !ok {
			continue
		}
		b.WriteString("{Value: ").WriteString(field.Name).WriteString(", Codec: ").WriteString(strconv.Quote(field.Codec)).WriteString("},")
	}
	b.Byte('}')
}
func cardinality(value string) string {
	switch value {
	case "one":
		return "ExactlyOne"
	case "maybe":
		return "AtMostOne"
	default:
		return "Many"
	}
}
func exported(value string) string {
	var b strings.Builder
	upper := true
	for _, r := range value {
		if r == '_' || r == '-' {
			upper = true
			continue
		}
		if upper {
			b.WriteString(strings.ToUpper(string(r)))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "Value"
	}
	result := b.String()
	for suffix, replacement := range map[string]string{"Id": "ID", "Url": "URL", "Uri": "URI", "Http": "HTTP", "Api": "API"} {
		if strings.HasSuffix(result, suffix) {
			result = strings.TrimSuffix(result, suffix) + replacement
		}
	}
	return result
}
func writeImports(b *sourceBuilder, imports []compilerir.GoImport, result bool, values []TypedValue) {
	b.Byte('\n')
	b.WriteString("import (\n\t\"github.com/lestrrat-go/rasql\"\n")
	if result {
		b.WriteString("\t\"github.com/lestrrat-go/rasql/schema\"\n")
	}
	seen := map[string]bool{"github.com/lestrrat-go/rasql": true, "github.com/lestrrat-go/rasql/schema": true}
	for _, imp := range imports {
		name := imp.Alias
		if name == "" {
			parts := strings.Split(imp.Path, "/")
			name = parts[len(parts)-1]
		}
		used := false
		for _, value := range values {
			if strings.Contains(value.Go.Type, name+".") || strings.Contains(value.Go.Type, name+"[") {
				used = true
				break
			}
		}
		if !used {
			continue
		}
		key := imp.Path + "\x00" + imp.Alias
		if imp.Path == "" || seen[key] {
			continue
		}
		seen[key] = true
		b.WriteString("\t")
		if imp.Alias != "" {
			b.WriteString(imp.Alias).Byte(' ')
		}
		b.WriteString(strconv.Quote(imp.Path)).Byte('\n')
	}
	b.WriteString(")\n\n")
}

func renderSchemaType(value compilerir.SemanticValue) (string, error) {
	scalar := value.LogicalKind
	switch scalar {
	case "boolean":
		return "schema.BooleanType{}", nil
	case "integer":
		if value.Integer == nil {
			return "schema.IntegerType{}", nil
		}
		return fmt.Sprintf("schema.IntegerType{Unsigned: %t, ZeroFill: %t}", value.Integer.Unsigned, value.Integer.ZeroFill), nil
	case "float":
		return "schema.FloatType{}", nil
	case "text":
		return "schema.TextType{}", nil
	case "bytes", "json":
		return "schema.BytesType{}", nil
	case "time":
		return "schema.TimeType{}", nil
	case "uuid":
		return "schema.UUIDType{}", nil
	default:
		return "", fmt.Errorf("unsupported logical type %q; canonical schema facts are required", scalar)
	}
}
