package querygen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/lestrrat-go/rasql/internal/compilerir"
)

// TypedInput is the immutable compiler output needed for one native query.
type TypedInput struct {
	Package, Function, Engine, SQL, Operation, Cardinality string
	Result, Projection, Decoder                            string
	Parameters, Results                                    []compilerir.GoField
}

type sourceBuilder struct{ bytes.Buffer }

func (b *sourceBuilder) WriteString(value string) *sourceBuilder {
	_, _ = b.Buffer.WriteString(value)
	return b
}
func (b *sourceBuilder) WriteByte(value byte) *sourceBuilder { _ = b.Buffer.WriteByte(value); return b }

// TypedGoSource emits a lock-backed constructor. It deliberately emits only
// plan construction; callers choose All, Maybe, One, Rows, or ExecMutation.
func TypedGoSource(in TypedInput) ([]byte, error) {
	if in.Package == "" || in.Function == "" || strings.TrimSpace(in.SQL) == "" || in.Engine == "" {
		return nil, fmt.Errorf("querygen: incomplete typed query")
	}
	if in.Operation == "exec" {
		return typedMutationSource(in)
	}
	if len(in.Results) == 0 {
		return nil, fmt.Errorf("querygen: typed query %q has no results", in.Function)
	}
	if in.Result == "" {
		in.Result = in.Function + "Result"
	}
	if in.Projection == "" {
		in.Projection = in.Function + "Projection"
	}
	if in.Decoder == "" {
		in.Decoder = in.Function + "Decoder"
	}
	var b sourceBuilder
	b.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\npackage ")
	b.WriteString(in.Package)
	b.WriteString("\n\nimport (\n\t\"github.com/lestrrat-go/rasql\"\n\t\"github.com/lestrrat-go/rasql/schema\"\n)\n\n")
	b.WriteString("type ").WriteString(in.Result).WriteString(" struct {\n")
	for _, field := range in.Results {
		b.WriteString("\t").WriteString(exported(field.Name)).WriteByte(' ').WriteString(field.Type).WriteString("\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("type ").WriteString(in.Decoder).WriteString(" struct{}\n")
	b.WriteString("func (").WriteString(in.Decoder).WriteString(") ResultSchema() rasql.ResultSchema { return ").WriteString(in.Decoder).WriteString("Schema() }\n")
	b.WriteString("func (").WriteString(in.Decoder).WriteString(") Presence() []rasql.Presence { return nil }\n")
	b.WriteString("func (").WriteString(in.Decoder).WriteString(") DecodeRow(s rasql.ScanSource, r *").WriteString(in.Result).WriteString(") error {\n")
	for _, field := range in.Results {
		name := exported(field.Name)
		if field.Nullable {
			b.WriteString("\tvar ").WriteString(name).WriteString(" any; if err := s.Scan(&").WriteString(name).WriteString("); err != nil { return err }; if ").WriteString(name).WriteString(" == nil { r.").WriteString(name).WriteString(".Valid = false } else { if err := rasql.ScanValue(&r.").WriteString(name).WriteString(".Value, ").WriteString(name).WriteString("); err != nil { return err }; r.").WriteString(name).WriteString(".Valid = true }\n")
			continue
		}
		b.WriteString("\tif err := s.Scan(&r.").WriteString(name).WriteString("); err != nil { return err }\n")
	}
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString("func ").WriteString(in.Decoder).WriteString("Schema() rasql.ResultSchema { s, _ := rasql.NewResultSchema(\n")
	for _, field := range in.Results {
		b.WriteString("\t\trasql.ResultColumn{Name: ").WriteString(strconv.Quote(field.Name)).WriteString(", Type: ")
		b.WriteString(schemaType(field.Type)).WriteString(", Nullable: ").WriteString(fmt.Sprint(field.Nullable)).WriteString(", Codec: ").WriteString(strconv.Quote(field.Codec)).WriteString("},\n")
	}
	b.WriteString("\t); return s }\n\n")
	b.WriteString("func ").WriteString(in.Function).WriteByte('(')
	writeParams(&b, in.Parameters)
	b.WriteString(") (rasql.Query[").WriteString(in.Result).WriteString("], error) {\n")
	b.WriteString("\tprojection, err := rasql.NewProjection([]rasql.ProjectionItem{\n")
	for _, field := range in.Results {
		zero := zeroValue(field.Type)
		if field.Nullable {
			b.WriteString("\t\trasql.NullItem(").WriteString(strconv.Quote(field.Name)).WriteString(", rasql.MinExpr(rasql.Value[").WriteString(nullableBase(field.Type)).WriteByte(']').WriteString("(").WriteString(zeroValue(nullableBase(field.Type))).WriteString(")), ").WriteString(schemaType(field.Type)).WriteString(", ").WriteString(strconv.Quote(field.Codec)).WriteString("),\n")
		} else {
			b.WriteString("\t\trasql.Item(").WriteString(strconv.Quote(field.Name)).WriteString(", rasql.Value[").WriteString(field.Type).WriteByte(']').WriteString("(").WriteString(zero).WriteString("), ").WriteString(schemaType(field.Type)).WriteString(", ").WriteString(strconv.Quote(field.Codec)).WriteString("),\n")
		}
	}
	b.WriteString("\t}, ").WriteString(in.Decoder).WriteString("{}); if err != nil { return rasql.Query[").WriteString(in.Result).WriteString("]{}, err }; return rasql.Native[").WriteString(in.Result).WriteString("](rasql.NativeStatement{Engine: ").WriteString(strconv.Quote(in.Engine)).WriteString(", SQL: ").WriteString(strconv.Quote(in.SQL)).WriteString(", Args: ")
	writeArgs(&b, in.Parameters)
	b.WriteString("}, projection, rasql.").WriteString(cardinality(in.Cardinality)).WriteString(")\n}\n")
	return format.Source(b.Bytes())
}

func typedMutationSource(in TypedInput) ([]byte, error) {
	var b sourceBuilder
	b.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\npackage ").WriteString(in.Package).WriteString("\n\nimport \"github.com/lestrrat-go/rasql\"\n\nfunc ").WriteString(in.Function).WriteByte('(')
	writeParams(&b, in.Parameters)
	b.WriteString(") (rasql.MutationPlan, error) { return rasql.NativeMutation(rasql.NativeStatement{Engine: ").WriteString(strconv.Quote(in.Engine)).WriteString(", SQL: ").WriteString(strconv.Quote(in.SQL)).WriteString(", Args: ")
	writeArgs(&b, in.Parameters)
	b.WriteString("}) }\n")
	return format.Source(b.Bytes())
}

func writeParams(b *sourceBuilder, fields []compilerir.GoField) {
	for i, field := range fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name).WriteByte(' ').WriteString(field.Type)
	}
}
func writeArgs(b *sourceBuilder, fields []compilerir.GoField) {
	b.WriteString("[]rasql.NativeArgument{")
	for _, field := range fields {
		b.WriteString("{Value: ").WriteString(field.Name).WriteString(", Codec: ").WriteString(strconv.Quote(field.Codec)).WriteString("},")
	}
	b.WriteByte('}')
}
func cardinality(value string) string {
	switch value {
	case "one":
		return "ExactlyOne"
	case "maybe":
		return "AtMostOne"
	default:
		return "Many"
	}
}
func exported(value string) string {
	var b strings.Builder
	upper := true
	for _, r := range value {
		if r == '_' || r == '-' {
			upper = true
			continue
		}
		if upper {
			b.WriteString(strings.ToUpper(string(r)))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "Value"
	}
	result := b.String()
	for suffix, replacement := range map[string]string{"Id": "ID", "Url": "URL", "Uri": "URI", "Http": "HTTP", "Api": "API"} {
		if strings.HasSuffix(result, suffix) {
			result = strings.TrimSuffix(result, suffix) + replacement
		}
	}
	return result
}
func nullableBase(value string) string {
	if strings.HasPrefix(value, "rasql.Nullable[") {
		return strings.TrimSuffix(strings.TrimPrefix(value, "rasql.Nullable["), "]")
	}
	return value
}
func zeroValue(value string) string {
	switch value {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int64", "uint64", "float64":
		return "0"
	case "[]byte":
		return "nil"
	default:
		return value + "{}"
	}
}
func schemaType(value string) string {
	scalar := strings.TrimPrefix(strings.TrimPrefix(value, "rasql.Nullable["), "]")
	if strings.HasPrefix(value, "rasql.Nullable[") {
		scalar = strings.TrimSuffix(strings.TrimPrefix(value, "rasql.Nullable["), "]")
	}
	switch scalar {
	case "bool":
		scalar = "boolean"
	case "int64":
		scalar = "integer"
	case "uint64":
		scalar = "unsigned_integer"
	case "float64":
		scalar = "float"
	case "string":
		scalar = "text"
	case "[]byte":
		scalar = "bytes"
	case "time.Time":
		scalar = "time"
	}
	switch scalar {
	case "boolean":
		return "schema.BooleanType{}"
	case "integer":
		return "schema.IntegerType{}"
	case "unsigned_integer":
		return "schema.IntegerType{Unsigned: true}"
	case "float":
		return "schema.FloatType{}"
	case "text":
		return "schema.TextType{}"
	case "bytes", "json":
		return "schema.BytesType{}"
	case "time":
		return "schema.TimeType{}"
	case "uuid":
		return "schema.UUIDType{}"
	case "decimal":
		return "schema.DecimalType{Precision: 1, Scale: schema.NewDecimalScale(0)}"
	default:
		return "schema.OpaqueType{}"
	}
}
