//go:build unix

package inspect_test

import (
	"testing"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/lestrrat-go/rasql/dialect"
	"github.com/lestrrat-go/rasql/inspect"
	"github.com/lestrrat-go/rasql/internal/dbtest"
	"github.com/lestrrat-go/rasql/schema"
	"github.com/stretchr/testify/require"
)

// TestPostgreSQLInspectorRecordsIdentityColumnsAgainstLiveDatabase pins
// what a real PostgreSQL server reports back for both identity
// generations, because a fixture test only asserts rasql's own mocked
// catalog echoes what the test told it to. Before this feature existed,
// the PostgreSQL columns query selected no identity metadata at all, so an
// identity column inspected silently as an ordinary column -- the exact
// gap this test proves no longer exists against a real server.
func TestPostgreSQLInspectorRecordsIdentityColumnsAgainstLiveDatabase(t *testing.T) {
	ctx := t.Context()
	database := dbtest.PostgreSQLDB(t)

	mustExec(t, ctx, database, "CREATE TABLE live_identity_always (id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)")
	mustExec(t, ctx, database, "CREATE TABLE live_identity_by_default (id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)")

	inspector, err := inspect.New(database, dialect.PostgreSQL())
	require.NoError(t, err)

	alwaysTable, err := inspector.Table(ctx, "live_identity_always")
	require.NoError(t, err)
	alwaysID, ok := columnNamed(alwaysTable.Columns, "id")
	require.True(t, ok, "inspected table has an id column")
	require.Equal(t, schema.IdentityAlways, alwaysID.Identity,
		"is_identity = 'YES' and identity_generation = 'ALWAYS' must map to schema.IdentityAlways")
	require.False(t, alwaysID.Nullable, "an identity column must report is_nullable = NO")
	require.Empty(t, alwaysID.Default, "an identity column carries no separate Default: column_default is empty for one, unlike a nextval(...) BIGSERIAL default")

	byDefaultTable, err := inspector.Table(ctx, "live_identity_by_default")
	require.NoError(t, err)
	byDefaultID, ok := columnNamed(byDefaultTable.Columns, "id")
	require.True(t, ok, "inspected table has an id column")
	require.Equal(t, schema.IdentityByDefault, byDefaultID.Identity,
		"is_identity = 'YES' and identity_generation = 'BY DEFAULT' must map to schema.IdentityByDefault")
	require.False(t, byDefaultID.Nullable, "an identity column must report is_nullable = NO")

	// PostgreSQL itself refuses an explicit value for an ALWAYS identity
	// column -- this is the exact refusal the typed write path's exclusion
	// of an ALWAYS identity column from the INSERT column list exists to
	// prevent (see typedInsertMany in typed_write.go). SQLSTATE 428C9 is
	// "generated_always" per PostgreSQL's own errcodes.txt.
	_, err = database.ExecContext(ctx, "INSERT INTO live_identity_always (id, name) VALUES (1, 'x')")
	require.Error(t, err, "PostgreSQL must refuse an explicit value for an ALWAYS identity column")
	var pgErr *pgconn.PgError
	require.ErrorAs(t, err, &pgErr, "the refusal must come from PostgreSQL itself, not from a connection or driver failure")
	require.Equal(t, "428C9", pgErr.Code, "PostgreSQL's own SQLSTATE for an explicit value into a GENERATED ALWAYS identity column")

	// A BY DEFAULT identity column, by contrast, accepts and keeps an
	// explicit value.
	_, err = database.ExecContext(ctx, "INSERT INTO live_identity_by_default (id, name) VALUES (7, 'y')")
	require.NoError(t, err, "PostgreSQL must accept an explicit value for a BY DEFAULT identity column")
	var keptID int64
	require.NoError(t, database.QueryRowContext(ctx, "SELECT id FROM live_identity_by_default WHERE name = 'y'").Scan(&keptID))
	require.Equal(t, int64(7), keptID, "a BY DEFAULT identity column must keep the explicit value rather than overwrite it")
}

// TestMySQLInspectorRecordsIdentityColumnAgainstLiveDatabase pins what a
// real MySQL server reports back for an AUTO_INCREMENT column, because a
// fixture test only asserts rasql's own mocked catalog echoes what the
// test told it to. MySQL has no ALWAYS-shaped form at all, so only
// schema.IdentityByDefault is ever produced.
func TestMySQLInspectorRecordsIdentityColumnAgainstLiveDatabase(t *testing.T) {
	ctx := t.Context()
	database := dbtest.MySQLDB(t)

	mustExec(t, ctx, database, "CREATE TABLE live_identity_members (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL) ENGINE=InnoDB")

	inspector, err := inspect.New(database, dialect.MySQL())
	require.NoError(t, err)
	table, err := inspector.Table(ctx, "live_identity_members")
	require.NoError(t, err)

	id, ok := columnNamed(table.Columns, "id")
	require.True(t, ok, "inspected table has an id column")
	require.Equal(t, schema.IdentityByDefault, id.Identity,
		"extra = 'auto_increment' must map to schema.IdentityByDefault: MySQL has no form that rejects an explicit value")
	require.False(t, id.Nullable, "MySQL reports is_nullable = NO for an AUTO_INCREMENT column even when declared without NOT NULL")
}
