package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/lestrrat-go/rasql/internal/compilerir"
	"github.com/lestrrat-go/rasql/schema"
)

// CompactObject is the canonical input for one compact generated object file.
// The renderer consumes all four compiler layers so generated declarations do
// not have to rediscover physical facts from the Go model.
type CompactObject struct {
	Catalog    compilerir.PhysicalObject
	Semantic   compilerir.SemanticObject
	Go         compilerir.GoObject
	Generation compilerir.ObjectGoName
	Table      schema.TableDef
	Mappings   []compilerir.ScalarMapping
	Targets    map[compilerir.ObjectID]CompactObjectRef
}

// CompactObjectRef carries the canonical names and relation facts needed by
// declarations that connect one generated object to another.
type CompactObjectRef struct {
	Catalog    compilerir.PhysicalObject
	Semantic   compilerir.SemanticObject
	Go         compilerir.GoObject
	Generation compilerir.ObjectGoName
	Table      schema.TableDef
}

// CompactObjectSource emits the compact table or view declarations for one
// object. It returns one formatted source file and never performs database
// work or retains mutable input state.
func CompactObjectSource(packageName string, object CompactObject) ([]byte, error) {
	if packageName == "" || object.Generation.File == "" {
		return nil, fmt.Errorf("compact: package and output file are required")
	}
	definition, err := TableDefinitionLiteral(object.Table)
	if err != nil {
		return nil, err
	}
	row := object.Generation.Row
	if row == "" {
		row = exportedCompact(object.Catalog.Name) + "Row"
	}
	accessor := object.Generation.Source
	if accessor == "" {
		accessor = exportedCompact(object.Catalog.Name)
	}
	if row == "" || accessor == "" {
		return nil, fmt.Errorf("compact: object %q has incomplete generated names", object.Catalog.ID)
	}
	if err := validateCompactSymbols(object, accessor, row); err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\npackage ")
	b.WriteString(packageName)
	b.WriteString("\n\nimport (\n")
	b.WriteString("\t\"github.com/lestrrat-go/rasql\"\n")
	b.WriteString("\t\"github.com/lestrrat-go/rasql/schema\"\n")
	for _, imp := range compactImports(object) {
		b.WriteString("\t")
		if imp.Alias != "" {
			b.WriteString(imp.Alias)
			b.WriteByte(' ')
		}
		b.WriteString(strconv.Quote(imp.Path))
		b.WriteByte('\n')
	}
	b.WriteString(")\n\n")
	b.WriteString("type ")
	b.WriteString(row)
	b.WriteString(" struct {\n")
	for _, group := range compactFieldGroups(object.Go.Row.Fields) {
		b.WriteString("\t")
		b.WriteString(strings.Join(group.Names, ", "))
		b.WriteByte(' ')
		b.WriteString(group.Type)
		b.WriteByte('\n')
	}
	b.WriteString("}\n\n")

	definitionName := compactLowerFirst(accessor) + "Definition"
	tableName := compactLowerFirst(accessor) + "Table"
	b.WriteString("var ")
	b.WriteString(definitionName)
	b.WriteString(" = ")
	b.WriteString(definition)
	b.WriteString("\n\n")
	if object.Catalog.Kind == "view" {
		b.WriteString("var ")
		b.WriteString(tableName)
		b.WriteString(" = rasql.MustReadTableOf[")
		b.WriteString(row)
		b.WriteString("](")
		b.WriteString(definitionName)
		b.WriteString(")\n\n")
	} else {
		b.WriteString("var ")
		b.WriteString(tableName)
		b.WriteString(" = rasql.MustTableOf[")
		b.WriteString(row)
		b.WriteString("](")
		b.WriteString(definitionName)
		b.WriteString(")\n\n")
	}
	b.WriteString("type ")
	b.WriteString(accessor)
	b.WriteString("Table struct { rasql.")
	if object.Catalog.Kind == "view" {
		b.WriteString("ReadTable[")
	} else {
		b.WriteString("Table[")
	}
	b.WriteString(row)
	b.WriteString("] }\n\nfunc ")
	b.WriteString(accessor)
	b.WriteString("() ")
	b.WriteString(accessor)
	b.WriteString("Table { return ")
	b.WriteString(accessor)
	if object.Catalog.Kind == "view" {
		b.WriteString("Table{ReadTable: ")
	} else {
		b.WriteString("Table{Table: ")
	}
	b.WriteString(tableName)
	b.WriteString("} }\n\n")
	b.WriteString("func (t ")
	b.WriteString(accessor)
	b.WriteString("Table) Source(alias string) (rasql.TypedRelation[")
	b.WriteString(row)
	b.WriteString("], error) { return rasql.SourceOf[")
	b.WriteString(row)
	if object.Catalog.Kind == "view" {
		b.WriteString("](t.ReadTable, alias) }\n\n")
	} else {
		b.WriteString("](t.Table, alias) }\n\n")
	}

	writeCompactColumns(&b, object, accessor, row)
	writeCompactDecoder(&b, object, accessor, row, false)
	marker := compactMarker(object.Table)
	if len(marker) > 0 {
		writeCompactDecoder(&b, object, accessor, row, true)
	}
	writeCompactProjections(&b, object, accessor, row, len(marker) > 0)
	writeCompactKeys(&b, object, accessor, row, marker)
	writeCompactRelations(&b, object, accessor, row)
	if object.Catalog.Kind != "view" {
		writeCompactMutations(&b, object, accessor, row)
	}
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("compact %s: format source: %w", object.Catalog.ID, err)
	}
	return formatted, nil
}

func validateCompactSymbols(object CompactObject, accessor, row string) error {
	fields := make(map[string]string, len(object.Go.Columns)+1)
	for _, column := range object.Go.Columns {
		if !columnReadable(object.Semantic, column.Name) {
			continue
		}
		name := exportedCompact(column.Name)
		if previous, exists := fields[name]; exists {
			return fmt.Errorf("compact %s: row field %q from %s collides with %s", object.Catalog.ID, name, column.Name, previous)
		}
		fields[name] = column.Name
	}
	if previous, exists := fields["ScanRow"]; exists {
		return fmt.Errorf("compact %s: row field %q from %s collides with generated ScanRow", object.Catalog.ID, "ScanRow", previous)
	}
	checkMethods := func(shape *compilerir.GoShape, receiver, terminal string) error {
		if shape == nil {
			return nil
		}
		methods := make(map[string]string, len(shape.Fields)+3)
		addMethod := func(name, source string) error {
			if previous, exists := methods[name]; exists {
				return fmt.Errorf("compact %s: %s method %q from %s collides with %s", object.Catalog.ID, receiver, name, source, previous)
			}
			methods[name] = source
			return nil
		}
		for _, field := range shape.Fields {
			name := exportedCompact(field.Name)
			if err := addMethod(name, field.Name); err != nil {
				return err
			}
			if column, ok := goColumnByName(object.Go, field.Name); ok && column.Nullable {
				if err := addMethod("Clear"+name, field.Name); err != nil {
					return err
				}
			}
			if columnHasDefault(object.Table, field.Name) {
				if err := addMethod("Default"+name, field.Name); err != nil {
					return err
				}
			}
		}
		if previous, exists := methods[terminal]; exists {
			return fmt.Errorf("compact %s: %s method %q from %s collides with generated %s", object.Catalog.ID, receiver, terminal, previous, terminal)
		}
		return nil
	}
	if object.Catalog.Kind != "view" {
		if err := checkMethods(object.Go.Create, "create", "Plan"); err != nil {
			return err
		}
		if err := checkMethods(object.Go.Patch, "patch", "Where"); err != nil {
			return err
		}
	}
	return nil
}

type compactImport struct{ Path, Alias string }

type compactFieldGroup struct {
	Names []string
	Type  string
}

func appendCompactFieldGroup(groups []compactFieldGroup, name, typ string) []compactFieldGroup {
	if len(groups) > 0 && groups[len(groups)-1].Type == typ {
		groups[len(groups)-1].Names = append(groups[len(groups)-1].Names, name)
		return groups
	}
	return append(groups, compactFieldGroup{Names: []string{name}, Type: typ})
}

func compactFieldGroups(fields []compilerir.GoField) []compactFieldGroup {
	groups := make([]compactFieldGroup, 0, len(fields))
	for _, field := range fields {
		groups = appendCompactFieldGroup(groups, exportedCompact(field.Name), field.Type)
	}
	return groups
}

func compactImports(object CompactObject) []compactImport {
	seen := map[string]compactImport{}
	for _, column := range object.Go.Columns {
		if strings.Contains(column.GoType, "time.Time") {
			seen["time"] = compactImport{Path: "time"}
		}
		mapping, ok := compilerir.DefaultScalarMapping(column.Scalar)
		if !ok {
			for _, candidate := range object.Mappings {
				if candidate.Name == column.Scalar {
					mapping, ok = candidate, true
					break
				}
			}
		}
		if ok {
			for _, imp := range mapping.Imports {
				seen[imp.Path] = compactImport{Path: imp.Path, Alias: imp.Alias}
			}
		}
	}
	result := make([]compactImport, 0, len(seen))
	for _, imp := range seen {
		if imp.Path == "github.com/lestrrat-go/rasql" || imp.Path == "github.com/lestrrat-go/rasql/schema" {
			continue
		}
		result = append(result, imp)
	}
	slicesSortImports(result)
	return result
}

func slicesSortImports(values []compactImport) {
	for i := 1; i < len(values); i++ {
		for j := i; j > 0 && values[j].Path < values[j-1].Path; j-- {
			values[j], values[j-1] = values[j-1], values[j]
		}
	}
}

func writeCompactColumns(b *bytes.Buffer, object CompactObject, accessor, row string) {
	b.WriteString("type ")
	b.WriteString(accessor)
	b.WriteString("Columns struct{}\n\ntype ")
	b.WriteString(accessor)
	b.WriteString("Expressions struct {\n")
	groups := make([]compactFieldGroup, 0, len(object.Go.Columns))
	for _, column := range object.Go.Columns {
		if !columnReadable(object.Semantic, column.Name) {
			continue
		}
		typ := "rasql.Column[" + row + "," + compactColumnValueType(object, column) + "]"
		if column.Nullable {
			typ = "rasql.NullColumn[" + row + "," + compactColumnValueType(object, column) + "]"
		}
		groups = appendCompactFieldGroup(groups, exportedCompact(column.Name), typ)
	}
	for _, group := range groups {
		b.WriteString("\t")
		b.WriteString(strings.Join(group.Names, ", "))
		b.WriteByte(' ')
		b.WriteString(group.Type)
		b.WriteByte('\n')
	}
	b.WriteString("}\n\ntype Optional")
	b.WriteString(accessor)
	b.WriteString("Expressions struct {\n")
	groups = groups[:0]
	for _, column := range object.Go.Columns {
		if !columnReadable(object.Semantic, column.Name) {
			continue
		}
		groups = appendCompactFieldGroup(groups, exportedCompact(column.Name), "rasql.NullColumn["+row+","+compactColumnValueType(object, column)+"]")
	}
	for _, group := range groups {
		b.WriteString("\t")
		b.WriteString(strings.Join(group.Names, ", "))
		b.WriteByte(' ')
		b.WriteString(group.Type)
		b.WriteByte('\n')
	}
	b.WriteString("}\n\n")

	writeCompactBinder(b, object, accessor, row, false)
	writeCompactBinder(b, object, accessor, row, true)
}

func writeCompactBinder(b *bytes.Buffer, object CompactObject, accessor, row string, optional bool) {
	name := "Bind"
	result := accessor + "Expressions"
	if optional {
		name = "BindOptional"
		result = "Optional" + accessor + "Expressions"
	}
	b.WriteString("func (")
	b.WriteString(accessor)
	b.WriteString("Columns) ")
	b.WriteString(name)
	if optional {
		b.WriteString("(source rasql.OptionalRelation[")
	} else {
		b.WriteString("(source rasql.TypedRelation[")
	}
	b.WriteString(row)
	b.WriteString("]) (")
	b.WriteString(result)
	b.WriteString(", error) {\n")
	b.WriteString("\tvar err error\n\tresult := ")
	b.WriteString(result)
	b.WriteString("{\n")
	for _, column := range object.Go.Columns {
		if !columnReadable(object.Semantic, column.Name) {
			continue
		}
		b.WriteString("\t\t")
		b.WriteString(exportedCompact(column.Name))
		b.WriteString(": rasqlgenBind(&err, source, ")
		b.WriteString(strconv.Quote(column.PhysicalName))
		b.WriteString(", ")
		b.WriteString(strconv.Quote(column.Codec))
		b.WriteString(", rasql.")
		if optional {
			b.WriteString("BindOptionalColumn[")
		} else if column.Nullable {
			b.WriteString("BindNullColumn[")
		} else {
			b.WriteString("BindColumn[")
		}
		b.WriteString(row)
		b.WriteByte(',')
		b.WriteString(compactColumnValueType(object, column))
		b.WriteString("]),\n")
	}
	b.WriteString("\t}\n\treturn result, err\n}\n\n")
}

func writeCompactDecoder(b *bytes.Buffer, object CompactObject, accessor, row string, optional bool) {
	name := compactLowerFirst(accessor) + "Decoder"
	if optional {
		name = compactLowerFirst(accessor) + "OptionalDecoder"
	}
	schemaName := compactLowerFirst(accessor) + "ResultSchema"
	if optional {
		schemaName = compactLowerFirst(accessor) + "OptionalResultSchema"
	}
	baseColumnsName := compactLowerFirst(accessor) + "ResultColumns"
	if !optional {
		b.WriteString("var ")
		b.WriteString(baseColumnsName)
		b.WriteString(" = []rasql.ResultColumn{\n")
		for _, column := range object.Go.Columns {
			if !columnReadable(object.Semantic, column.Name) {
				continue
			}
			b.WriteString("\t{Name: ")
			b.WriteString(strconv.Quote(column.PhysicalName))
			b.WriteString(", Type: ")
			b.WriteString(compactSchemaType(object.Table, column.PhysicalName))
			if column.Nullable {
				b.WriteString(", Nullable: true")
			}
			b.WriteString(", Codec: ")
			b.WriteString(strconv.Quote(column.Codec))
			b.WriteString("},\n")
		}
		b.WriteString("}\n")
		b.WriteString("var ")
		b.WriteString(schemaName)
		b.WriteString(" = rasqlgenResultSchema(")
		b.WriteString(baseColumnsName)
		b.WriteString(")\n\n")
	} else {
		b.WriteString("var ")
		b.WriteString(schemaName)
		b.WriteString(" = rasqlgenOptionalResultSchema(")
		b.WriteString(baseColumnsName)
		b.WriteString(")\n\n")
	}
	b.WriteString("type ")
	b.WriteString(name)
	b.WriteString(" struct{}\nfunc (")
	b.WriteString(name)
	b.WriteString(") ResultSchema() rasql.ResultSchema { return ")
	b.WriteString(schemaName)
	b.WriteString(" }\nfunc (")
	b.WriteString(name)
	b.WriteString(") Presence() []rasql.Presence {")
	if optional {
		marker := compactMarker(object.Table)
		b.WriteString(" p, err := rasql.NewPresence(")
		b.WriteString(strconv.Quote(accessor))
		for _, column := range marker {
			b.WriteString(", ")
			b.WriteString(strconv.Quote(column))
		}
		b.WriteString("); if err != nil { panic(err) }; return []rasql.Presence{p}")
	} else {
		b.WriteString(" return nil")
	}
	b.WriteString(" }\n")
	b.WriteString("func (")
	b.WriteString(name)
	b.WriteString(") DecodeRow(source rasql.ScanSource, row *")
	b.WriteString(row)
	b.WriteString(") error {\n")
	if optional {
		valueGroups := make([]compactFieldGroup, 0, len(object.Go.Columns))
		for _, column := range object.Go.Columns {
			if !columnReadable(object.Semantic, column.Name) {
				continue
			}
			if compactNullableDirect(object, column) {
				continue
			}
			valueGroups = appendCompactFieldGroup(valueGroups, exportedCompact(column.Name)+"Value", "rasql.Nullable["+compactColumnValueType(object, column)+"]")
		}
		for _, group := range valueGroups {
			b.WriteString("\tvar ")
			b.WriteString(strings.Join(group.Names, ", "))
			b.WriteByte(' ')
			b.WriteString(group.Type)
			b.WriteByte('\n')
		}
	}
	if optional {
		b.WriteString("\tif err := source.Scan(")
	} else {
		b.WriteString("\treturn source.Scan(")
	}
	first := true
	for _, column := range object.Go.Columns {
		if !columnReadable(object.Semantic, column.Name) {
			continue
		}
		if !first {
			b.WriteString(", ")
		}
		first = false
		if optional {
			b.WriteString("&")
			if compactNullableDirect(object, column) {
				b.WriteString("row.")
				b.WriteString(exportedCompact(column.Name))
			} else {
				b.WriteString(exportedCompact(column.Name))
				b.WriteString("Value")
			}
		} else {
			b.WriteString("&row.")
			b.WriteString(exportedCompact(column.Name))
		}
	}
	if optional {
		b.WriteString("); err != nil { return err }\n")
	} else {
		b.WriteString(")\n}\n\n")
		b.WriteString("func (row *")
		b.WriteString(row)
		b.WriteString(") ScanRow(source rasql.ScanSource) error { return ")
		b.WriteString(name)
		b.WriteString("{}.DecodeRow(source, row) }\n\n")
		return
	}
	if optional {
		for _, column := range object.Go.Columns {
			if !columnReadable(object.Semantic, column.Name) {
				continue
			}
			if compactNullableDirect(object, column) {
				continue
			}
			b.WriteString("\trasqlgenAssignNullable(")
			b.WriteString(exportedCompact(column.Name))
			b.WriteString("Value, &row.")
			b.WriteString(exportedCompact(column.Name))
			b.WriteString(")\n")
		}
	}
	b.WriteString("\treturn nil\n}\n\n")
}

func writeCompactProjections(b *bytes.Buffer, object CompactObject, accessor, row string, optional bool) {
	writeProjection := func(name string, optionalProjection bool) {
		b.WriteString("func ")
		b.WriteString(name)
		b.WriteString("(expressions ")
		if optionalProjection {
			b.WriteString("Optional")
		}
		b.WriteString(accessor)
		b.WriteString("Expressions) (rasql.Projection[")
		b.WriteString(row)
		b.WriteString("], error) {\n\titems := []rasql.ProjectionItem{\n")
		for _, column := range object.Go.Columns {
			if !columnReadable(object.Semantic, column.Name) {
				continue
			}
			field := exportedCompact(column.Name)
			b.WriteString("\t\t")
			if optionalProjection || column.Nullable {
				b.WriteString("rasql.NullItem(")
			} else {
				b.WriteString("rasql.Item(")
			}
			b.WriteString(strconv.Quote(column.PhysicalName))
			b.WriteString(", ")
			if optionalProjection || column.Nullable {
				b.WriteString("expressions.")
				b.WriteString(field)
				b.WriteString(".NullExpr()")
			} else {
				b.WriteString("expressions.")
				b.WriteString(field)
				b.WriteString(".Expr()")
			}
			b.WriteString(", ")
			b.WriteString(compactSchemaType(object.Table, column.PhysicalName))
			b.WriteString(", ")
			b.WriteString(strconv.Quote(column.Codec))
			b.WriteString("),\n")
		}
		b.WriteString("\t}\n\treturn rasql.NewProjection(items, ")
		if optionalProjection {
			b.WriteString(compactLowerFirst(accessor) + "OptionalDecoder{}")
		} else {
			b.WriteString(compactLowerFirst(accessor) + "Decoder{}")
		}
		b.WriteString(")\n}\n\n")
	}
	writeProjection(accessor+"Projection", false)
	if optional {
		writeProjection("Optional"+accessor+"Projection", true)
	}
}

func compactPageColumns(object CompactObject) []compilerir.GoColumn {
	result := make([]compilerir.GoColumn, 0, len(object.Go.Columns))
	for _, column := range object.Go.Columns {
		if columnReadable(object.Semantic, column.Name) && !compactCustomNullable(object, column) {
			result = append(result, column)
		}
	}
	return result
}

func compactRelations(object CompactObject) []compilerir.GoRelation {
	result := make([]compilerir.GoRelation, 0, len(object.Go.Relations))
	for _, relation := range object.Go.Relations {
		if _, ok := object.Targets[relation.Target]; ok {
			result = append(result, relation)
		}
	}
	return result
}

func writeCompactKeys(b *bytes.Buffer, object CompactObject, accessor, row string, marker []string) {
	if len(marker) > 0 {
		b.WriteString("func ")
		b.WriteString(accessor)
		b.WriteString("GraphKey(source rasql.TypedRelation[")
		b.WriteString(row)
		b.WriteString("]) (rasql.GraphKey[")
		b.WriteString(row)
		b.WriteString("], error) {\n\texpressions, err := (")
		b.WriteString(accessor)
		b.WriteString("Columns{}).Bind(source)\n\tif err != nil { return rasql.GraphKey[")
		b.WriteString(row)
		b.WriteString("]{}, err }\n\treturn rasql.NewGraphKey[")
		b.WriteString(row)
		b.WriteString("](")
		writeCompactGraphParts(b, object, accessor, row, marker, "expressions")
		b.WriteString(")\n}\n\n")
	}
	for _, column := range compactPageColumns(object) {
		field := exportedCompact(column.Name)
		valueType := compactColumnValueType(object, column)
		b.WriteString("func ")
		b.WriteString(accessor)
		b.WriteString(field)
		b.WriteString("PageKey(source rasql.TypedRelation[")
		b.WriteString(row)
		b.WriteString("], direction rasql.PageDirection")
		if column.Nullable {
			b.WriteString(", nulls rasql.NullOrder")
		}
		b.WriteString(") (rasql.PageKey[")
		b.WriteString(row)
		b.WriteString("], error) {\n\texpressions, err := (")
		b.WriteString(accessor)
		b.WriteString("Columns{}).Bind(source)\n\tif err != nil { return nil, err }\n\treturn rasqlgen")
		if column.Nullable {
			b.WriteString("NullablePageKey(direction, ")
		} else {
			b.WriteString("PageKey(direction, ")
		}
		b.WriteString("expressions")
		b.WriteString(".")
		b.WriteString(field)
		if column.Nullable {
			b.WriteString(".NullExpr(), func(row ")
			b.WriteString(row)
			b.WriteString(") rasql.Nullable[")
			b.WriteString(valueType)
			b.WriteString("] { return row.")
			b.WriteString(field)
			b.WriteString(" }, nulls)")
		} else {
			b.WriteString(".Expr(), func(row ")
			b.WriteString(row)
			b.WriteString(") ")
			b.WriteString(valueType)
			b.WriteString(" { return row.")
			b.WriteString(field)
			b.WriteString(" })")
		}
		b.WriteString("\n}\n\n")
	}
}

func writeCompactGraphParts(b *bytes.Buffer, object CompactObject, accessor, row string, columns []string, expressions string) {
	for i, name := range columns {
		if i > 0 {
			b.WriteString(", ")
		}
		column, ok := goColumnByName(object.Go, name)
		if !ok {
			b.WriteString("rasql.GraphKeyPart[")
			b.WriteString(row)
			b.WriteString("]{}")
			continue
		}
		field := exportedCompact(name)
		valueType := compactColumnValueType(object, column)
		if column.Nullable {
			b.WriteString("rasql.NullKeyPart[")
		} else {
			b.WriteString("rasql.KeyPart[")
		}
		b.WriteString(row)
		b.WriteByte(',')
		b.WriteString(valueType)
		b.WriteString("](")
		b.WriteString(expressions)
		b.WriteByte('.')
		b.WriteString(field)
		if column.Nullable {
			b.WriteString(", func(row ")
			b.WriteString(row)
			b.WriteString(") rasql.Nullable[")
			b.WriteString(valueType)
			b.WriteString("] { return row.")
			b.WriteString(field)
			b.WriteString(" })")
		} else {
			b.WriteString(", func(row ")
			b.WriteString(row)
			b.WriteString(") ")
			b.WriteString(valueType)
			b.WriteString(" { return row.")
			b.WriteString(field)
			b.WriteString(" })")
		}
	}
}

func writeCompactRelations(b *bytes.Buffer, object CompactObject, accessor, row string) {
	for _, relation := range compactRelations(object) {
		target := object.Targets[relation.Target]
		targetAccessor := target.Generation.Source
		if targetAccessor == "" {
			targetAccessor = exportedCompact(target.Catalog.Name)
		}
		targetRow := target.Generation.Row
		if targetRow == "" {
			targetRow = exportedCompact(target.Catalog.Name) + "Row"
		}
		name := accessor + exportedCompact(relation.Name) + "Edge"
		b.WriteString("func ")
		b.WriteString(name)
		b.WriteString("[G, CG any](parentSource rasql.TypedRelation[")
		b.WriteString(row)
		b.WriteString("], ")
		if relation.Kind == "many_through" && relation.Through != nil {
			through := object.Targets[relation.Through.Object]
			throughRow := through.Generation.Row
			if throughRow == "" {
				throughRow = exportedCompact(through.Catalog.Name) + "Row"
			}
			b.WriteString("junctionSource rasql.TypedRelation[")
			b.WriteString(throughRow)
			b.WriteString("], ")
		}
		b.WriteString("childSource rasql.TypedRelation[")
		b.WriteString(targetRow)
		b.WriteString("], children rasql.GraphPlan[")
		b.WriteString(targetRow)
		b.WriteString(", CG], options rasql.EdgeOptions, attach func(*G, rasql.Loaded")
		if relation.Kind == "belongs_to" || relation.Kind == "has_one" {
			b.WriteString("One[")
		} else {
			b.WriteString("Many[")
		}
		b.WriteString("CG])) (rasql.GraphEdge[")
		b.WriteString(row)
		b.WriteString(", G], error) {\n")
		b.WriteString("\tparentExpressions, err := (")
		b.WriteString(accessor)
		b.WriteString("Columns{}).Bind(parentSource)\n\tif err != nil { return nil, err }\n")
		b.WriteString("\tchildExpressions, err := (")
		b.WriteString(targetAccessor)
		b.WriteString("Columns{}).Bind(childSource)\n\tif err != nil { return nil, err }\n")
		b.WriteString("\tparent, err := rasql.NewGraphKey[")
		b.WriteString(row)
		b.WriteString("](")
		writeCompactGraphParts(b, object, accessor, row, relation.From, "parentExpressions")
		b.WriteString(")\n\tif err != nil { return nil, err }\n")
		if relation.Kind == "many_through" && relation.Through != nil {
			through, ok := object.Targets[relation.Through.Object]
			if !ok {
				continue
			}
			throughAccessor := through.Generation.Source
			if throughAccessor == "" {
				throughAccessor = exportedCompact(through.Catalog.Name)
			}
			throughRow := through.Generation.Row
			if throughRow == "" {
				throughRow = exportedCompact(through.Catalog.Name) + "Row"
			}
			b.WriteString("\tjunctionExpressions, err := (")
			b.WriteString(throughAccessor)
			b.WriteString("Columns{}).Bind(junctionSource)\n\tif err != nil { return nil, err }\n")
			b.WriteString("\tjunctionParent, err := rasql.NewGraphKey[")
			b.WriteString(throughRow)
			b.WriteString("](")
			writeCompactGraphParts(b, CompactObject{Go: through.Go, Mappings: object.Mappings}, throughAccessor, throughRow, relation.Through.SourceFrom, "junctionExpressions")
			b.WriteString(")\n\tif err != nil { return nil, err }\n")
			b.WriteString("\tjunctionChild, err := rasql.NewGraphKey[")
			b.WriteString(throughRow)
			b.WriteString("](")
			writeCompactGraphParts(b, CompactObject{Go: through.Go, Mappings: object.Mappings}, throughAccessor, throughRow, relation.Through.TargetFrom, "junctionExpressions")
			b.WriteString(")\n\tif err != nil { return nil, err }\n")
			b.WriteString("\tchild, err := rasql.NewGraphKey[")
			b.WriteString(targetRow)
			b.WriteString("](")
			writeCompactGraphParts(b, CompactObject{Catalog: target.Catalog, Go: target.Go, Mappings: object.Mappings}, targetAccessor, targetRow, relation.To, "childExpressions")
			b.WriteString(")\n\tif err != nil { return nil, err }\n")
			b.WriteString("\treturn rasql.ManyThrough(\"")
			b.WriteString(relation.Name)
			b.WriteString("\", parent, junctionParent, junctionChild, child, junctionSource.Source(), children, options, attach)\n}\n\n")
			continue
		}
		b.WriteString("\tchild, err := rasql.NewGraphKey[")
		b.WriteString(targetRow)
		b.WriteString("](")
		writeCompactGraphParts(b, CompactObject{Catalog: target.Catalog, Go: target.Go, Mappings: object.Mappings}, targetAccessor, targetRow, relation.To, "childExpressions")
		b.WriteString(")\n\tif err != nil { return nil, err }\n\treturn rasql.")
		if relation.Kind == "belongs_to" || relation.Kind == "has_one" {
			b.WriteString("HasOne")
		} else {
			b.WriteString("HasMany")
		}
		b.WriteString("(\"")
		b.WriteString(relation.Name)
		b.WriteString("\", parent, child, children, options, attach)\n}\n\n")
	}
}

func writeCompactMutations(b *bytes.Buffer, object CompactObject, accessor, row string) {
	create := object.Generation.Create
	patch := object.Generation.Patch
	if create == "" {
		create = accessor + "Create"
	}
	if patch == "" {
		patch = accessor + "Patch"
	}
	mutationColumns := compactLowerFirst(accessor) + "MutationColumns"
	b.WriteString("var ")
	b.WriteString(mutationColumns)
	b.WriteString(" = func() ")
	b.WriteString(accessor)
	b.WriteString("Expressions { source, err := ")
	b.WriteString(accessor)
	b.WriteString("().Source(\"\"); if err != nil { panic(err) }; value, err := (")
	b.WriteString(accessor)
	b.WriteString("Columns{}).Bind(source); if err != nil { panic(err) }; return value }()\n\n")
	if create != "" {
		writeMutationType(b, object, accessor, row, create, false, mutationColumns)
	}
	if patch != "" {
		writeMutationType(b, object, accessor, row, patch, true, mutationColumns)
	}
}

func writeMutationType(b *bytes.Buffer, object CompactObject, accessor, row, name string, patch bool, mutationColumns string) {
	b.WriteString("type ")
	b.WriteString(name)
	b.WriteString(" struct { fields []rasql.MutationField[")
	b.WriteString(row)
	b.WriteString("] }")
	b.WriteString("\nfunc New")
	b.WriteString(name)
	b.WriteString("() ")
	b.WriteString(name)
	b.WriteString(" { return ")
	b.WriteString(name)
	b.WriteString("{} }\n")
	shape := object.Go.Create
	if patch {
		shape = object.Go.Patch
	}
	if shape != nil {
		for _, field := range shape.Fields {
			column, ok := goColumnByName(object.Go, field.Name)
			if !ok {
				continue
			}
			method := exportedCompact(field.Name)
			b.WriteString("func (v ")
			b.WriteString(name)
			b.WriteString(") ")
			b.WriteString(method)
			b.WriteString("(value ")
			b.WriteString(compactColumnValueType(object, column))
			b.WriteString(") ")
			b.WriteString(name)
			b.WriteString(" { v.fields = rasqlgenAppendMutationField(v.fields, ")
			if column.Nullable {
				b.WriteString("rasql.SetNullableField(")
			} else {
				b.WriteString("rasql.SetField(")
			}
			b.WriteString(mutationColumns)
			b.WriteByte('.')
			b.WriteString(method)
			b.WriteString(", value)); return v }\n")
			if column.Nullable {
				b.WriteString("func (v ")
				b.WriteString(name)
				b.WriteString(") Clear")
				b.WriteString(method)
				b.WriteString("() ")
				b.WriteString(name)
				b.WriteString(" { v.fields = rasqlgenAppendMutationField(v.fields, rasql.ClearField(")
				b.WriteString(mutationColumns)
				b.WriteByte('.')
				b.WriteString(method)
				b.WriteString(")); return v }\n")
			}
			if columnHasDefault(object.Table, field.Name) {
				b.WriteString("func (v ")
				b.WriteString(name)
				b.WriteString(") Default")
				b.WriteString(method)
				b.WriteString("() ")
				b.WriteString(name)
				b.WriteString(" { v.fields = rasqlgenAppendMutationField(v.fields, ")
				if column.Nullable {
					b.WriteString("rasql.DefaultNullableField(")
				} else {
					b.WriteString("rasql.DefaultField(")
				}
				b.WriteString(mutationColumns)
				b.WriteByte('.')
				b.WriteString(method)
				b.WriteString(")); return v }\n")
			}
		}
	}
	if patch {
		b.WriteString("func (v ")
		b.WriteString(name)
		b.WriteString(") Where(value rasql.Predicate) (rasql.PatchPlan[")
		b.WriteString(row)
		b.WriteString("], error) { return rasql.NewPatchPlan(")
		b.WriteString(accessor)
		b.WriteString("().Table, value, v.fields...) }\n\n")
		return
	}
	b.WriteString("func (v ")
	b.WriteString(name)
	b.WriteString(") Plan() (rasql.CreatePlan[")
	b.WriteString(row)
	b.WriteString("], error) {\n")
	b.WriteString("\treturn rasql.NewCreatePlan(")
	b.WriteString(accessor)
	b.WriteString("().Table, v.fields...)")
	b.WriteString("\n}\n\n")
}

func compactMarker(table schema.TableDef) []string {
	key := append([]string(nil), table.PrimaryKey...)
	if len(key) == 0 {
		for _, unique := range table.UniqueConstraints {
			if len(unique.Columns) == 0 {
				continue
			}
			valid := true
			for _, name := range unique.Columns {
				column, ok := table.Column(name)
				if !ok || column.Nullable {
					valid = false
					break
				}
			}
			if valid {
				key = append(key, unique.Columns...)
				break
			}
		}
	}
	for _, name := range key {
		column, ok := table.Column(name)
		if !ok || column.Nullable {
			return nil
		}
	}
	return key
}

func columnReadable(object compilerir.SemanticObject, name string) bool {
	for _, c := range object.Columns {
		if c.Name == name {
			return c.Readable
		}
	}
	return false
}
func goColumnByName(object compilerir.GoObject, name string) (compilerir.GoColumn, bool) {
	for _, c := range object.Columns {
		if c.Name == name {
			return c, true
		}
	}
	return compilerir.GoColumn{}, false
}
func columnHasDefault(table schema.TableDef, name string) bool {
	c, ok := table.Column(name)
	return ok && c.Default != ""
}
func compactLowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
func exportedCompact(value string) string {
	var b strings.Builder
	upper := true
	for _, r := range value {
		if r == '_' || r == '-' || r == ' ' || r == '.' {
			upper = true
			continue
		}
		if upper {
			b.WriteString(strings.ToUpper(string(r)))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "Value"
	}
	result := b.String()
	for _, pair := range [][2]string{{"Id", "ID"}, {"Url", "URL"}, {"Uri", "URI"}, {"Api", "API"}} {
		if strings.HasSuffix(result, pair[0]) {
			result = strings.TrimSuffix(result, pair[0]) + pair[1]
		}
	}
	return result
}
func compactBaseType(value string) string {
	if strings.HasPrefix(value, "rasql.Nullable[") {
		return strings.TrimSuffix(strings.TrimPrefix(value, "rasql.Nullable["), "]")
	}
	return value
}
func compactColumnValueType(object CompactObject, column compilerir.GoColumn) string {
	for _, mapping := range object.Mappings {
		if mapping.Name == column.Scalar && mapping.GoType != "" {
			return mapping.GoType
		}
	}
	return compactBaseType(column.GoType)
}

func compactCustomNullable(object CompactObject, column compilerir.GoColumn) bool {
	if !column.Nullable {
		return false
	}
	for _, mapping := range object.Mappings {
		if mapping.Name == column.Scalar {
			return mapping.NullableGoType != "" && !strings.HasPrefix(mapping.NullableGoType, "rasql.Nullable[")
		}
	}
	return false
}

func compactNullableDirect(object CompactObject, column compilerir.GoColumn) bool {
	if compactCustomNullable(object, column) {
		return true
	}
	return column.Nullable && strings.HasPrefix(column.GoType, "rasql.Nullable[")
}

func compactSchemaType(table schema.TableDef, name string) string {
	var b bytes.Buffer
	column, _ := table.Column(name)
	writeColumnTypeLiteral(&b, column.Type)
	return b.String()
}
