package generate_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/lestrrat-go/rasql/generate"
	"github.com/stretchr/testify/require"
)

func TestRenderCompactPlansCanonicalTableSurface(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	root := t.TempDir()
	store.Root = root
	store.Dir = "generated"
	plan, err := store.Plan()
	require.NoError(t, err)
	require.Len(t, plan.Files(), 3)
	for _, file := range plan.Files() {
		require.True(t, len(file.Source) > 0)
		require.Equal(t, "// Code generated by rasqlgen; DO NOT EDIT.", string(file.Source[:len("// Code generated by rasqlgen; DO NOT EDIT.")]))
	}
	require.NoError(t, os.MkdirAll(filepath.Join(root, "generated"), 0o755))
	require.NoError(t, plan.Commit())
	module := filepath.Join(root, "go.mod")
	require.NoError(t, os.WriteFile(module, []byte("module example.com/compact\n\ngo 1.23\n\nrequire github.com/lestrrat-go/rasql v0.0.0\nreplace github.com/lestrrat-go/rasql => "+repoRoot(t)+"\n"), 0o600))
	command := exec.Command("go", "test", "-mod=mod", "./generated")
	command.Dir = root
	command.Env = append(os.Environ(), "GOCACHE="+filepath.Join(root, "cache"))
	output, err := command.CombinedOutput()
	require.NoError(t, err, "%s", output)
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("..")
	require.NoError(t, err)
	return root
}
