package generate_test

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lestrrat-go/rasql/generate"
	"github.com/lestrrat-go/rasql/internal/compilerir"
	"github.com/lestrrat-go/rasql/schema"
)

func TestCompilerInputFromTableDefsPreservesLegacySidecar(t *testing.T) {
	relation := schema.RelationshipDef{Name: "parent", Kind: schema.RelationshipManyToMany, Columns: []string{"id"}, ReferencedTable: "users", ReferencedColumns: []string{"id"}, Through: &schema.RelationshipThrough{Table: schema.ObjectName{Name: "links"}, SourceColumns: []string{"id"}, TargetColumns: []string{"id"}}}
	table := schema.TableDef{Schema: "public", Name: "users", Operations: schema.OperationRead, RowName: "PersonRow", Columns: []schema.ColumnDef{{Name: "id", Type: schema.IntegerType{}, GoBinding: &schema.GoBinding{Type: "int32", Imports: []schema.GoImport{{Path: "example.com/id"}}}}}, Relationships: []schema.RelationshipDef{relation}}
	input, diagnostics := generate.CompilerInputFromTableDefs(compilerir.EngineIdentity{Dialect: "sqlite"}, []schema.TableDef{table})
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	if input.Legacy == nil || len(input.Legacy.Objects) != 1 || input.Legacy.Objects[0].RowName != "PersonRow" {
		t.Fatalf("sidecar missing: %#v", input.Legacy)
	}
	input.Legacy.Objects[0].Relationships[0].Through.SourceColumns[0] = "changed"
	if relation.Through.SourceColumns[0] != "id" {
		t.Fatal("sidecar relationship aliases source")
	}
	input.Legacy.Objects[0].Columns[0].GoBinding.Imports[0].Path = "changed"
	if table.Columns[0].GoBinding.Imports[0].Path != "example.com/id" {
		t.Fatal("sidecar binding aliases source")
	}
}

func TestStorePlanRejectsInvalidCompilerInput(t *testing.T) {
	input := &generate.CompilerInput{Catalog: compilerir.PhysicalCatalog{Engine: compilerir.EngineIdentity{Dialect: "sqlite"}, Objects: []compilerir.PhysicalObject{{Kind: "table", Name: "events"}}}}
	store := generate.Store{Package: "store", Root: ".", Dir: "generated", CompilerInput: input}
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "compiler input") {
		t.Fatalf("unexpected compiler input result: %v", err)
	}
}

func TestPublicCompilerInputMatchesLegacyPlan(t *testing.T) {
	tables := []schema.TableDef{{Name: "users", Operations: schema.OperationRead, RowName: "PersonRow", Columns: []schema.ColumnDef{{Name: "id", Type: schema.IntegerType{}, GoBinding: &schema.GoBinding{Type: "int32"}}}}}
	input, diagnostics := generate.CompilerInputFromTableDefs(compilerir.EngineIdentity{Dialect: "sqlite"}, tables)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	store := generate.Store{Package: "store", Dir: filepath.Join(t.TempDir(), "store"), Tables: tables}
	legacy, err := store.Plan()
	if err != nil {
		t.Fatal(err)
	}
	store.Tables = nil
	store.CompilerInput = &input
	modern, err := store.Plan()
	if err != nil {
		t.Fatal(err)
	}
	if len(legacy.Files()) != len(modern.Files()) {
		t.Fatalf("file count changed: %d != %d", len(legacy.Files()), len(modern.Files()))
	}
	for i := range legacy.Files() {
		if !bytes.Equal(legacy.Files()[i].Source, modern.Files()[i].Source) {
			t.Fatalf("generated bytes changed for %s", legacy.Files()[i].Path)
		}
	}
	changed := input.Clone()
	changed.Legacy.Objects = nil
	store.CompilerInput = &changed
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[0].id") {
		t.Fatalf("missing object path was not reported: %v", err)
	}
	changed = input.Clone()
	changed.Legacy.Objects[0].Columns = nil
	store.CompilerInput = &changed
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[0].columns[0].name") {
		t.Fatalf("missing column path was not reported: %v", err)
	}
	changed = input.Clone()
	changed.Legacy.Objects = append(changed.Legacy.Objects, changed.Legacy.Objects[0])
	store.CompilerInput = &changed
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[1].id") {
		t.Fatalf("duplicate object path was not reported: %v", err)
	}
	changed = input.Clone()
	changed.Legacy.Objects[0].ID = "stale-object"
	store.CompilerInput = &changed
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[0].id unknown") {
		t.Fatalf("unknown object path was not reported: %v", err)
	}
	changed = input.Clone()
	changed.Legacy.Objects[0].Columns[0].Name = "stale-column"
	store.CompilerInput = &changed
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[0].columns[0].name unknown") {
		t.Fatalf("unknown column path was not reported: %v", err)
	}
	changed = input.Clone()
	changed.Legacy.Objects[0].Columns = append(changed.Legacy.Objects[0].Columns, changed.Legacy.Objects[0].Columns[0])
	store.CompilerInput = &changed
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[0].columns[1].name duplicate") {
		t.Fatalf("duplicate column path was not reported: %v", err)
	}
	input.Legacy = nil
	store.CompilerInput = &input
	if _, err := store.Plan(); err != nil {
		t.Fatalf("nil sidecar was rejected: %v", err)
	}
}

func TestCompilerInputRejectsSidecarKindMismatch(t *testing.T) {
	input, diagnostics := generate.CompilerInputFromTableDefs(compilerir.EngineIdentity{Dialect: "sqlite"}, []schema.TableDef{{Name: "users", Columns: []schema.ColumnDef{{Name: "id", Type: schema.IntegerType{}}}}})
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	input.Legacy.Objects[0].Kind = schema.ObjectView
	store := generate.Store{Package: "store", Dir: filepath.Join(t.TempDir(), "store"), CompilerInput: &input}
	if _, err := store.Plan(); err == nil || !strings.Contains(err.Error(), "legacy.objects[0].kind") {
		t.Fatalf("sidecar kind mismatch was accepted: %v", err)
	}
}
