package generate_test

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/lestrrat-go/rasql/generate"
	"github.com/lestrrat-go/rasql/internal/compilerir"
	"github.com/lestrrat-go/rasql/internal/querygen"
	"github.com/stretchr/testify/require"
)

func TestRenderCompactPlansCanonicalTableSurface(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	root := t.TempDir()
	store.Root = root
	store.Dir = "generated"
	plan, err := store.Plan()
	require.NoError(t, err)
	legacyInput := plainEmitterFixture(t)
	legacyInput.Generation.Emitter = "legacy"
	legacyStore, err := generate.LegacyStore(legacyInput)
	require.NoError(t, err)
	legacyStore.Root = root
	legacyStore.Dir = "legacy"
	legacyPlan, err := legacyStore.Plan()
	require.NoError(t, err)
	require.Len(t, plan.Files(), 3)
	for _, file := range plan.Files() {
		require.True(t, len(file.Source) > 0)
		require.Equal(t, "// Code generated by rasqlgen; DO NOT EDIT.", string(file.Source[:len("// Code generated by rasqlgen; DO NOT EDIT.")]))
	}
	require.NoError(t, os.MkdirAll(filepath.Join(root, "generated"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "legacy"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "compactcmd"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "legacycmd"), 0o755))
	require.NoError(t, plan.Commit())
	require.NoError(t, legacyPlan.Commit())
	module := filepath.Join(root, "go.mod")
	require.NoError(t, os.WriteFile(module, []byte("module example.com/compact\n\ngo 1.26\n\nrequire github.com/lestrrat-go/rasql v0.0.0\nrequire modernc.org/sqlite v1.55.0\nreplace github.com/lestrrat-go/rasql => "+repoRoot(t)+"\n"), 0o600))
	compactConsumer := `package store_test

import (
	"context"
	"database/sql"
	"fmt"
	"testing"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/dialect"
	generated "example.com/compact/generated"
	_ "modernc.org/sqlite"
)

func collect[R any](ctx context.Context, executor rasql.Executor, query rasql.Query[R]) error {
	rows, err := rasql.Rows(ctx, executor, query)
	if err != nil { return err }
	count := 0
	for _, err := range rows {
		if err != nil { return err }
		count++
	}
	if count != 1 { return fmt.Errorf("rows = %d", count) }
	return nil
}

func TestCompactConsumerRoundTrip(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil { t.Fatal(err) }
	defer db.Close()
	if _, err := db.ExecContext(t.Context(), "CREATE TABLE users (id INTEGER PRIMARY KEY)"); err != nil { t.Fatal(err) }
	rdb, err := rasql.New(db, dialect.SQLite())
	if err != nil { t.Fatal(err) }
	plan, err := generated.NewUsersCreate().ID(7).Plan()
	if err != nil { t.Fatal(err) }
	profile, err := rasql.DiscoverEngineProfile(t.Context(), rdb, "sqlite-3.35")
	if err != nil { t.Fatal(err) }
	executor, err := rasql.AsExecutor(rdb, profile)
	if err != nil { t.Fatal(err) }
	if _, err := rasql.ExecMutation(t.Context(), executor, plan); err != nil { t.Fatal(err) }
	rows, err := rasql.SelectFrom(generated.Users()).All(t.Context(), rdb)
	if err != nil { t.Fatal(err) }
	if len(rows) != 1 || rows[0].ID != 7 { t.Fatalf("rows = %#v", rows) }
}

func BenchmarkCompactScan(b *testing.B) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil { b.Fatal(err) }
	defer db.Close()
	if _, err := db.ExecContext(b.Context(), "CREATE TABLE users (id INTEGER PRIMARY KEY)"); err != nil { b.Fatal(err) }
	if _, err := db.ExecContext(b.Context(), "INSERT INTO users (id) VALUES (7)"); err != nil { b.Fatal(err) }
	rdb, err := rasql.New(db, dialect.SQLite())
	if err != nil { b.Fatal(err) }
	profile, err := rasql.DiscoverEngineProfile(b.Context(), rdb, "sqlite-3.35")
	if err != nil { b.Fatal(err) }
	executor, err := rasql.AsExecutor(rdb, profile)
	if err != nil { b.Fatal(err) }
	source, err := generated.Users().Source("")
	if err != nil { b.Fatal(err) }
	expressions, err := (generated.UsersColumns{}).Bind(source)
	if err != nil { b.Fatal(err) }
	projection, err := generated.UsersProjection(expressions)
	if err != nil { b.Fatal(err) }
	query := rasql.Select(source.Source(), projection)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := collect(b.Context(), executor, query); err != nil { b.Fatal(err) }
	}
}
`
	legacyConsumer := `package store_test

import (
	"context"
	"database/sql"
	"fmt"
	"testing"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/dialect"
	"github.com/lestrrat-go/rasql/schema"
	legacy "example.com/compact/legacy"
	_ "modernc.org/sqlite"
)

type legacyUsersDecoder struct{ schema rasql.ResultSchema }
func (d legacyUsersDecoder) ResultSchema() rasql.ResultSchema { return d.schema }
func (legacyUsersDecoder) Presence() []rasql.Presence { return nil }
func (legacyUsersDecoder) DecodeRow(src rasql.ScanSource, row *legacy.UsersRow) error { return row.ScanRow(src) }

func collect[R any](ctx context.Context, executor rasql.Executor, query rasql.Query[R]) error {
	rows, err := rasql.Rows(ctx, executor, query)
	if err != nil { return err }
	count := 0
	for _, err := range rows {
		if err != nil { return err }
		count++
	}
	if count != 1 { return fmt.Errorf("rows = %d", count) }
	return nil
}

func BenchmarkLegacyScan(b *testing.B) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil { b.Fatal(err) }
	defer db.Close()
	if _, err := db.ExecContext(b.Context(), "CREATE TABLE users (id INTEGER PRIMARY KEY)"); err != nil { b.Fatal(err) }
	if _, err := db.ExecContext(b.Context(), "INSERT INTO users (id) VALUES (7)"); err != nil { b.Fatal(err) }
	rdb, err := rasql.New(db, dialect.SQLite())
	if err != nil { b.Fatal(err) }
	profile, err := rasql.DiscoverEngineProfile(b.Context(), rdb, "sqlite-3.35")
	if err != nil { b.Fatal(err) }
	executor, err := rasql.AsExecutor(rdb, profile)
	if err != nil { b.Fatal(err) }
	source, err := rasql.SourceOf(legacy.Users(), "")
	if err != nil { b.Fatal(err) }
	id, err := rasql.BindColumn[legacy.UsersRow, int64](source, "id", "")
	if err != nil { b.Fatal(err) }
	legacySchema, err := rasql.NewResultSchema(rasql.ResultColumn{Name: "id", Type: schema.IntegerType{}})
	if err != nil { b.Fatal(err) }
	legacyProjection, err := rasql.NewProjection([]rasql.ProjectionItem{rasql.Item("id", id.Expr(), schema.IntegerType{}, "")}, legacyUsersDecoder{schema: legacySchema})
	if err != nil { b.Fatal(err) }
	query := rasql.Select(source.Source(), legacyProjection)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := collect(b.Context(), executor, query); err != nil { b.Fatal(err) }
	}
}
`
	require.NoError(t, os.WriteFile(filepath.Join(root, "generated", "consumer_test.go"), []byte(compactConsumer), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(root, "legacy", "consumer_test.go"), []byte(legacyConsumer), 0o600))
	compactProgram := `package main

import (
	"context"

	"github.com/lestrrat-go/rasql"
	generated "example.com/compact/generated"
)

func main() {
	source, err := generated.Users().Source("")
	if err != nil { panic(err) }
	expressions, err := (generated.UsersColumns{}).Bind(source)
	if err != nil { panic(err) }
	projection, err := generated.UsersProjection(expressions)
	if err != nil { panic(err) }
	query := rasql.Select(source.Source(), projection)
	rows, err := rasql.Rows(context.Background(), nil, query)
	if err != nil { return }
	_ = rows
}
`
	legacyProgram := `package main

import (
	"context"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
	legacy "example.com/compact/legacy"
)

type legacyUsersDecoder struct{ schema rasql.ResultSchema }
func (d legacyUsersDecoder) ResultSchema() rasql.ResultSchema { return d.schema }
func (legacyUsersDecoder) Presence() []rasql.Presence { return nil }
func (legacyUsersDecoder) DecodeRow(src rasql.ScanSource, row *legacy.UsersRow) error { return row.ScanRow(src) }

func main() {
	source, err := rasql.SourceOf(legacy.Users(), "")
	if err != nil { panic(err) }
	id, err := rasql.BindColumn[legacy.UsersRow, int64](source, "id", "")
	if err != nil { panic(err) }
	resultSchema, err := rasql.NewResultSchema(rasql.ResultColumn{Name: "id", Type: schema.IntegerType{}})
	if err != nil { panic(err) }
	projection, err := rasql.NewProjection([]rasql.ProjectionItem{rasql.Item("id", id.Expr(), schema.IntegerType{}, "")}, legacyUsersDecoder{schema: resultSchema})
	if err != nil { panic(err) }
	query := rasql.Select(source.Source(), projection)
	rows, err := rasql.Rows(context.Background(), nil, query)
	if err != nil { return }
	_ = rows
}
`
	require.NoError(t, os.WriteFile(filepath.Join(root, "compactcmd", "main.go"), []byte(compactProgram), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(root, "legacycmd", "main.go"), []byte(legacyProgram), 0o600))
	command := exec.Command("go", "test", "-mod=mod", "./generated", "./legacy")
	command.Dir = root
	command.Env = append(os.Environ(), "GOCACHE="+filepath.Join(root, "cache"))
	output, err := command.CombinedOutput()
	require.NoError(t, err, "%s", output)
	compactBuilds, legacyBuilds := pairedBuildSamples(t, root, command.Env)
	t.Logf("compact build samples=%s median=%s", formatDurations(compactBuilds), medianDuration(compactBuilds))
	t.Logf("legacy build samples=%s median=%s", formatDurations(legacyBuilds), medianDuration(legacyBuilds))
	t.Logf("build median metrics compact=%s legacy=%s", formatBuildMetric(medianBuildMetrics(compactBuilds)), formatBuildMetric(medianBuildMetrics(legacyBuilds)))
	wallRatio := buildRatio(compactBuilds, legacyBuilds, func(sample buildSample) float64 { return sample.wall.Seconds() })
	cpuRatio := buildRatio(compactBuilds, legacyBuilds, func(sample buildSample) float64 { return sample.cpu.Seconds() })
	rssRatio := buildRatio(compactBuilds, legacyBuilds, func(sample buildSample) float64 { return float64(sample.rssKB) })
	binaryRatio := buildRatio(compactBuilds, legacyBuilds, func(sample buildSample) float64 { return float64(sample.binary) })
	t.Logf("build median ratios compact/legacy wall=%.2fx cpu=%.2fx rss=%.2fx binary=%.2fx", wallRatio, cpuRatio, rssRatio, binaryRatio)
	for name, ratio := range map[string]float64{"wall": wallRatio, "cpu": cpuRatio, "rss": rssRatio, "binary": binaryRatio} {
		require.LessOrEqual(t, ratio, 1.10, "%s median compact/legacy ratio", name)
	}
	compactOutput := benchmarkPackage(t, root, command.Env, "./generated", "BenchmarkCompactScan")
	legacyOutput := benchmarkPackage(t, root, command.Env, "./legacy", "BenchmarkLegacyScan")
	t.Logf("compact scan measurement: %s", compactOutput)
	t.Logf("legacy scan measurement: %s", legacyOutput)
	compactAllocs, ok := benchmarkAllocs(string(compactOutput), "BenchmarkCompactScan")
	require.True(t, ok)
	legacyAllocs, ok := benchmarkAllocs(string(legacyOutput), "BenchmarkLegacyScan")
	require.True(t, ok)
	t.Logf("scan allocations compact=%d legacy=%d", compactAllocs, legacyAllocs)
	require.LessOrEqual(t, compactAllocs, legacyAllocs)
	manifest := store.APIManifest()
	require.NotEmpty(t, manifest)
	var removedTables bool
	for _, mapping := range manifest {
		if mapping.Legacy == "Tables" && mapping.Status == "removed" {
			removedTables = true
		}
	}
	require.True(t, removedTables)
}

func benchmarkAllocs(output, name string) (int, bool) {
	for _, line := range strings.Split(output, "\n") {
		if !strings.HasPrefix(strings.TrimSpace(line), name+"-") {
			continue
		}
		fields := strings.Fields(line)
		for index, field := range fields {
			if field != "allocs/op" || index == 0 {
				continue
			}
			value, err := strconv.Atoi(fields[index-1])
			if err == nil {
				return value, true
			}
		}
	}
	return 0, false
}

func benchmarkPackage(t *testing.T, root string, env []string, packagePath, benchmarkName string) []byte {
	t.Helper()
	command := exec.Command("go", "test", "-mod=mod", "-run", "^$", "-bench", "^"+benchmarkName+"$", "-benchmem", packagePath)
	command.Dir = root
	command.Env = env
	output, err := command.CombinedOutput()
	require.NoError(t, err, "%s", output)
	return output
}

type buildSample struct {
	wall   time.Duration
	user   time.Duration
	system time.Duration
	cpu    time.Duration
	rssKB  int64
	binary int64
}

func pairedBuildSamples(t *testing.T, root string, env []string) ([]buildSample, []buildSample) {
	t.Helper()
	const samples = 7
	compact := make([]buildSample, 0, samples)
	legacy := make([]buildSample, 0, samples)
	for index := 0; index < samples; index++ {
		if index%2 == 0 {
			compact = append(compact, buildSampleAt(t, root, env, "compact", "./compactcmd", index))
			legacy = append(legacy, buildSampleAt(t, root, env, "legacy", "./legacycmd", index))
		} else {
			legacy = append(legacy, buildSampleAt(t, root, env, "legacy", "./legacycmd", index))
			compact = append(compact, buildSampleAt(t, root, env, "compact", "./compactcmd", index))
		}
	}
	return compact, legacy
}

func buildSampleAt(t *testing.T, root string, env []string, label, packagePath string, index int) buildSample {
	t.Helper()
	output := filepath.Join(root, fmt.Sprintf("%s-%d.test", label, index))
	stats := filepath.Join(root, fmt.Sprintf("%s-%d.time", label, index))
	command := exec.Command("/usr/bin/time", "-f", "%e %U %S %M", "-o", stats, "go", "build", "-buildvcs=false", "-trimpath", "-o", output, packagePath)
	command.Dir = root
	command.Env = env
	buildOutput, err := command.CombinedOutput()
	require.NoError(t, err, "%s", buildOutput)
	measurement, err := os.ReadFile(stats)
	require.NoError(t, err)
	fields := strings.Fields(string(measurement))
	require.Len(t, fields, 4)
	wallSeconds, err := strconv.ParseFloat(fields[0], 64)
	require.NoError(t, err)
	userSeconds, err := strconv.ParseFloat(fields[1], 64)
	require.NoError(t, err)
	systemSeconds, err := strconv.ParseFloat(fields[2], 64)
	require.NoError(t, err)
	rssKB, err := strconv.ParseInt(fields[3], 10, 64)
	require.NoError(t, err)
	binary, err := os.Stat(output)
	require.NoError(t, err)
	user := time.Duration(userSeconds * float64(time.Second))
	system := time.Duration(systemSeconds * float64(time.Second))
	sample := buildSample{wall: time.Duration(wallSeconds * float64(time.Second)), user: user, system: system, cpu: user + system, rssKB: rssKB, binary: binary.Size()}
	t.Logf("%s build sample=%d wall=%s user=%s system=%s cpu=%s rss=%dKB binary=%d bytes", label, index+1, sample.wall.Round(time.Millisecond), sample.user.Round(time.Millisecond), sample.system.Round(time.Millisecond), sample.cpu.Round(time.Millisecond), sample.rssKB, sample.binary)
	require.NoError(t, os.Remove(output))
	require.NoError(t, os.Remove(stats))
	return sample
}

func medianMetric(values []buildSample, metric func(buildSample) float64) float64 {
	ordered := make([]float64, len(values))
	for index, value := range values {
		ordered[index] = metric(value)
	}
	sort.Float64s(ordered)
	return ordered[len(ordered)/2]
}

func medianBuildMetrics(values []buildSample) buildSample {
	return buildSample{
		wall:   time.Duration(medianMetric(values, func(value buildSample) float64 { return float64(value.wall) })),
		user:   time.Duration(medianMetric(values, func(value buildSample) float64 { return float64(value.user) })),
		system: time.Duration(medianMetric(values, func(value buildSample) float64 { return float64(value.system) })),
		cpu:    time.Duration(medianMetric(values, func(value buildSample) float64 { return float64(value.cpu) })),
		rssKB:  int64(medianMetric(values, func(value buildSample) float64 { return float64(value.rssKB) })),
		binary: int64(medianMetric(values, func(value buildSample) float64 { return float64(value.binary) })),
	}
}

func formatBuildMetric(sample buildSample) string {
	return fmt.Sprintf("wall=%s user=%s system=%s cpu=%s rss=%dKB binary=%d", sample.wall.Round(time.Millisecond), sample.user.Round(time.Millisecond), sample.system.Round(time.Millisecond), sample.cpu.Round(time.Millisecond), sample.rssKB, sample.binary)
}

func buildRatio(compact, legacy []buildSample, value func(buildSample) float64) float64 {
	legacyValue := medianMetric(legacy, value)
	if legacyValue == 0 {
		return 0
	}
	return medianMetric(compact, value) / legacyValue
}

func medianDuration(values []buildSample) time.Duration {
	ordered := append([]buildSample(nil), values...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].wall < ordered[j].wall })
	return ordered[len(ordered)/2].wall
}

func formatDurations(values []buildSample) string {
	result := make([]string, len(values))
	for i, value := range values {
		result[i] = value.wall.Round(time.Millisecond).String()
	}
	return strings.Join(result, ",")
}

func TestRenderCompactConcurrent(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	ctx := t.Context()
	const renders = 100
	dirs := make([]string, renders)
	for i := range dirs {
		dirs[i] = t.TempDir()
	}
	outputs := make([][]byte, renders)
	errors := make([]error, renders)
	var wait sync.WaitGroup
	wait.Add(renders)
	for i := range renders {
		go func(index int) {
			defer wait.Done()
			store, err := generate.RenderCompact(in)
			if err != nil {
				errors[index] = err
				return
			}
			store.Root = dirs[index]
			store.Dir = "generated"
			plan, err := store.PlanContext(ctx)
			if err != nil {
				errors[index] = err
				return
			}
			var bytes []byte
			for _, file := range plan.Files() {
				bytes = append(bytes, filepath.Base(file.Path)...)
				bytes = append(bytes, 0)
				bytes = append(bytes, file.Source...)
				bytes = append(bytes, 0)
			}
			outputs[index] = bytes
		}(i)
	}
	wait.Wait()
	for _, err := range errors {
		require.NoError(t, err)
	}
	for i := 1; i < len(outputs); i++ {
		require.Equal(t, outputs[0], outputs[i])
	}
}

func TestCompactPlanIncludesTypedQueries(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	store.Root, store.Dir = t.TempDir(), "generated"
	parameter := []querygen.TypedValue{{Go: compilerir.GoField{Name: "id", Type: "int64"}, Semantic: compilerir.SemanticValue{Name: "id", LogicalKind: "integer"}}}
	result := []querygen.TypedValue{{Go: compilerir.GoField{Name: "id", Type: "int64"}, Semantic: compilerir.SemanticValue{Name: "id", LogicalKind: "integer"}}}
	store.TypedQueries = []generate.TypedQuery{
		{Function: "FindUsers", Output: "find_users_gen.go", Engine: "sqlite", SQL: "SELECT id FROM users WHERE id = ?", Operation: "select", Cardinality: "many", Result: "FindUsersResult", Decoder: "FindUsersDecoder", Parameters: parameter, Results: result, ArgumentNames: []string{"id"}},
		{Function: "FindUser", Output: "find_user_gen.go", Engine: "sqlite", SQL: "SELECT id FROM users WHERE id = ?", Operation: "select", Cardinality: "one", Result: "FindUserResult", Decoder: "FindUserDecoder", Parameters: parameter, Results: result, ArgumentNames: []string{"id"}},
		{Function: "MaybeUser", Output: "maybe_user_gen.go", Engine: "sqlite", SQL: "SELECT id FROM users WHERE id = ?", Operation: "select", Cardinality: "maybe", Result: "MaybeUserResult", Decoder: "MaybeUserDecoder", Parameters: parameter, Results: result, ArgumentNames: []string{"id"}},
		{Function: "UpdateUser", Output: "update_user_gen.go", Engine: "sqlite", SQL: "UPDATE users SET id = id WHERE id = ?", Operation: "exec", Parameters: parameter, ArgumentNames: []string{"id"}},
	}
	plan, err := store.Plan()
	require.NoError(t, err)
	found := make(map[string]bool)
	for _, file := range plan.Files() {
		name := filepath.Base(file.Path)
		if name == "find_users_gen.go" || name == "find_user_gen.go" || name == "maybe_user_gen.go" || name == "update_user_gen.go" {
			found[name] = true
		}
		if name == "find_user_gen.go" {
			require.Contains(t, string(file.Source), "func FindUser")
		}
	}
	require.Len(t, found, 4)
}

func TestCompactPlanRejectsTypedQueryDeclarationCollision(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	in.Generation.Objects[0].Source = "FindBindings"
	in.Generation.Objects[0].Row = "FindBindingsRow"
	model, diagnostics := compilerir.BuildGo(in.Semantic, in.Generation)
	require.Empty(t, diagnostics)
	in.Go = model
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	store.Root, store.Dir = t.TempDir(), "generated"
	store.TypedQueries = []generate.TypedQuery{{
		Function: "Find", Output: "find_gen.go", Engine: "sqlite", SQL: "SELECT id FROM users", Operation: "select", Cardinality: "many",
		Results: []querygen.TypedValue{{Go: compilerir.GoField{Name: "id", Type: "int64"}, Semantic: compilerir.SemanticValue{Name: "id", LogicalKind: "integer"}}},
	}}
	_, err = store.Plan()
	require.Error(t, err)
	require.Contains(t, err.Error(), "FindBindings")
}

func TestCompactPlanRejectsTypedQuerySelfCollision(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	store.Root, store.Dir = t.TempDir(), "generated"
	store.TypedQueries = []generate.TypedQuery{{
		Function: "Same", Output: "same_gen.go", Engine: "sqlite", SQL: "SELECT id FROM users", Operation: "select", Cardinality: "many", Result: "Same",
		Results: []querygen.TypedValue{{Go: compilerir.GoField{Name: "id", Type: "int64"}, Semantic: compilerir.SemanticValue{Name: "id", LogicalKind: "integer"}}},
	}}
	_, err = store.Plan()
	require.Error(t, err)
	require.Contains(t, err.Error(), "collides with its function declaration")
}

func TestCompactManifestMapsRenamedMutationSymbols(t *testing.T) {
	in := plainEmitterFixture(t)
	in.Generation.Emitter = "compact"
	in.Generation.Objects[0].Source = "Account"
	in.Generation.Objects[0].Row = "AccountRecord"
	in.Generation.Objects[0].Create = "AccountInsert"
	in.Generation.Objects[0].Patch = "AccountChange"
	model, diagnostics := compilerir.BuildGo(in.Semantic, in.Generation)
	require.Empty(t, diagnostics)
	in.Go = model
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	manifest := store.APIManifest()
	find := func(legacy string) generate.APIMapping {
		for _, mapping := range manifest {
			if mapping.Legacy == legacy {
				return mapping
			}
		}
		return generate.APIMapping{}
	}
	require.Equal(t, generate.APIMapping{Legacy: "AccountCreate", Compact: "store.AccountInsert", Status: "replacement"}, find("AccountCreate"))
	require.Equal(t, generate.APIMapping{Legacy: "AccountPatch", Compact: "store.AccountChange", Status: "replacement"}, find("AccountPatch"))
}

func TestCompactRejectsGeneratedSymbolCollisions(t *testing.T) {
	cases := []struct {
		name, want string
		columns    []compilerir.PhysicalColumn
	}{
		{name: "scan row", columns: []compilerir.PhysicalColumn{{Name: "scan_row", Ordinal: 1, LogicalKind: "text"}}, want: "ScanRow"},
		{name: "create plan", columns: []compilerir.PhysicalColumn{{Name: "plan", Ordinal: 1, LogicalKind: "text"}}, want: "Plan"},
		{name: "patch where", columns: []compilerir.PhysicalColumn{{Name: "where", Ordinal: 1, LogicalKind: "text"}}, want: "Where"},
		{name: "reverse clear", columns: []compilerir.PhysicalColumn{{Name: "clear_name", Ordinal: 1, LogicalKind: "text"}, {Name: "name", Ordinal: 2, LogicalKind: "text", Nullable: true}}, want: "ClearName"},
		{name: "reverse default", columns: []compilerir.PhysicalColumn{{Name: "default_name", Ordinal: 1, LogicalKind: "text", DefaultSQL: "'default'"}, {Name: "name", Ordinal: 2, LogicalKind: "text", DefaultSQL: "'default'"}}, want: "DefaultName"},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			columns := append([]compilerir.PhysicalColumn{{Name: "id", LogicalKind: "integer"}}, test.columns...)
			catalog := compilerir.PhysicalCatalog{Engine: compilerir.EngineIdentity{Dialect: "sqlite", Version: "3"}, Objects: []compilerir.PhysicalObject{{
				ID: "users", Kind: "table", Name: "users", Columns: columns,
				Constraints: []compilerir.PhysicalConstraint{{Kind: "primary_key", Columns: []string{"id"}}},
			}}}
			semantic, diagnostics := compilerir.BuildSemantic(catalog, compilerir.MappingConfig{}, nil)
			require.Empty(t, diagnostics)
			config := compilerir.GoConfig{Package: "store", Output: "generated", Emitter: "compact", Objects: []compilerir.ObjectGoName{{ID: "users", File: "users_gen.go"}}}
			model, diagnostics := compilerir.BuildGo(semantic, config)
			require.Empty(t, diagnostics)
			input, err := generate.NewEmitterInput(catalog, semantic, model, config, compilerir.MappingConfig{})
			require.NoError(t, err)
			_, err = generate.RenderCompact(input)
			require.Error(t, err)
			require.Contains(t, err.Error(), test.want)
		})
	}
}

func TestCompactImportsOnlyUsedMappings(t *testing.T) {
	catalog := compilerir.PhysicalCatalog{Engine: compilerir.EngineIdentity{Dialect: "sqlite", Version: "3"}, Objects: []compilerir.PhysicalObject{
		{ID: "users", Kind: "table", Name: "users", Columns: []compilerir.PhysicalColumn{{Name: "id", LogicalKind: "integer"}, {Name: "status", Ordinal: 1, LogicalKind: "text", Native: &compilerir.NativeType{Dialect: "sqlite", Kind: "other", Name: "status"}}}},
		{ID: "projects", Kind: "table", Name: "projects", Columns: []compilerir.PhysicalColumn{{Name: "id", LogicalKind: "integer"}, {Name: "title", Ordinal: 1, LogicalKind: "text"}}},
	}}
	mapping := compilerir.ScalarMapping{Name: "status", Match: compilerir.NativeMatch{Name: "status"}, GoType: "domain.Status", Codec: "status", Imports: []compilerir.GoImport{{Path: "example.com/domain", Alias: "domain"}}}
	semantic, diagnostics := compilerir.BuildSemantic(catalog, compilerir.MappingConfig{Scalars: []compilerir.ScalarMapping{mapping}}, nil)
	require.Empty(t, diagnostics)
	config := compilerir.GoConfig{Package: "store", Output: "generated", Emitter: "compact", Scalars: []compilerir.ScalarMapping{mapping}, Objects: []compilerir.ObjectGoName{{ID: "users", File: "users_gen.go"}, {ID: "projects", File: "projects_gen.go"}}}
	model, diagnostics := compilerir.BuildGo(semantic, config)
	require.Empty(t, diagnostics)
	in, err := generate.NewEmitterInput(catalog, semantic, model, config, compilerir.MappingConfig{Scalars: []compilerir.ScalarMapping{mapping}})
	require.NoError(t, err)
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	store.Root, store.Dir = t.TempDir(), "generated"
	plan, err := store.Plan()
	require.NoError(t, err)
	for _, file := range plan.Files() {
		if filepath.Base(file.Path) == "projects_gen.go" {
			require.NotContains(t, string(file.Source), "example.com/domain")
		}
	}
}

func TestCompactEmitsGraphAndPageFactories(t *testing.T) {
	catalog := compilerir.PhysicalCatalog{Engine: compilerir.EngineIdentity{Dialect: "sqlite", Version: "3"}, Objects: []compilerir.PhysicalObject{
		{ID: "users", Kind: "table", Name: "users", Columns: []compilerir.PhysicalColumn{
			{Name: "id", LogicalKind: "integer"}, {Name: "deleted_at", Ordinal: 1, LogicalKind: "text", Nullable: true},
		}, Constraints: []compilerir.PhysicalConstraint{{Kind: "primary_key", Columns: []string{"id"}}}},
	}}
	semantic, diagnostics := compilerir.BuildSemantic(catalog, compilerir.MappingConfig{}, nil)
	require.Empty(t, diagnostics)
	config := compilerir.GoConfig{Package: "store", Output: "generated", Emitter: "compact", Objects: []compilerir.ObjectGoName{{ID: "users", File: "users_gen.go"}}}
	model, diagnostics := compilerir.BuildGo(semantic, config)
	require.Empty(t, diagnostics)
	in, err := generate.NewEmitterInput(catalog, semantic, model, config, compilerir.MappingConfig{})
	require.NoError(t, err)
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	store.Root, store.Dir = t.TempDir(), "generated"
	plan, err := store.Plan()
	require.NoError(t, err)
	var source string
	for _, file := range plan.Files() {
		if filepath.Base(file.Path) == "users_gen.go" {
			source = string(file.Source)
		}
	}
	require.Contains(t, source, "func UsersGraphKey(source rasql.TypedRelation[UsersRow])")
	require.Contains(t, source, "func UsersIDPageKey(source rasql.TypedRelation[UsersRow], direction rasql.PageDirection)")
	require.Contains(t, source, "func UsersDeletedAtPageKey(source rasql.TypedRelation[UsersRow], direction rasql.PageDirection, nulls rasql.NullOrder)")
	require.Contains(t, source, "rasqlgenNullablePageKey")
}

func TestCompactGeneratedGraphAliasReproducer(t *testing.T) {
	catalog := compilerir.PhysicalCatalog{Engine: compilerir.EngineIdentity{Dialect: "sqlite", Version: "3"}, Objects: []compilerir.PhysicalObject{
		{ID: "users", Kind: "table", Name: "users", Columns: []compilerir.PhysicalColumn{{Name: "id", LogicalKind: "integer"}}, Constraints: []compilerir.PhysicalConstraint{{Kind: "primary_key", Columns: []string{"id"}}}},
		{ID: "projects", Kind: "table", Name: "projects", Columns: []compilerir.PhysicalColumn{{Name: "id", LogicalKind: "integer"}, {Name: "owner_id", Ordinal: 1, LogicalKind: "integer"}}, Constraints: []compilerir.PhysicalConstraint{{Kind: "primary_key", Columns: []string{"id"}}, {Kind: "foreign_key", Name: "projects_owner_fk", Columns: []string{"owner_id"}, Reference: &compilerir.ForeignReference{Object: "users", Columns: []string{"id"}}}}},
	}}
	semantic, diagnostics := compilerir.BuildSemantic(catalog, compilerir.MappingConfig{}, nil)
	require.Empty(t, diagnostics)
	config := compilerir.GoConfig{Package: "store", Output: "generated", Emitter: "compact", Objects: []compilerir.ObjectGoName{{ID: "users", File: "users_gen.go"}, {ID: "projects", File: "projects_gen.go"}}}
	model, diagnostics := compilerir.BuildGo(semantic, config)
	require.Empty(t, diagnostics)
	in, err := generate.NewEmitterInput(catalog, semantic, model, config, compilerir.MappingConfig{})
	require.NoError(t, err)
	store, err := generate.RenderCompact(in)
	require.NoError(t, err)
	root := t.TempDir()
	store.Root, store.Dir = root, "generated"
	plan, err := store.Plan()
	require.NoError(t, err)
	require.NoError(t, os.MkdirAll(filepath.Join(root, "generated"), 0o755))
	require.NoError(t, plan.Commit())
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/graph\n\ngo 1.26\n\nrequire github.com/lestrrat-go/rasql v0.0.0\nrequire modernc.org/sqlite v1.55.0\nreplace github.com/lestrrat-go/rasql => "+repoRoot(t)+"\n"), 0o600))
	consumer := `package store_test

import (
	"strings"
	"testing"

	"github.com/lestrrat-go/rasql"
	generated "example.com/graph/generated"
)

type projectGraph struct { Owner rasql.LoadedOne[userGraph] }
type userGraph struct { ID int64 }

func TestGeneratedEdgeUsesExactAliasedStage(t *testing.T) {
	parentSource, err := generated.Projects().Source("p")
	if err != nil { t.Fatal(err) }
	parentExpressions, err := (generated.ProjectsColumns{}).Bind(parentSource)
	if err != nil { t.Fatal(err) }
	parentProjection, err := generated.ProjectsProjection(parentExpressions)
	if err != nil { t.Fatal(err) }
	parentQuery := rasql.Select(parentSource.Source(), parentProjection)
	childSource, err := generated.Users().Source("u")
	if err != nil { t.Fatal(err) }
	childExpressions, err := (generated.UsersColumns{}).Bind(childSource)
	if err != nil { t.Fatal(err) }
	childProjection, err := generated.UsersProjection(childExpressions)
	if err != nil { t.Fatal(err) }
	childQuery := rasql.Select(childSource.Source(), childProjection)
	childPlan, err := rasql.NewGraphPlan(childQuery, func(row generated.UsersRow) userGraph { return userGraph{ID: row.ID} })
	if err != nil { t.Fatal(err) }
	edge, err := generated.ProjectsOwnerEdge(parentSource, childSource, childPlan, rasql.EdgeOptions{}, func(graph *projectGraph, value rasql.LoadedOne[userGraph]) { graph.Owner = value })
	if err != nil { t.Fatal(err) }
	if _, err = rasql.NewGraphPlan(parentQuery, func(generated.ProjectsRow) projectGraph { return projectGraph{} }, edge); err != nil { t.Fatal(err) }
	wrongParent, err := generated.Projects().Source("p2")
	if err != nil { t.Fatal(err) }
	wrongEdge, err := generated.ProjectsOwnerEdge(wrongParent, childSource, childPlan, rasql.EdgeOptions{}, func(graph *projectGraph, value rasql.LoadedOne[userGraph]) { graph.Owner = value })
	if err != nil { t.Fatal(err) }
	_, err = rasql.NewGraphPlan(parentQuery, func(generated.ProjectsRow) projectGraph { return projectGraph{} }, wrongEdge)
	if err == nil || !strings.Contains(err.Error(), "graph_key_mismatch") { t.Fatalf("err = %v, want graph_key_mismatch", err) }
}
`
	require.NoError(t, os.WriteFile(filepath.Join(root, "generated", "graph_test.go"), []byte(consumer), 0o600))
	command := exec.Command("go", "test", "-mod=mod", "./generated")
	command.Dir = root
	command.Env = append(os.Environ(), "GOCACHE="+filepath.Join(root, "cache"))
	output, err := command.CombinedOutput()
	require.NoError(t, err, "%s", output)
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("..")
	require.NoError(t, err)
	return root
}
