// Package generate creates deterministic Go source from schema descriptors.
package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/lestrrat-go/rasql/schema"
)

// Schema returns formatted Go source declaring reusable table references in packageName.
func Schema(packageName string, tables ...schema.Table) ([]byte, error) {
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf("generate: invalid package name %q", packageName)
	}
	clones := make([]schema.Table, len(tables))
	for i, table := range tables {
		if err := table.Validate(); err != nil {
			return nil, fmt.Errorf("generate: table at index %d: %w", i, err)
		}
		clones[i] = table.Clone()
	}
	sort.Slice(clones, func(left, right int) bool {
		return clones[left].Name < clones[right].Name
	})
	if err := validateVariableNames(clones); err != nil {
		return nil, err
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\n")
	source.WriteString("package ")
	source.WriteString(packageName)
	source.WriteString("\n\n")
	source.WriteString("import (\n")
	if containsTime(clones) {
		source.WriteString("\t\"time\"\n\n")
	}
	source.WriteString("\t\"github.com/lestrrat-go/rasql/query\"\n")
	source.WriteString("\t\"github.com/lestrrat-go/rasql/runtime\"\n")
	source.WriteString("\t\"github.com/lestrrat-go/rasql/schema\"\n")
	source.WriteString(")\n\n")
	for _, table := range clones {
		writeRowType(&source, table)
		source.WriteString("\n")
		source.WriteString("var ")
		source.WriteString(variableName(table.Name))
		source.WriteString(" = runtime.MustTable[")
		source.WriteString(rowTypeName(table.Name))
		source.WriteString("](query.MustNewTableRef(")
		writeTable(&source, table, "")
		source.WriteString("))\n\n")
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generate: format source: %w", err)
	}
	return formatted, nil
}

func validateVariableNames(tables []schema.Table) error {
	names := make(map[string]struct{}, len(tables)*2)
	for _, table := range tables {
		variable := variableName(table.Name)
		if variable == "" || !token.IsIdentifier(variable) {
			return fmt.Errorf("generate: table %q cannot become a Go identifier", table.Name)
		}
		if _, exists := names[variable]; exists {
			return fmt.Errorf("generate: table %q duplicates generated name %q", table.Name, variable)
		}
		names[variable] = struct{}{}
		rowType := rowTypeName(table.Name)
		if _, exists := names[rowType]; exists {
			return fmt.Errorf("generate: table %q duplicates generated name %q", table.Name, rowType)
		}
		names[rowType] = struct{}{}

		fields := make(map[string]struct{}, len(table.Columns))
		for _, column := range table.Columns {
			field := fieldName(column.Name)
			if field == "" || !token.IsIdentifier(field) {
				return fmt.Errorf("generate: column %q on table %q cannot become a Go field", column.Name, table.Name)
			}
			if _, exists := fields[field]; exists {
				return fmt.Errorf("generate: column %q on table %q duplicates generated field %q", column.Name, table.Name, field)
			}
			fields[field] = struct{}{}
		}
	}
	return nil
}

func variableName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_'
	})
	var result strings.Builder
	for _, part := range parts {
		for index, r := range part {
			if index == 0 {
				result.WriteRune(unicode.ToUpper(r))
				continue
			}
			result.WriteRune(r)
		}
	}
	return result.String()
}

func rowTypeName(tableName string) string {
	return variableName(tableName) + "Row"
}

func fieldName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_'
	})
	var result strings.Builder
	for _, part := range parts {
		switch strings.ToLower(part) {
		case "api":
			result.WriteString("API")
		case "id":
			result.WriteString("ID")
		case "json":
			result.WriteString("JSON")
		case "url":
			result.WriteString("URL")
		case "uuid":
			result.WriteString("UUID")
		default:
			for index, r := range part {
				if index == 0 {
					result.WriteRune(unicode.ToUpper(r))
					continue
				}
				result.WriteRune(r)
			}
		}
	}
	return result.String()
}

func containsTime(tables []schema.Table) bool {
	for _, table := range tables {
		for _, column := range table.Columns {
			if column.Type == schema.TypeTime {
				return true
			}
		}
	}
	return false
}

func writeRowType(source *bytes.Buffer, table schema.Table) {
	source.WriteString("type ")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString(" struct {\n")
	for _, column := range table.Columns {
		source.WriteString("\t")
		source.WriteString(fieldName(column.Name))
		source.WriteByte(' ')
		if column.Nullable {
			source.WriteByte('*')
		}
		source.WriteString(rowFieldType(column.Type))
		source.WriteString(" `rasql:")
		source.WriteString(quote(column.Name))
		source.WriteString("`\n")
	}
	source.WriteString("}\n")
}

func rowFieldType(logicalType schema.LogicalType) string {
	switch logicalType {
	case schema.TypeBoolean:
		return "bool"
	case schema.TypeInteger:
		return "int64"
	case schema.TypeFloat:
		return "float64"
	case schema.TypeText, schema.TypeUUID:
		return "string"
	case schema.TypeBytes, schema.TypeJSON:
		return "[]byte"
	case schema.TypeTime:
		return "time.Time"
	default:
		return "any"
	}
}

func writeTable(source *bytes.Buffer, table schema.Table, indent string) {
	source.WriteString("schema.Table{\n")
	writeField(source, indent+"\t", "Name", quote(table.Name))
	writeColumns(source, table.Columns, indent+"\t")
	writeStrings(source, table.PrimaryKey, indent+"\t", "PrimaryKey")
	writeUniqueConstraints(source, table.UniqueConstraints, indent+"\t")
	writeChecks(source, table.Checks, indent+"\t")
	writeIndexes(source, table.Indexes, indent+"\t")
	writeForeignKeys(source, table.ForeignKeys, indent+"\t")
	source.WriteString(indent)
	source.WriteByte('}')
}

func writeColumns(source *bytes.Buffer, columns []schema.Column, indent string) {
	if len(columns) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Columns: []schema.Column{\n")
	for _, column := range columns {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(column.Name))
		source.WriteString(", Type: ")
		source.WriteString(typeConstant(column.Type))
		if column.Nullable {
			source.WriteString(", Nullable: true")
		}
		if column.Default != "" {
			source.WriteString(", Default: ")
			source.WriteString(quote(column.Default))
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeStrings(source *bytes.Buffer, values []string, indent string, field string) {
	if len(values) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString(field)
	source.WriteString(": []string{")
	for index, value := range values {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(quote(value))
	}
	source.WriteString("},\n")
}

func writeUniqueConstraints(source *bytes.Buffer, constraints []schema.UniqueConstraint, indent string) {
	if len(constraints) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("UniqueConstraints: []schema.UniqueConstraint{\n")
	for _, constraint := range constraints {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(constraint.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, constraint.Columns)
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeChecks(source *bytes.Buffer, checks []schema.CheckConstraint, indent string) {
	if len(checks) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Checks: []schema.CheckConstraint{\n")
	for _, check := range checks {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(check.Name))
		source.WriteString(", Expression: ")
		source.WriteString(quote(check.Expression))
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeIndexes(source *bytes.Buffer, indexes []schema.Index, indent string) {
	if len(indexes) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Indexes: []schema.Index{\n")
	for _, index := range indexes {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(index.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, index.Columns)
		if index.Unique {
			source.WriteString(", Unique: true")
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeForeignKeys(source *bytes.Buffer, keys []schema.ForeignKey, indent string) {
	if len(keys) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("ForeignKeys: []schema.ForeignKey{\n")
	for _, key := range keys {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(key.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, key.Columns)
		source.WriteString(", ReferencedTable: ")
		source.WriteString(quote(key.ReferencedTable))
		source.WriteString(", ReferencedColumns: ")
		writeStringLiteralSlice(source, key.ReferencedColumns)
		if key.OnDelete != "" {
			source.WriteString(", OnDelete: ")
			source.WriteString(referenceActionConstant(key.OnDelete))
		}
		if key.OnUpdate != "" {
			source.WriteString(", OnUpdate: ")
			source.WriteString(referenceActionConstant(key.OnUpdate))
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeStringLiteralSlice(source *bytes.Buffer, values []string) {
	source.WriteString("[]string{")
	for index, value := range values {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(quote(value))
	}
	source.WriteByte('}')
}

func writeField(source *bytes.Buffer, indent string, name string, value string) {
	source.WriteString(indent)
	source.WriteString(name)
	source.WriteString(": ")
	source.WriteString(value)
	source.WriteString(",\n")
}

func typeConstant(logicalType schema.LogicalType) string {
	switch logicalType {
	case schema.TypeBoolean:
		return "schema.TypeBoolean"
	case schema.TypeInteger:
		return "schema.TypeInteger"
	case schema.TypeFloat:
		return "schema.TypeFloat"
	case schema.TypeText:
		return "schema.TypeText"
	case schema.TypeBytes:
		return "schema.TypeBytes"
	case schema.TypeTime:
		return "schema.TypeTime"
	case schema.TypeJSON:
		return "schema.TypeJSON"
	case schema.TypeUUID:
		return "schema.TypeUUID"
	default:
		return "schema.LogicalType(" + quote(string(logicalType)) + ")"
	}
}

func referenceActionConstant(action schema.ReferenceAction) string {
	switch action {
	case schema.ReferenceActionNoAction:
		return "schema.ReferenceActionNoAction"
	case schema.ReferenceActionRestrict:
		return "schema.ReferenceActionRestrict"
	case schema.ReferenceActionCascade:
		return "schema.ReferenceActionCascade"
	case schema.ReferenceActionSetNull:
		return "schema.ReferenceActionSetNull"
	case schema.ReferenceActionSetDefault:
		return "schema.ReferenceActionSetDefault"
	default:
		return "schema.ReferenceAction(" + quote(string(action)) + ")"
	}
}

func quote(value string) string {
	return strconv.Quote(value)
}
