// Package generate creates deterministic Go source from schema descriptors.
package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/lestrrat-go/rasql/schema"
)

// reservedFieldNames holds the identifiers a generated table type already uses.
// A column whose generated field name lands on one of them is rejected, because
// the field would shadow the embedded rasql.Table or its methods, or collide
// with a mapping method declared on the row type.
var reservedFieldNames = map[string]struct{}{
	"As":               {},
	"Column":           {},
	"ColumnValue":      {},
	"DecodeRow":        {},
	"IsGeneratedRow":   {},
	"QueryTable":       {},
	"ScanDestinations": {},
	"ScanRow":          {},
	"Table":            {},
	"tableRow":         {},
}

// ValidateSchema checks whether packageName and tables can produce Go source.
// It checks names across all tables, so callers that generate one file per
// table can still reject collisions between those files before writing any.
func ValidateSchema(packageName string, tables ...schema.Table) error {
	_, err := prepareSchema(packageName, tables)
	return err
}

// Schema returns formatted Go source declaring reusable table descriptors in packageName.
func Schema(packageName string, tables ...schema.Table) ([]byte, error) {
	clones, err := prepareSchema(packageName, tables)
	if err != nil {
		return nil, err
	}
	return schemaSource(packageName, clones, clones)
}

// SchemaTable returns the generated source for table. allTables supplies the
// package-wide descriptors used to derive relationship methods. It is useful
// to callers such as rasqlgen that keep one generated file per table.
func SchemaTable(packageName string, table schema.Table, allTables ...schema.Table) ([]byte, error) {
	if len(allTables) == 0 {
		allTables = []schema.Table{table}
	}
	clones, err := prepareSchema(packageName, allTables)
	if err != nil {
		return nil, err
	}
	for _, candidate := range clones {
		if candidate.Schema == table.Schema && candidate.Name == table.Name {
			return schemaSource(packageName, []schema.Table{candidate}, clones)
		}
	}
	return nil, fmt.Errorf("generate: table %q is not present in allTables", table.QualifiedName())
}

func schemaSource(packageName string, tables, allTables []schema.Table) ([]byte, error) {

	var source bytes.Buffer
	source.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\n")
	source.WriteString("package ")
	source.WriteString(packageName)
	source.WriteString("\n\n")
	// An empty schema declares nothing, so importing anything would not compile.
	if len(tables) > 0 {
		source.WriteString("import (\n")
		source.WriteString("\t\"fmt\"\n")
		if containsTime(tables) {
			source.WriteString("\t\"time\"\n")
		}
		if containsRelationships(tables, allTables) {
			source.WriteString("\t\"context\"\n")
		}
		source.WriteString("\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql\"\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql/query\"\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql/row\"\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql/schema\"\n")
		source.WriteString(")\n\n")
	}
	for _, table := range tables {
		writeRowType(&source, table)
		source.WriteString("\n")
		writeRowDecode(&source, table)
		source.WriteString("\n")
		writeRowScan(&source, table)
		source.WriteString("\n")
		writeRowColumnValue(&source, table)
		source.WriteString("\n")
		writeTableType(&source, table)
		source.WriteString("\n")
		writeTableConstructor(&source, table)
		source.WriteString("\n")
		writeTableDescriptor(&source, table)
		source.WriteString("\n")
		writeTableAccessor(&source, table)
		source.WriteString("\n")
		writeTableAs(&source, table)
		source.WriteString("\n")
		writeRelationships(&source, table, allTables)
		source.WriteString("\n")
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generate: format source: %w", err)
	}
	return formatted, nil
}

func prepareSchema(packageName string, tables []schema.Table) ([]schema.Table, error) {
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf("generate: invalid package name %q", packageName)
	}
	clones := make([]schema.Table, len(tables))
	for i, table := range tables {
		if err := table.Validate(); err != nil {
			return nil, fmt.Errorf("generate: table at index %d: %w", i, err)
		}
		clones[i] = table.Clone()
		clones[i].Relationships = mergeRelationships(clones[i])
	}
	sort.Slice(clones, func(left, right int) bool {
		return clones[left].Name < clones[right].Name
	})
	if err := validateVariableNames(clones); err != nil {
		return nil, err
	}
	return clones, nil
}

func derivedRelationships(table schema.Table) []schema.Relationship {
	relationships := make([]schema.Relationship, 0, len(table.ForeignKeys))
	for _, key := range table.ForeignKeys {
		if len(key.Columns) == 0 {
			continue
		}
		name := key.Columns[0]
		name = strings.TrimSuffix(name, "_id")
		name = variableName(name)
		if name == "" {
			name = variableName(key.ReferencedTable)
		}
		relationships = append(relationships, schema.Relationship{
			Name:              name,
			Kind:              schema.RelationshipBelongsTo,
			Columns:           append([]string(nil), key.Columns...),
			ReferencedSchema:  key.ReferencedSchema,
			ReferencedTable:   key.ReferencedTable,
			ReferencedColumns: append([]string(nil), key.ReferencedColumns...),
		})
	}
	return relationships
}

func mergeRelationships(table schema.Table) []schema.Relationship {
	relationships := make([]schema.Relationship, 0, len(table.ForeignKeys))
	matched := make([]bool, len(table.ForeignKeys))
	for _, relationship := range table.Relationships {
		relationships = append(relationships, relationship)
		for index, key := range table.ForeignKeys {
			if matched[index] || !relationshipMatchesForeignKey(relationship, key) {
				continue
			}
			matched[index] = true
			break
		}
	}
	for index, key := range table.ForeignKeys {
		if matched[index] {
			continue
		}
		derived := derivedRelationships(schema.Table{ForeignKeys: []schema.ForeignKey{key}})
		relationships = append(relationships, derived...)
	}
	return relationships
}

func relationshipMatchesForeignKey(relationship schema.Relationship, key schema.ForeignKey) bool {
	return relationship.ReferencedSchema == key.ReferencedSchema &&
		relationship.ReferencedTable == key.ReferencedTable &&
		stringSlicesEqual(relationship.Columns, key.Columns) &&
		stringSlicesEqual(relationship.ReferencedColumns, key.ReferencedColumns)
}

func stringSlicesEqual(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func validateVariableNames(tables []schema.Table) error {
	names := make(map[string]struct{}, len(tables)*2)
	for _, table := range tables {
		variable := variableName(table.Name)
		if variable == "" || !token.IsIdentifier(variable) {
			return fmt.Errorf("generate: table %q cannot become a Go identifier", table.Name)
		}
		if _, exists := names[variable]; exists {
			return fmt.Errorf("generate: table %q duplicates generated name %q", table.Name, variable)
		}
		names[variable] = struct{}{}
		for _, generated := range []string{
			rowTypeName(table.Name),
			tableTypeName(table.Name),
			constructorName(table.Name),
			descriptorName(table.Name),
		} {
			if _, exists := names[generated]; exists {
				return fmt.Errorf("generate: table %q duplicates generated name %q", table.Name, generated)
			}
			names[generated] = struct{}{}
		}

		fields := make(map[string]struct{}, len(table.Columns))
		for _, column := range table.Columns {
			field := goName(column.Name)
			if field == "" || !token.IsIdentifier(field) {
				return fmt.Errorf("generate: column %q on table %q cannot become a Go field", column.Name, table.Name)
			}
			if _, exists := reservedFieldNames[field]; exists {
				return fmt.Errorf("generate: column %q on table %q uses reserved generated field %q", column.Name, table.Name, field)
			}
			if _, exists := fields[field]; exists {
				return fmt.Errorf("generate: column %q on table %q duplicates generated field %q", column.Name, table.Name, field)
			}
			fields[field] = struct{}{}
		}
		relationshipMethods := make(map[string]struct {
			index int
			name  string
		})
		for index, relationship := range table.Relationships {
			method := goName(relationship.Name)
			if !token.IsIdentifier(method) {
				return fmt.Errorf("generate: relationship %q on table %q cannot become a Go method", relationship.Name, table.Name)
			}
			if reservedRelationshipMethod(method) {
				return fmt.Errorf("generate: relationship %q on table %q uses reserved generated method %q", relationship.Name, table.Name, method)
			}
			if previous, exists := relationshipMethods[method]; exists {
				return fmt.Errorf("generate: relationships[%d] %q and relationships[%d] %q on table %q duplicate generated method %q", previous.index, previous.name, index, relationship.Name, table.Name, method)
			}
			relationshipMethods[method] = struct {
				index int
				name  string
			}{index: index, name: relationship.Name}
		}
		for _, relationship := range table.Relationships {
			method := goName(relationship.Name)
			if _, exists := fields[method]; exists {
				return fmt.Errorf("generate: relationship %q on table %q collides with generated field %q", relationship.Name, table.Name, method)
			}
		}
		for _, relationship := range relationshipSpecs(table, tables) {
			if _, exists := fields[relationship.method]; exists {
				return fmt.Errorf("generate: relationship %q on table %q collides with generated field %q", relationship.method, table.Name, relationship.method)
			}
		}
	}
	for _, table := range tables {
		for _, relationship := range relationshipSpecs(table, tables) {
			if _, exists := names[relationship.typeName]; exists {
				return fmt.Errorf("generate: relationship %q on table %q duplicates generated name %q", relationship.method, table.Name, relationship.typeName)
			}
			names[relationship.typeName] = struct{}{}
		}
	}
	return nil
}

// variableName returns the exported Go identifier for a table name. It
// delegates to goName so tables use the same initialism rules as columns:
// a table named api_keys and a column named api_key both spell "API" the
// same way, instead of the table getting a plain "Api".
func variableName(name string) string {
	return goName(name)
}

func rowTypeName(tableName string) string {
	return variableName(tableName) + "Row"
}

// tableTypeName returns the exported wrapper type holding the typed table and
// its column fields.
func tableTypeName(tableName string) string {
	return variableName(tableName) + "Table"
}

// constructorName returns the unexported function binding every column field to
// one table value. As reuses it to rebind columns to an alias.
func constructorName(tableName string) string {
	return "new" + tableTypeName(tableName)
}

// descriptorName returns the unexported variable name backing an accessor.
// Distinctness across accessors is enforced by validateVariableNames, which
// includes descriptor names in its collision set, not by any property of
// this lowering.
func descriptorName(tableName string) string {
	accessor := variableName(tableName)
	if accessor == "" {
		return ""
	}
	runes := []rune(accessor)
	// Find the leading run of uppercase runes: for "APIKeys" that is "APIK",
	// because casing alone cannot tell an initialism from the capital that
	// starts the next word. When the run stops partway through the name, its
	// last rune is that next word's leading capital (the "K" of "Keys") and
	// stays as-is; only the initialism before it gets lowered, so "APIKeys"
	// becomes "apiKeys" rather than "apikeys". A run spanning the whole name
	// (e.g. "ID") or only the first rune (e.g. "Users") has no such word
	// boundary to protect, so it lowers completely.
	end := 0
	for end < len(runes) && unicode.IsUpper(runes[end]) {
		end++
	}
	if end > 1 && end < len(runes) {
		end--
	}
	for index := 0; index < end; index++ {
		runes[index] = unicode.ToLower(runes[index])
	}
	return string(runes) + "Table"
}

func goName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_'
	})
	var result strings.Builder
	for _, part := range parts {
		switch strings.ToLower(part) {
		case "api":
			result.WriteString("API")
		case "id":
			result.WriteString("ID")
		case "json":
			result.WriteString("JSON")
		case "url":
			result.WriteString("URL")
		case "uuid":
			result.WriteString("UUID")
		default:
			for index, r := range part {
				if index == 0 {
					result.WriteRune(unicode.ToUpper(r))
					continue
				}
				result.WriteRune(r)
			}
		}
	}
	return result.String()
}

func containsTime(tables []schema.Table) bool {
	for _, table := range tables {
		for _, column := range table.Columns {
			if column.Type.Kind() == schema.KindTime {
				return true
			}
		}
	}
	return false
}

// writeTableType writes the exported wrapper type: the typed table plus one
// query.Column field per column, so a mistyped column name fails to compile.
func writeTableType(source *bytes.Buffer, table schema.Table) {
	typeName := tableTypeName(table.Name)
	source.WriteString("// ")
	source.WriteString(typeName)
	source.WriteString(" is the generated table type for the ")
	source.WriteString(quote(table.Name))
	source.WriteString(" table.\n")
	source.WriteString("type ")
	source.WriteString(typeName)
	source.WriteString(" struct {\n\trasql.Table[")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString("]\n")
	for _, column := range table.Columns {
		source.WriteString("\t")
		source.WriteString(goName(column.Name))
		source.WriteString(" query.Column\n")
	}
	source.WriteString("}\n")
}

// writeTableConstructor writes the function binding every column field to table.
func writeTableConstructor(source *bytes.Buffer, table schema.Table) {
	typeName := tableTypeName(table.Name)
	source.WriteString("func ")
	source.WriteString(constructorName(table.Name))
	source.WriteString("(table rasql.Table[")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString("]) ")
	source.WriteString(typeName)
	source.WriteString(" {\n\treturn ")
	source.WriteString(typeName)
	source.WriteString("{\n\t\tTable: table,\n")
	for _, column := range table.Columns {
		source.WriteString("\t\t")
		source.WriteString(goName(column.Name))
		source.WriteString(": rasql.MustColumn(table, ")
		source.WriteString(quote(column.Name))
		source.WriteString("),\n")
	}
	source.WriteString("\t}\n}\n")
}

// writeTableDescriptor writes the unexported variable holding the table.
// Keeping it unexported means importers reach the table only through the
// accessor and cannot replace it.
func writeTableDescriptor(source *bytes.Buffer, table schema.Table) {
	source.WriteString("var ")
	source.WriteString(descriptorName(table.Name))
	source.WriteString(" = ")
	source.WriteString(constructorName(table.Name))
	source.WriteString("(rasql.MustTable[")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString("](")
	writeTable(source, table, "")
	source.WriteString("))\n")
}

func writeTableAccessor(source *bytes.Buffer, table schema.Table) {
	accessor := variableName(table.Name)
	source.WriteString("// ")
	source.WriteString(accessor)
	source.WriteString(" returns the descriptor for the ")
	source.WriteString(quote(table.Name))
	source.WriteString(" table.\n")
	source.WriteString("func ")
	source.WriteString(accessor)
	source.WriteString("() ")
	source.WriteString(tableTypeName(table.Name))
	source.WriteString(" {\n\treturn ")
	source.WriteString(descriptorName(table.Name))
	source.WriteString("\n}\n")
}

// writeTableAs writes the alias constructor. It rebinds every column through the
// table constructor, so an aliased table qualifies its columns with the alias.
func writeTableAs(source *bytes.Buffer, table schema.Table) {
	typeName := tableTypeName(table.Name)
	source.WriteString("// As returns the table under alias, with every column rebound to it.\n")
	source.WriteString("func (t ")
	source.WriteString(typeName)
	source.WriteString(") As(alias string) (")
	source.WriteString(typeName)
	source.WriteString(", error) {\n")
	source.WriteString("\taliased, err := rasql.As(t.Table, alias)\n")
	source.WriteString("\tif err != nil {\n\t\treturn ")
	source.WriteString(typeName)
	source.WriteString("{}, err\n\t}\n\treturn ")
	source.WriteString(constructorName(table.Name))
	source.WriteString("(aliased), nil\n}\n")
}

func writeRowType(source *bytes.Buffer, table schema.Table) {
	source.WriteString("type ")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString(" struct {\n")
	for _, column := range table.Columns {
		source.WriteString("\t")
		source.WriteString(goName(column.Name))
		source.WriteByte(' ')
		if column.Nullable {
			source.WriteByte('*')
		}
		source.WriteString(rowFieldType(column))
		source.WriteString("\n")
	}
	source.WriteString("}\n")
}

type relationshipSpec struct {
	kind          schema.RelationshipKind
	method        string
	typeName      string
	parent        schema.Table
	child         schema.Table
	parentColumn  schema.Column
	childColumn   schema.Column
	parentField   string
	childField    string
	parentKeyType string
}

type inverseRelationshipCandidate struct {
	child        schema.Table
	relationship schema.Relationship
	parentColumn schema.Column
	childColumn  schema.Column
	keyType      string
}

func containsRelationships(tables, allTables []schema.Table) bool {
	for _, table := range tables {
		if len(relationshipSpecs(table, allTables)) > 0 {
			return true
		}
	}
	return false
}

func relationshipSpecs(table schema.Table, allTables []schema.Table) []relationshipSpec {
	result := make([]relationshipSpec, 0)
	usedMethods := make(map[string]struct{})
	for _, relationship := range table.Relationships {
		if relationship.Kind != schema.RelationshipBelongsTo || len(relationship.Columns) != 1 || len(relationship.ReferencedColumns) != 1 {
			continue
		}
		parent, ok := relationshipTable(allTables, relationship.ReferencedSchema, relationship.ReferencedTable)
		if !ok {
			continue
		}
		childColumn, ok := table.Column(relationship.Columns[0])
		if !ok || childColumn.Nullable {
			continue
		}
		parentColumn, ok := parent.Column(relationship.ReferencedColumns[0])
		if !ok || parentColumn.Nullable || len(parent.PrimaryKey) != 1 || parent.PrimaryKey[0] != parentColumn.Name {
			continue
		}
		keyType, ok := relationKeyType(parentColumn)
		if !ok || keyType != rowFieldType(childColumn) {
			continue
		}
		method := goName(relationship.Name)
		if !token.IsIdentifier(method) || reservedRelationshipMethod(method) {
			continue
		}
		if _, exists := usedMethods[method]; exists {
			continue
		}
		usedMethods[method] = struct{}{}
		result = append(result, relationshipSpec{
			kind:          schema.RelationshipBelongsTo,
			method:        method,
			typeName:      tableTypeName(table.Name) + method + "Relation",
			parent:        parent,
			child:         table,
			parentColumn:  parentColumn,
			childColumn:   childColumn,
			parentField:   goName(parentColumn.Name),
			childField:    goName(childColumn.Name),
			parentKeyType: keyType,
		})
	}

	candidates := make([]inverseRelationshipCandidate, 0)
	for _, child := range allTables {
		for _, relationship := range child.Relationships {
			if relationship.Kind != schema.RelationshipBelongsTo || len(relationship.Columns) != 1 || len(relationship.ReferencedColumns) != 1 {
				continue
			}
			if relationship.ReferencedTable != table.Name || relationship.ReferencedSchema != table.Schema {
				continue
			}
			childColumn, ok := child.Column(relationship.Columns[0])
			if !ok || childColumn.Nullable {
				continue
			}
			parentColumn, ok := table.Column(relationship.ReferencedColumns[0])
			if !ok || parentColumn.Nullable || len(table.PrimaryKey) != 1 || table.PrimaryKey[0] != parentColumn.Name {
				continue
			}
			keyType, ok := relationKeyType(parentColumn)
			if !ok || keyType != rowFieldType(childColumn) {
				continue
			}
			candidates = append(candidates, inverseRelationshipCandidate{
				child:        child,
				relationship: relationship,
				parentColumn: parentColumn,
				childColumn:  childColumn,
				keyType:      keyType,
			})
		}
	}
	sort.SliceStable(candidates, func(left, right int) bool {
		leftKey := inverseRelationshipSortKey(candidates[left])
		rightKey := inverseRelationshipSortKey(candidates[right])
		return leftKey < rightKey
	})
	for _, candidate := range candidates {
		method := inverseRelationshipMethodName(candidate.child, candidate.relationship, usedMethods)
		if method == "" {
			continue
		}
		usedMethods[method] = struct{}{}
		result = append(result, relationshipSpec{
			kind:          schema.RelationshipHasMany,
			method:        method,
			typeName:      tableTypeName(table.Name) + method + "Relation",
			parent:        table,
			child:         candidate.child,
			parentColumn:  candidate.parentColumn,
			childColumn:   candidate.childColumn,
			parentField:   goName(candidate.parentColumn.Name),
			childField:    goName(candidate.childColumn.Name),
			parentKeyType: candidate.keyType,
		})
	}
	return result
}

func inverseRelationshipSortKey(candidate inverseRelationshipCandidate) string {
	return strings.Join([]string{
		candidate.child.Schema,
		candidate.child.Name,
		candidate.relationship.Name,
		strings.Join(candidate.relationship.Columns, "\x00"),
		strings.Join(candidate.relationship.ReferencedColumns, "\x00"),
		candidate.parentColumn.Name,
		candidate.childColumn.Name,
	}, "\x00")
}

// Inverse methods use the child table name when it is available. A collision
// or reserved name gets the relationship name as a stable prefix, followed by
// a numeric suffix only when that name is also occupied.
func inverseRelationshipMethodName(child schema.Table, relationship schema.Relationship, usedMethods map[string]struct{}) string {
	base := variableName(child.Name)
	if base == "" {
		return ""
	}
	if _, exists := usedMethods[base]; !exists && !reservedRelationshipMethod(base) {
		return base
	}

	prefix := goName(relationship.Name)
	if prefix == "" {
		return ""
	}
	base = prefix + base
	if _, exists := usedMethods[base]; !exists && !reservedRelationshipMethod(base) {
		return base
	}
	for suffix := 2; ; suffix++ {
		candidate := base + strconv.Itoa(suffix)
		if _, exists := usedMethods[candidate]; !exists && !reservedRelationshipMethod(candidate) {
			return candidate
		}
	}
}

func relationshipTable(tables []schema.Table, referencedSchema, referencedName string) (schema.Table, bool) {
	for _, table := range tables {
		if table.Name != referencedName {
			continue
		}
		if table.Schema != referencedSchema {
			continue
		}
		return table, true
	}
	return schema.Table{}, false
}

func relationKeyType(column schema.Column) (string, bool) {
	fieldType := rowFieldType(column)
	if fieldType == "[]byte" || column.Nullable {
		return "", false
	}
	return fieldType, true
}

func reservedRelationshipMethod(name string) bool {
	_, reserved := reservedFieldNames[name]
	return reserved
}

func writeRelationships(source *bytes.Buffer, table schema.Table, allTables []schema.Table) {
	for _, relationship := range relationshipSpecs(table, allTables) {
		source.WriteString("// ")
		source.WriteString(relationship.typeName)
		source.WriteString(" describes the ")
		source.WriteString(relationship.method)
		source.WriteString(" relationship from ")
		source.WriteString(tableTypeName(table.Name))
		source.WriteString(".\n")
		source.WriteString("type ")
		source.WriteString(relationship.typeName)
		source.WriteString(" struct {\n")
		source.WriteString("\tParent ")
		source.WriteString(tableTypeName(relationship.parent.Name))
		source.WriteString("\n\tChild ")
		source.WriteString(tableTypeName(relationship.child.Name))
		source.WriteString("\n\tParentKey query.Column\n\tChildKey query.Column\n}\n\n")

		source.WriteString("// ")
		source.WriteString(relationship.method)
		source.WriteString(" returns the generated relationship descriptor.\n")
		source.WriteString("func (t ")
		source.WriteString(tableTypeName(table.Name))
		source.WriteString(") ")
		source.WriteString(relationship.method)
		source.WriteString("() ")
		source.WriteString(relationship.typeName)
		source.WriteString(" {\n")
		if relationship.kind == schema.RelationshipHasMany {
			source.WriteString("\tchild := ")
			source.WriteString(variableName(relationship.child.Name))
			source.WriteString("()\n\tparent := t\n")
		} else {
			source.WriteString("\tchild := t\n\tparent := ")
			source.WriteString(variableName(relationship.parent.Name))
			source.WriteString("()\n")
		}
		source.WriteString("\treturn ")
		source.WriteString(relationship.typeName)
		source.WriteString("{Parent: parent, Child: child, ParentKey: parent.")
		source.WriteString(relationship.parentField)
		source.WriteString(", ChildKey: child.")
		source.WriteString(relationship.childField)
		source.WriteString("}\n}\n\n")

		source.WriteString("// Join returns an INNER JOIN for the relationship.\n")
		source.WriteString("func (r ")
		source.WriteString(relationship.typeName)
		source.WriteString(") Join() query.Join {\n\treturn rasql.InnerJoin(r.")
		if relationship.kind == schema.RelationshipHasMany {
			source.WriteString("Child")
		} else {
			source.WriteString("Parent")
		}
		source.WriteString(", query.Equal(r.ParentKey, r.ChildKey))\n}\n\n")
		writeRelationshipLoad(source, relationship)
	}
}

func writeRelationshipLoad(source *bytes.Buffer, relationship relationshipSpec) {
	if relationship.kind == schema.RelationshipHasMany {
		source.WriteString("// Load fetches all children for parents in one query and groups them by parent key.\n")
		source.WriteString("func (r ")
		source.WriteString(relationship.typeName)
		source.WriteString(") Load(ctx context.Context, x rasql.Executor, parents []")
		source.WriteString(rowTypeName(relationship.parent.Name))
		source.WriteString(") (map[")
		source.WriteString(relationship.parentKeyType)
		source.WriteString("][]")
		source.WriteString(rowTypeName(relationship.child.Name))
		source.WriteString(", error) {\n\treturn rasql.LoadHasMany[")
		source.WriteString(rowTypeName(relationship.parent.Name))
		source.WriteString(", ")
		source.WriteString(rowTypeName(relationship.child.Name))
		source.WriteString(", ")
		source.WriteString(relationship.parentKeyType)
		source.WriteString("](ctx, x, r.Child, r.ChildKey, parents, func(row ")
		source.WriteString(rowTypeName(relationship.parent.Name))
		source.WriteString(") ")
		source.WriteString(relationship.parentKeyType)
		source.WriteString(" { return row.")
		source.WriteString(relationship.parentField)
		source.WriteString(" }, func(row ")
		source.WriteString(rowTypeName(relationship.child.Name))
		source.WriteString(") ")
		source.WriteString(relationship.parentKeyType)
		source.WriteString(" { return row.")
		source.WriteString(relationship.childField)
		source.WriteString(" })\n}\n\n")
		return
	}

	source.WriteString("// Load fetches all related parents for children in one query and groups them by foreign-key value.\n")
	source.WriteString("func (r ")
	source.WriteString(relationship.typeName)
	source.WriteString(") Load(ctx context.Context, x rasql.Executor, children []")
	source.WriteString(rowTypeName(relationship.child.Name))
	source.WriteString(") (map[")
	source.WriteString(relationship.parentKeyType)
	source.WriteString("]")
	source.WriteString(rowTypeName(relationship.parent.Name))
	source.WriteString(", error) {\n\treturn rasql.LoadBelongsTo[")
	source.WriteString(rowTypeName(relationship.child.Name))
	source.WriteString(", ")
	source.WriteString(rowTypeName(relationship.parent.Name))
	source.WriteString(", ")
	source.WriteString(relationship.parentKeyType)
	source.WriteString("](ctx, x, r.Parent, r.ParentKey, children, func(row ")
	source.WriteString(rowTypeName(relationship.child.Name))
	source.WriteString(") ")
	source.WriteString(relationship.parentKeyType)
	source.WriteString(" { return row.")
	source.WriteString(relationship.childField)
	source.WriteString(" }, func(row ")
	source.WriteString(rowTypeName(relationship.parent.Name))
	source.WriteString(") ")
	source.WriteString(relationship.parentKeyType)
	source.WriteString(" { return row.")
	source.WriteString(relationship.parentField)
	source.WriteString(" })\n}\n\n")
}

// writeRowDecode writes the row.Decoder implementation. The generator
// already knows which column feeds which field, so the row type states that
// mapping directly instead of restating it as a tag for reflection to parse.
func writeRowDecode(source *bytes.Buffer, table schema.Table) {
	typeName := rowTypeName(table.Name)
	source.WriteString("// DecodeRow assigns each result column to its field.\n")
	source.WriteString("func (r *")
	source.WriteString(typeName)
	source.WriteString(") DecodeRow(src row.Dynamic) error {\n")
	last := len(table.Columns) - 1
	for index, column := range table.Columns {
		if index == last {
			source.WriteString("\treturn ")
			writeRowAssign(source, column)
			source.WriteString("\n")
			break
		}
		source.WriteString("\tif err := ")
		writeRowAssign(source, column)
		source.WriteString("; err != nil {\n\t\treturn err\n\t}\n")
	}
	source.WriteString("}\n")
}

func writeRowAssign(source *bytes.Buffer, column schema.Column) {
	source.WriteString("row.Assign(src, ")
	source.WriteString(quote(column.Name))
	source.WriteString(", &r.")
	source.WriteString(goName(column.Name))
	source.WriteString(")")
}

// writeRowScan writes the direct database/sql scan path and the runtime result
// column mapping path.
func writeRowScan(source *bytes.Buffer, table schema.Table) {
	typeName := rowTypeName(table.Name)
	if tableHasTimeColumn(table) {
		source.WriteString("type ")
		source.WriteString(timeScannerTypeName(table.Name))
		source.WriteString(" func(any) error\n\n")
		source.WriteString("func (s ")
		source.WriteString(timeScannerTypeName(table.Name))
		source.WriteString(") Scan(value any) error {\n\treturn s(value)\n}\n\n")
	}
	source.WriteString("// ScanRow scans each result column directly into its field.\n")
	source.WriteString("func (r *")
	source.WriteString(typeName)
	source.WriteString(") ScanRow(src row.ScanSource) error {\n")
	for index, column := range table.Columns {
		if !isTimeColumn(column) {
			continue
		}
		source.WriteString("\ttimeScanner")
		source.WriteString(strconv.Itoa(index))
		source.WriteString(" := ")
		writeTimeScannerLiteral(source, table.Name, column, "&r."+goName(column.Name))
		source.WriteString("\n")
	}
	source.WriteString("\treturn src.Scan(")
	for index, column := range table.Columns {
		if index > 0 {
			source.WriteString(", ")
		}
		if isTimeColumn(column) {
			source.WriteString("&timeScanner")
			source.WriteString(strconv.Itoa(index))
		} else {
			source.WriteString("&r.")
			source.WriteString(goName(column.Name))
		}
	}
	source.WriteString(")\n}\n")

	source.WriteString("\n// IsGeneratedRow marks this row as generated by rasqlgen.\n")
	source.WriteString("func (*")
	source.WriteString(typeName)
	source.WriteString(") IsGeneratedRow() {}\n")

	source.WriteString("\n// ScanDestinations maps result-column names to fields on r.\n")
	source.WriteString("func (r *")
	source.WriteString(typeName)
	source.WriteString(") ScanDestinations(columns []string) ([]any, error) {\n")
	for index, column := range table.Columns {
		if !isTimeColumn(column) {
			continue
		}
		source.WriteString("\ttimeScanner")
		source.WriteString(strconv.Itoa(index))
		source.WriteString(" := ")
		writeTimeScannerLiteral(source, table.Name, column, "&r."+goName(column.Name))
		source.WriteString("\n")
	}
	source.WriteString("\tdestinations := make([]any, len(columns))\n")
	maskWords := (len(table.Columns) + 63) / 64
	if maskWords <= 1 {
		source.WriteString("\tvar scanned uint64\n")
	} else {
		source.WriteString("\tvar scanned [")
		source.WriteString(strconv.Itoa(maskWords))
		source.WriteString("]uint64\n")
	}
	source.WriteString("\tvar discard any\n")
	source.WriteString("\tfor index, column := range columns {\n\t\tswitch column {\n")
	for index, column := range table.Columns {
		field := goName(column.Name)
		word := index / 64
		bit := index % 64
		source.WriteString("\t\tcase ")
		source.WriteString(quote(column.Name))
		source.WriteString(":\n\t\t\tif ")
		writeScanMask(source, maskWords, word)
		source.WriteString(" & (uint64(1) << ")
		source.WriteString(strconv.Itoa(bit))
		source.WriteString(")")
		source.WriteString(" != 0 {\n\t\t\t\treturn nil, fmt.Errorf(\"duplicate result column %q\", column)\n\t\t\t}\n\t\t\t")
		writeScanMask(source, maskWords, word)
		source.WriteString(" |= uint64(1) << ")
		source.WriteString(strconv.Itoa(bit))
		source.WriteString("\n\t\t\tdestinations[index] = ")
		if isTimeColumn(column) {
			source.WriteString("&timeScanner")
			source.WriteString(strconv.Itoa(index))
		} else {
			source.WriteString("&r.")
			source.WriteString(field)
		}
		source.WriteString("\n")
	}
	source.WriteString("\t\tdefault:\n\t\t\tdestinations[index] = &discard\n\t\t}\n\t}\n")
	source.WriteString("\treturn destinations, nil\n}\n")
}

func tableHasTimeColumn(table schema.Table) bool {
	for _, column := range table.Columns {
		if isTimeColumn(column) {
			return true
		}
	}
	return false
}

func isTimeColumn(column schema.Column) bool {
	return column.Type.Kind() == schema.KindTime
}

func timeScannerTypeName(tableName string) string {
	return strings.TrimSuffix(descriptorName(tableName), "Table") + "TimeScanner"
}

func writeTimeScannerLiteral(source *bytes.Buffer, tableName string, column schema.Column, destination string) {
	source.WriteString(timeScannerTypeName(tableName))
	source.WriteString("(func(value any) error {\n")
	source.WriteString("\t\tdecoded, err := row.New([]string{")
	source.WriteString(quote(column.Name))
	source.WriteString("}, []any{value})\n")
	source.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	source.WriteString("\t\treturn row.Assign(decoded, ")
	source.WriteString(quote(column.Name))
	source.WriteString(", ")
	source.WriteString(destination)
	source.WriteString(")\n\t})")
}

func writeScanMask(source *bytes.Buffer, maskWords, word int) {
	if maskWords <= 1 {
		source.WriteString("scanned")
		return
	}
	source.WriteString("scanned[")
	source.WriteString(strconv.Itoa(word))
	source.WriteString("]")
}

// writeRowColumnValue writes the rasql.ColumnValuer implementation, which is
// the write-direction counterpart of DecodeRow.
func writeRowColumnValue(source *bytes.Buffer, table schema.Table) {
	typeName := rowTypeName(table.Name)
	source.WriteString("// ColumnValue returns the value of the named column.\n")
	source.WriteString("func (r ")
	source.WriteString(typeName)
	source.WriteString(") ColumnValue(name string) (any, bool) {\n")
	source.WriteString("\tswitch name {\n")
	for _, column := range table.Columns {
		source.WriteString("\tcase ")
		source.WriteString(quote(column.Name))
		source.WriteString(":\n\t\treturn r.")
		source.WriteString(goName(column.Name))
		source.WriteString(", true\n")
	}
	source.WriteString("\t}\n\treturn nil, false\n}\n")
}

// rowFieldType returns the Go type of the row field holding column. It takes
// the whole column because signedness changes the answer: an unsigned integer
// column reaches 18446744073709551615, which int64 cannot hold, so it generates
// a uint64 field. Every other integer column keeps int64.
func rowFieldType(column schema.Column) string {
	switch typed := column.Type.(type) {
	case schema.IntegerType:
		if typed.Unsigned {
			return "uint64"
		}
		return "int64"
	case schema.BooleanType:
		return "bool"
	case schema.FloatType:
		return "float64"
	case schema.TextType, schema.UUIDType:
		return "string"
	case schema.BytesType, schema.JSONType:
		return "[]byte"
	case schema.TimeType:
		return "time.Time"
	case schema.DecimalType:
		return "string"
	default:
		return "any"
	}
}

func writeTable(source *bytes.Buffer, table schema.Table, indent string) {
	source.WriteString("schema.Table{\n")
	writeField(source, indent+"\t", "Name", quote(table.Name))
	writeColumns(source, table.Columns, indent+"\t")
	writeStrings(source, table.PrimaryKey, indent+"\t", "PrimaryKey")
	writeUniqueConstraints(source, table.UniqueConstraints, indent+"\t")
	writeChecks(source, table.Checks, indent+"\t")
	writeIndexes(source, table.Indexes, indent+"\t")
	writeForeignKeys(source, table.ForeignKeys, indent+"\t")
	writeSchemaRelationships(source, table.Relationships, indent+"\t")
	source.WriteString(indent)
	source.WriteByte('}')
}

func writeSchemaRelationships(source *bytes.Buffer, relationships []schema.Relationship, indent string) {
	if len(relationships) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Relationships: []schema.Relationship{\n")
	for _, relationship := range relationships {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(relationship.Name))
		source.WriteString(", Kind: schema.RelationshipBelongsTo, Columns: ")
		writeStringLiteralSlice(source, relationship.Columns)
		if relationship.ReferencedSchema != "" {
			source.WriteString(", ReferencedSchema: ")
			source.WriteString(quote(relationship.ReferencedSchema))
		}
		source.WriteString(", ReferencedTable: ")
		source.WriteString(quote(relationship.ReferencedTable))
		source.WriteString(", ReferencedColumns: ")
		writeStringLiteralSlice(source, relationship.ReferencedColumns)
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeColumns(source *bytes.Buffer, columns []schema.Column, indent string) {
	if len(columns) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Columns: []schema.Column{\n")
	for _, column := range columns {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(column.Name))
		source.WriteString(", Type: ")
		source.WriteString(columnTypeLiteral(column.Type))
		if column.Nullable {
			source.WriteString(", Nullable: true")
		}
		if column.Default != "" {
			source.WriteString(", Default: ")
			source.WriteString(quote(column.Default))
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeStrings(source *bytes.Buffer, values []string, indent string, field string) {
	if len(values) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString(field)
	source.WriteString(": []string{")
	for index, value := range values {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(quote(value))
	}
	source.WriteString("},\n")
}

func writeUniqueConstraints(source *bytes.Buffer, constraints []schema.UniqueConstraint, indent string) {
	if len(constraints) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("UniqueConstraints: []schema.UniqueConstraint{\n")
	for _, constraint := range constraints {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(constraint.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, constraint.Columns)
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeChecks(source *bytes.Buffer, checks []schema.CheckConstraint, indent string) {
	if len(checks) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Checks: []schema.CheckConstraint{\n")
	for _, check := range checks {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(check.Name))
		source.WriteString(", Expression: ")
		source.WriteString(quote(check.Expression))
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeIndexes(source *bytes.Buffer, indexes []schema.Index, indent string) {
	if len(indexes) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Indexes: []schema.Index{\n")
	for _, index := range indexes {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(index.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, index.Columns)
		if index.Unique {
			source.WriteString(", Unique: true")
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeForeignKeys(source *bytes.Buffer, keys []schema.ForeignKey, indent string) {
	if len(keys) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("ForeignKeys: []schema.ForeignKey{\n")
	for _, key := range keys {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(key.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, key.Columns)
		if key.ReferencedSchema != "" {
			source.WriteString(", ReferencedSchema: ")
			source.WriteString(quote(key.ReferencedSchema))
		}
		source.WriteString(", ReferencedTable: ")
		source.WriteString(quote(key.ReferencedTable))
		source.WriteString(", ReferencedColumns: ")
		writeStringLiteralSlice(source, key.ReferencedColumns)
		if key.OnDelete != "" {
			source.WriteString(", OnDelete: ")
			source.WriteString(referenceActionConstant(key.OnDelete))
		}
		if key.OnUpdate != "" {
			source.WriteString(", OnUpdate: ")
			source.WriteString(referenceActionConstant(key.OnUpdate))
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeStringLiteralSlice(source *bytes.Buffer, values []string) {
	source.WriteString("[]string{")
	for index, value := range values {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(quote(value))
	}
	source.WriteByte('}')
}

func writeField(source *bytes.Buffer, indent string, name string, value string) {
	source.WriteString(indent)
	source.WriteString(name)
	source.WriteString(": ")
	source.WriteString(value)
	source.WriteString(",\n")
}

func columnTypeLiteral(columnType schema.ColumnType) string {
	switch typed := columnType.(type) {
	case schema.BooleanType:
		return "schema.BooleanType{}"
	case schema.IntegerType:
		if typed.Unsigned {
			return "schema.IntegerType{Unsigned: true}"
		}
		return "schema.IntegerType{}"
	case schema.FloatType:
		return "schema.FloatType{}"
	case schema.TextType:
		return "schema.TextType{}"
	case schema.BytesType:
		return "schema.BytesType{}"
	case schema.TimeType:
		return "schema.TimeType{}"
	case schema.JSONType:
		return "schema.JSONType{}"
	case schema.UUIDType:
		return "schema.UUIDType{}"
	case schema.DecimalType:
		result := "schema.DecimalType{Precision: " + strconv.Itoa(typed.Precision)
		if scale, stated := typed.Scale.Value(); stated {
			result += ", Scale: schema.NewDecimalScale(" + strconv.Itoa(scale) + ")"
		}
		return result + "}"
	default:
		return "schema.ColumnType(nil)"
	}
}

func referenceActionConstant(action schema.ReferenceAction) string {
	switch action {
	case schema.ReferenceActionNoAction:
		return "schema.ReferenceActionNoAction"
	case schema.ReferenceActionRestrict:
		return "schema.ReferenceActionRestrict"
	case schema.ReferenceActionCascade:
		return "schema.ReferenceActionCascade"
	case schema.ReferenceActionSetNull:
		return "schema.ReferenceActionSetNull"
	case schema.ReferenceActionSetDefault:
		return "schema.ReferenceActionSetDefault"
	default:
		return "schema.ReferenceAction(" + quote(string(action)) + ")"
	}
}

func quote(value string) string {
	return strconv.Quote(value)
}
