// Package generate creates deterministic Go source from schema descriptors.
package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/lestrrat-go/rasql/schema"
)

// reservedFieldNames holds the identifiers a generated table type already uses.
// A column whose generated field name lands on one of them is rejected, because
// the field would shadow the embedded rasql.Table or its methods, or collide
// with a mapping method declared on the row type.
var reservedFieldNames = map[string]struct{}{
	"As":               {},
	"Column":           {},
	"ColumnValue":      {},
	"DecodeRow":        {},
	"QueryTable":       {},
	"ScanColumns":      {},
	"ScanDestinations": {},
	"ScanRow":          {},
	"Table":            {},
	"tableRow":         {},
}

// ValidateSchema checks whether packageName and tables can produce Go source.
// It checks names across all tables, so callers that generate one file per
// table can still reject collisions between those files before writing any.
func ValidateSchema(packageName string, tables ...schema.Table) error {
	_, err := prepareSchema(packageName, tables)
	return err
}

// Schema returns formatted Go source declaring reusable table descriptors in packageName.
func Schema(packageName string, tables ...schema.Table) ([]byte, error) {
	clones, err := prepareSchema(packageName, tables)
	if err != nil {
		return nil, err
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by rasqlgen; DO NOT EDIT.\n\n")
	source.WriteString("package ")
	source.WriteString(packageName)
	source.WriteString("\n\n")
	// An empty schema declares nothing, so importing anything would not compile.
	if len(clones) > 0 {
		source.WriteString("import (\n")
		source.WriteString("\t\"fmt\"\n")
		if containsTime(clones) {
			source.WriteString("\t\"time\"\n")
		}
		source.WriteString("\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql\"\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql/query\"\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql/row\"\n")
		source.WriteString("\t\"github.com/lestrrat-go/rasql/schema\"\n")
		source.WriteString(")\n\n")
	}
	for _, table := range clones {
		writeRowType(&source, table)
		source.WriteString("\n")
		writeRowDecode(&source, table)
		source.WriteString("\n")
		writeRowScan(&source, table)
		source.WriteString("\n")
		writeRowColumnValue(&source, table)
		source.WriteString("\n")
		writeTableType(&source, table)
		source.WriteString("\n")
		writeTableConstructor(&source, table)
		source.WriteString("\n")
		writeTableDescriptor(&source, table)
		source.WriteString("\n")
		writeTableAccessor(&source, table)
		source.WriteString("\n")
		writeTableAs(&source, table)
		source.WriteString("\n")
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generate: format source: %w", err)
	}
	return formatted, nil
}

func prepareSchema(packageName string, tables []schema.Table) ([]schema.Table, error) {
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf("generate: invalid package name %q", packageName)
	}
	clones := make([]schema.Table, len(tables))
	for i, table := range tables {
		if err := table.Validate(); err != nil {
			return nil, fmt.Errorf("generate: table at index %d: %w", i, err)
		}
		clones[i] = table.Clone()
	}
	sort.Slice(clones, func(left, right int) bool {
		return clones[left].Name < clones[right].Name
	})
	if err := validateVariableNames(clones); err != nil {
		return nil, err
	}
	return clones, nil
}

func validateVariableNames(tables []schema.Table) error {
	names := make(map[string]struct{}, len(tables)*2)
	for _, table := range tables {
		variable := variableName(table.Name)
		if variable == "" || !token.IsIdentifier(variable) {
			return fmt.Errorf("generate: table %q cannot become a Go identifier", table.Name)
		}
		if _, exists := names[variable]; exists {
			return fmt.Errorf("generate: table %q duplicates generated name %q", table.Name, variable)
		}
		names[variable] = struct{}{}
		for _, generated := range []string{
			rowTypeName(table.Name),
			tableTypeName(table.Name),
			constructorName(table.Name),
			descriptorName(table.Name),
		} {
			if _, exists := names[generated]; exists {
				return fmt.Errorf("generate: table %q duplicates generated name %q", table.Name, generated)
			}
			names[generated] = struct{}{}
		}

		fields := make(map[string]struct{}, len(table.Columns))
		for _, column := range table.Columns {
			field := goName(column.Name)
			if field == "" || !token.IsIdentifier(field) {
				return fmt.Errorf("generate: column %q on table %q cannot become a Go field", column.Name, table.Name)
			}
			if _, exists := reservedFieldNames[field]; exists {
				return fmt.Errorf("generate: column %q on table %q uses reserved generated field %q", column.Name, table.Name, field)
			}
			if _, exists := fields[field]; exists {
				return fmt.Errorf("generate: column %q on table %q duplicates generated field %q", column.Name, table.Name, field)
			}
			fields[field] = struct{}{}
		}
	}
	return nil
}

// variableName returns the exported Go identifier for a table name. It
// delegates to goName so tables use the same initialism rules as columns:
// a table named api_keys and a column named api_key both spell "API" the
// same way, instead of the table getting a plain "Api".
func variableName(name string) string {
	return goName(name)
}

func rowTypeName(tableName string) string {
	return variableName(tableName) + "Row"
}

// tableTypeName returns the exported wrapper type holding the typed table and
// its column fields.
func tableTypeName(tableName string) string {
	return variableName(tableName) + "Table"
}

// constructorName returns the unexported function binding every column field to
// one table value. As reuses it to rebind columns to an alias.
func constructorName(tableName string) string {
	return "new" + tableTypeName(tableName)
}

// descriptorName returns the unexported variable name backing an accessor.
// Distinctness across accessors is enforced by validateVariableNames, which
// includes descriptor names in its collision set, not by any property of
// this lowering.
func descriptorName(tableName string) string {
	accessor := variableName(tableName)
	if accessor == "" {
		return ""
	}
	runes := []rune(accessor)
	// Find the leading run of uppercase runes: for "APIKeys" that is "APIK",
	// because casing alone cannot tell an initialism from the capital that
	// starts the next word. When the run stops partway through the name, its
	// last rune is that next word's leading capital (the "K" of "Keys") and
	// stays as-is; only the initialism before it gets lowered, so "APIKeys"
	// becomes "apiKeys" rather than "apikeys". A run spanning the whole name
	// (e.g. "ID") or only the first rune (e.g. "Users") has no such word
	// boundary to protect, so it lowers completely.
	end := 0
	for end < len(runes) && unicode.IsUpper(runes[end]) {
		end++
	}
	if end > 1 && end < len(runes) {
		end--
	}
	for index := 0; index < end; index++ {
		runes[index] = unicode.ToLower(runes[index])
	}
	return string(runes) + "Table"
}

func goName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_'
	})
	var result strings.Builder
	for _, part := range parts {
		switch strings.ToLower(part) {
		case "api":
			result.WriteString("API")
		case "id":
			result.WriteString("ID")
		case "json":
			result.WriteString("JSON")
		case "url":
			result.WriteString("URL")
		case "uuid":
			result.WriteString("UUID")
		default:
			for index, r := range part {
				if index == 0 {
					result.WriteRune(unicode.ToUpper(r))
					continue
				}
				result.WriteRune(r)
			}
		}
	}
	return result.String()
}

func containsTime(tables []schema.Table) bool {
	for _, table := range tables {
		for _, column := range table.Columns {
			if column.Type == schema.TypeTime {
				return true
			}
		}
	}
	return false
}

// writeTableType writes the exported wrapper type: the typed table plus one
// query.Column field per column, so a mistyped column name fails to compile.
func writeTableType(source *bytes.Buffer, table schema.Table) {
	typeName := tableTypeName(table.Name)
	source.WriteString("// ")
	source.WriteString(typeName)
	source.WriteString(" is the generated table type for the ")
	source.WriteString(quote(table.Name))
	source.WriteString(" table.\n")
	source.WriteString("type ")
	source.WriteString(typeName)
	source.WriteString(" struct {\n\trasql.Table[")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString("]\n")
	for _, column := range table.Columns {
		source.WriteString("\t")
		source.WriteString(goName(column.Name))
		source.WriteString(" query.Column\n")
	}
	source.WriteString("}\n")
}

// writeTableConstructor writes the function binding every column field to table.
func writeTableConstructor(source *bytes.Buffer, table schema.Table) {
	typeName := tableTypeName(table.Name)
	source.WriteString("func ")
	source.WriteString(constructorName(table.Name))
	source.WriteString("(table rasql.Table[")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString("]) ")
	source.WriteString(typeName)
	source.WriteString(" {\n\treturn ")
	source.WriteString(typeName)
	source.WriteString("{\n\t\tTable: table,\n")
	for _, column := range table.Columns {
		source.WriteString("\t\t")
		source.WriteString(goName(column.Name))
		source.WriteString(": rasql.MustColumn(table, ")
		source.WriteString(quote(column.Name))
		source.WriteString("),\n")
	}
	source.WriteString("\t}\n}\n")
}

// writeTableDescriptor writes the unexported variable holding the table.
// Keeping it unexported means importers reach the table only through the
// accessor and cannot replace it.
func writeTableDescriptor(source *bytes.Buffer, table schema.Table) {
	source.WriteString("var ")
	source.WriteString(descriptorName(table.Name))
	source.WriteString(" = ")
	source.WriteString(constructorName(table.Name))
	source.WriteString("(rasql.MustTable[")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString("](")
	writeTable(source, table, "")
	source.WriteString("))\n")
}

func writeTableAccessor(source *bytes.Buffer, table schema.Table) {
	accessor := variableName(table.Name)
	source.WriteString("// ")
	source.WriteString(accessor)
	source.WriteString(" returns the descriptor for the ")
	source.WriteString(quote(table.Name))
	source.WriteString(" table.\n")
	source.WriteString("func ")
	source.WriteString(accessor)
	source.WriteString("() ")
	source.WriteString(tableTypeName(table.Name))
	source.WriteString(" {\n\treturn ")
	source.WriteString(descriptorName(table.Name))
	source.WriteString("\n}\n")
}

// writeTableAs writes the alias constructor. It rebinds every column through the
// table constructor, so an aliased table qualifies its columns with the alias.
func writeTableAs(source *bytes.Buffer, table schema.Table) {
	typeName := tableTypeName(table.Name)
	source.WriteString("// As returns the table under alias, with every column rebound to it.\n")
	source.WriteString("func (t ")
	source.WriteString(typeName)
	source.WriteString(") As(alias string) (")
	source.WriteString(typeName)
	source.WriteString(", error) {\n")
	source.WriteString("\taliased, err := rasql.As(t.Table, alias)\n")
	source.WriteString("\tif err != nil {\n\t\treturn ")
	source.WriteString(typeName)
	source.WriteString("{}, err\n\t}\n\treturn ")
	source.WriteString(constructorName(table.Name))
	source.WriteString("(aliased), nil\n}\n")
}

func writeRowType(source *bytes.Buffer, table schema.Table) {
	source.WriteString("type ")
	source.WriteString(rowTypeName(table.Name))
	source.WriteString(" struct {\n")
	for _, column := range table.Columns {
		source.WriteString("\t")
		source.WriteString(goName(column.Name))
		source.WriteByte(' ')
		if column.Nullable {
			source.WriteByte('*')
		}
		source.WriteString(rowFieldType(column))
		source.WriteString("\n")
	}
	source.WriteString("}\n")
}

// writeRowDecode writes the row.Decoder implementation. The generator
// already knows which column feeds which field, so the row type states that
// mapping directly instead of restating it as a tag for reflection to parse.
func writeRowDecode(source *bytes.Buffer, table schema.Table) {
	typeName := rowTypeName(table.Name)
	source.WriteString("// DecodeRow assigns each result column to its field.\n")
	source.WriteString("func (r *")
	source.WriteString(typeName)
	source.WriteString(") DecodeRow(src row.Dynamic) error {\n")
	last := len(table.Columns) - 1
	for index, column := range table.Columns {
		if index == last {
			source.WriteString("\treturn ")
			writeRowAssign(source, column)
			source.WriteString("\n")
			break
		}
		source.WriteString("\tif err := ")
		writeRowAssign(source, column)
		source.WriteString("; err != nil {\n\t\treturn err\n\t}\n")
	}
	source.WriteString("}\n")
}

func writeRowAssign(source *bytes.Buffer, column schema.Column) {
	source.WriteString("row.Assign(src, ")
	source.WriteString(quote(column.Name))
	source.WriteString(", &r.")
	source.WriteString(goName(column.Name))
	source.WriteString(")")
}

// writeRowScan writes the direct database/sql scan path and the runtime result
// column mapping path.
func writeRowScan(source *bytes.Buffer, table schema.Table) {
	typeName := rowTypeName(table.Name)
	source.WriteString("// ScanRow scans each result column directly into its field.\n")
	source.WriteString("func (r *")
	source.WriteString(typeName)
	source.WriteString(") ScanRow(src row.ScanSource) error {\n\treturn src.Scan(")
	for index, column := range table.Columns {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString("&r.")
		source.WriteString(goName(column.Name))
	}
	source.WriteString(")\n}\n")

	source.WriteString("\n// ScanDestinations maps result-column names to fields on r.\n")
	source.WriteString("func (r *")
	source.WriteString(typeName)
	source.WriteString(") ScanDestinations(columns []string) ([]any, error) {\n")
	source.WriteString("\tdestinations := make([]any, len(columns))\n")
	for _, column := range table.Columns {
		source.WriteString("\tvar scanned")
		source.WriteString(goName(column.Name))
		source.WriteString(" bool\n")
	}
	source.WriteString("\tvar discard any\n")
	source.WriteString("\tfor index, column := range columns {\n\t\tswitch column {\n")
	for _, column := range table.Columns {
		field := goName(column.Name)
		source.WriteString("\t\tcase ")
		source.WriteString(quote(column.Name))
		source.WriteString(":\n\t\t\tif scanned")
		source.WriteString(field)
		source.WriteString(" {\n\t\t\t\treturn nil, fmt.Errorf(\"duplicate result column %q\", column)\n\t\t\t}\n")
		source.WriteString("\t\t\tscanned")
		source.WriteString(field)
		source.WriteString(" = true\n\t\t\tdestinations[index] = &r.")
		source.WriteString(field)
		source.WriteString("\n")
	}
	source.WriteString("\t\tdefault:\n\t\t\tdestinations[index] = &discard\n\t\t}\n\t}\n")
	source.WriteString("\treturn destinations, nil\n}\n")
}

// writeRowColumnValue writes the rasql.ColumnValuer implementation, which is
// the write-direction counterpart of DecodeRow.
func writeRowColumnValue(source *bytes.Buffer, table schema.Table) {
	typeName := rowTypeName(table.Name)
	source.WriteString("// ColumnValue returns the value of the named column.\n")
	source.WriteString("func (r ")
	source.WriteString(typeName)
	source.WriteString(") ColumnValue(name string) (any, bool) {\n")
	source.WriteString("\tswitch name {\n")
	for _, column := range table.Columns {
		source.WriteString("\tcase ")
		source.WriteString(quote(column.Name))
		source.WriteString(":\n\t\treturn r.")
		source.WriteString(goName(column.Name))
		source.WriteString(", true\n")
	}
	source.WriteString("\t}\n\treturn nil, false\n}\n")
}

// rowFieldType returns the Go type of the row field holding column. It takes
// the whole column because signedness changes the answer: an unsigned integer
// column reaches 18446744073709551615, which int64 cannot hold, so it generates
// a uint64 field. Every other integer column keeps int64.
func rowFieldType(column schema.Column) string {
	if column.Unsigned && column.Type == schema.TypeInteger {
		return "uint64"
	}
	switch column.Type {
	case schema.TypeBoolean:
		return "bool"
	case schema.TypeInteger:
		return "int64"
	case schema.TypeFloat:
		return "float64"
	case schema.TypeText, schema.TypeUUID:
		return "string"
	case schema.TypeBytes, schema.TypeJSON:
		return "[]byte"
	case schema.TypeTime:
		return "time.Time"
	case schema.TypeDecimal:
		return "string"
	default:
		return "any"
	}
}

func writeTable(source *bytes.Buffer, table schema.Table, indent string) {
	source.WriteString("schema.Table{\n")
	writeField(source, indent+"\t", "Name", quote(table.Name))
	writeColumns(source, table.Columns, indent+"\t")
	writeStrings(source, table.PrimaryKey, indent+"\t", "PrimaryKey")
	writeUniqueConstraints(source, table.UniqueConstraints, indent+"\t")
	writeChecks(source, table.Checks, indent+"\t")
	writeIndexes(source, table.Indexes, indent+"\t")
	writeForeignKeys(source, table.ForeignKeys, indent+"\t")
	source.WriteString(indent)
	source.WriteByte('}')
}

func writeColumns(source *bytes.Buffer, columns []schema.Column, indent string) {
	if len(columns) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Columns: []schema.Column{\n")
	for _, column := range columns {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(column.Name))
		source.WriteString(", Type: ")
		source.WriteString(typeConstant(column.Type))
		if column.Nullable {
			source.WriteString(", Nullable: true")
		}
		if column.Unsigned {
			source.WriteString(", Unsigned: true")
		}
		if column.Default != "" {
			source.WriteString(", Default: ")
			source.WriteString(quote(column.Default))
		}
		if column.Precision != 0 {
			source.WriteString(", Precision: ")
			source.WriteString(strconv.Itoa(column.Precision))
		}
		// A stated scale is emitted even when it is zero, because Scale's zero
		// value means no scale was stated and would not validate.
		if scale, stated := column.Scale.Value(); stated {
			source.WriteString(", Scale: schema.NewDecimalScale(")
			source.WriteString(strconv.Itoa(scale))
			source.WriteString(")")
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeStrings(source *bytes.Buffer, values []string, indent string, field string) {
	if len(values) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString(field)
	source.WriteString(": []string{")
	for index, value := range values {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(quote(value))
	}
	source.WriteString("},\n")
}

func writeUniqueConstraints(source *bytes.Buffer, constraints []schema.UniqueConstraint, indent string) {
	if len(constraints) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("UniqueConstraints: []schema.UniqueConstraint{\n")
	for _, constraint := range constraints {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(constraint.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, constraint.Columns)
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeChecks(source *bytes.Buffer, checks []schema.CheckConstraint, indent string) {
	if len(checks) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Checks: []schema.CheckConstraint{\n")
	for _, check := range checks {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(check.Name))
		source.WriteString(", Expression: ")
		source.WriteString(quote(check.Expression))
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeIndexes(source *bytes.Buffer, indexes []schema.Index, indent string) {
	if len(indexes) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("Indexes: []schema.Index{\n")
	for _, index := range indexes {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(index.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, index.Columns)
		if index.Unique {
			source.WriteString(", Unique: true")
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeForeignKeys(source *bytes.Buffer, keys []schema.ForeignKey, indent string) {
	if len(keys) == 0 {
		return
	}
	source.WriteString(indent)
	source.WriteString("ForeignKeys: []schema.ForeignKey{\n")
	for _, key := range keys {
		source.WriteString(indent)
		source.WriteString("\t{Name: ")
		source.WriteString(quote(key.Name))
		source.WriteString(", Columns: ")
		writeStringLiteralSlice(source, key.Columns)
		source.WriteString(", ReferencedTable: ")
		source.WriteString(quote(key.ReferencedTable))
		source.WriteString(", ReferencedColumns: ")
		writeStringLiteralSlice(source, key.ReferencedColumns)
		if key.OnDelete != "" {
			source.WriteString(", OnDelete: ")
			source.WriteString(referenceActionConstant(key.OnDelete))
		}
		if key.OnUpdate != "" {
			source.WriteString(", OnUpdate: ")
			source.WriteString(referenceActionConstant(key.OnUpdate))
		}
		source.WriteString("},\n")
	}
	source.WriteString(indent)
	source.WriteString("},\n")
}

func writeStringLiteralSlice(source *bytes.Buffer, values []string) {
	source.WriteString("[]string{")
	for index, value := range values {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(quote(value))
	}
	source.WriteByte('}')
}

func writeField(source *bytes.Buffer, indent string, name string, value string) {
	source.WriteString(indent)
	source.WriteString(name)
	source.WriteString(": ")
	source.WriteString(value)
	source.WriteString(",\n")
}

func typeConstant(logicalType schema.LogicalType) string {
	switch logicalType {
	case schema.TypeBoolean:
		return "schema.TypeBoolean"
	case schema.TypeInteger:
		return "schema.TypeInteger"
	case schema.TypeFloat:
		return "schema.TypeFloat"
	case schema.TypeText:
		return "schema.TypeText"
	case schema.TypeBytes:
		return "schema.TypeBytes"
	case schema.TypeTime:
		return "schema.TypeTime"
	case schema.TypeJSON:
		return "schema.TypeJSON"
	case schema.TypeUUID:
		return "schema.TypeUUID"
	case schema.TypeDecimal:
		return "schema.TypeDecimal"
	default:
		return "schema.LogicalType(" + quote(string(logicalType)) + ")"
	}
}

func referenceActionConstant(action schema.ReferenceAction) string {
	switch action {
	case schema.ReferenceActionNoAction:
		return "schema.ReferenceActionNoAction"
	case schema.ReferenceActionRestrict:
		return "schema.ReferenceActionRestrict"
	case schema.ReferenceActionCascade:
		return "schema.ReferenceActionCascade"
	case schema.ReferenceActionSetNull:
		return "schema.ReferenceActionSetNull"
	case schema.ReferenceActionSetDefault:
		return "schema.ReferenceActionSetDefault"
	default:
		return "schema.ReferenceAction(" + quote(string(action)) + ")"
	}
}

func quote(value string) string {
	return strconv.Quote(value)
}
