// Code generated by rasqlgen; DO NOT EDIT.

package described

import (
	"context"
	"fmt"
	"github.com/lestrrat-go/rasql"
	"iter"

	"github.com/lestrrat-go/rasql/stmt"
)

func UserReport() stmt.Statement {
	return stmt.New("SELECT u.id AS user_id, p.nickname AS nickname, count(p.user_id) AS profile_count\nFROM users AS u\nLEFT JOIN profiles AS p ON p.user_id = u.id\nGROUP BY u.id, p.nickname\nORDER BY u.id\n")
}

type UserReportRow struct {
	UserID       *int64  `rasql:"user_id"`
	Nickname     *string `rasql:"nickname"`
	ProfileCount int64   `rasql:"profile_count"`
}

func (r *UserReportRow) ScanDestinations(columns []string) ([]any, error) {
	m := rasql.NewScanMask(3)
	dest := make([]any, len(columns))
	for i, name := range columns {
		switch name {
		case "user_id":
			if !m.Mark(0) {
				return nil, fmt.Errorf("duplicate result column")
			}
			dest[i] = &r.UserID
		case "nickname":
			if !m.Mark(1) {
				return nil, fmt.Errorf("duplicate result column")
			}
			dest[i] = &r.Nickname
		case "profile_count":
			if !m.Mark(2) {
				return nil, fmt.Errorf("duplicate result column")
			}
			dest[i] = &r.ProfileCount
		default:
			return nil, fmt.Errorf("unknown result column %s", name)
		}
	}
	return dest, nil
}

func QueryUserReport(ctx context.Context, db rasql.DB) (iter.Seq2[UserReportRow, error], error) {
	return rasql.QueryRendered[UserReportRow](ctx, db, UserReport())
}
