package postgresql

import (
	"fmt"
	"regexp"
	"strings"
	"unicode"
)

type identityMode string

const (
	identityAlways    identityMode = "GENERATED ALWAYS AS IDENTITY"
	identityByDefault identityMode = "GENERATED BY DEFAULT AS IDENTITY"
)

type identityKey struct{ table, column string }
type identityFacts map[identityKey]identityMode
type referenceAction string

const (
	referenceNoAction   referenceAction = "NO ACTION"
	referenceRestrict   referenceAction = "RESTRICT"
	referenceCascade    referenceAction = "CASCADE"
	referenceSetNull    referenceAction = "SET NULL"
	referenceSetDefault referenceAction = "SET DEFAULT"
)

type foreignKeyKey struct {
	table, constraint string
	inline            bool
}
type foreignKeyActions struct{ onDelete, onUpdate referenceAction }
type scannedPostgreSQLFacts struct {
	identities  identityFacts
	foreignKeys map[foreignKeyKey]foreignKeyActions
}

func identifierKey(raw string) string {
	raw = strings.TrimSpace(raw)
	if len(raw) >= 2 && raw[0] == '"' && raw[len(raw)-1] == '"' {
		return fmt.Sprintf("%d:%s", len(raw)-2, strings.ReplaceAll(raw[1:len(raw)-1], `""`, `"`))
	}
	return fmt.Sprintf("%d:%s", len(raw), strings.ToLower(raw))
}

func scanPostgreSQLClauses(source string) (string, scannedPostgreSQLFacts, error) {
	stripped, err := stripIdentityClauses(source)
	facts := scannedPostgreSQLFacts{identities: make(identityFacts), foreignKeys: make(map[foreignKeyKey]foreignKeyActions)}
	if err != nil {
		return stripped, facts, err
	}
	tableMatch := regexp.MustCompile(`(?is)CREATE\s+TABLE\s+((?:"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)(?:\s*\.\s*(?:"[^"]+"|[A-Za-z_][A-Za-z0-9_]*))?)\s*\(`).FindStringSubmatch(source)
	tableKey := ""
	if len(tableMatch) > 1 {
		for _, part := range strings.Split(tableMatch[1], ".") {
			tableKey += identifierKey(strings.TrimSpace(part))
		}
	}
	foreignKeyPattern := regexp.MustCompile(`(?is)CONSTRAINT\s+([A-Za-z_][A-Za-z0-9_]*|"[^"]+")`)
	positions := foreignKeyPattern.FindAllStringSubmatchIndex(source, -1)
	for index, match := range positions {
		end := len(source)
		if index+1 < len(positions) {
			end = positions[index+1][0]
		}
		segment := source[match[0]:end]
		if !strings.Contains(strings.ToUpper(segment), "FOREIGN KEY") {
			continue
		}
		actions := foreignKeyActions{onDelete: referenceNoAction, onUpdate: referenceNoAction}
		deleteMatch := regexp.MustCompile(`(?is)ON\s+DELETE\s+(CASCADE|RESTRICT|SET\s+NULL|SET\s+DEFAULT|NO\s+ACTION)`).FindStringSubmatch(segment)
		updateMatch := regexp.MustCompile(`(?is)ON\s+UPDATE\s+(CASCADE|RESTRICT|SET\s+NULL|SET\s+DEFAULT|NO\s+ACTION)`).FindStringSubmatch(segment)
		if len(deleteMatch) > 1 {
			actions.onDelete = referenceAction(strings.ToUpper(deleteMatch[1]))
		}
		if len(updateMatch) > 1 {
			actions.onUpdate = referenceAction(strings.ToUpper(updateMatch[1]))
		}
		facts.foreignKeys[foreignKeyKey{table: tableKey, constraint: identifierKey(source[match[2]:match[3]])}] = actions
	}
	upper := strings.ToUpper(source)
	for position := strings.Index(upper, "CREATE TABLE"); position >= 0; {
		rest := source[position+len("CREATE TABLE"):]
		open := strings.IndexByte(rest, '(')
		if open < 0 {
			break
		}
		body := rest[open+1:]
		identity := strings.Index(strings.ToUpper(body), "GENERATED ALWAYS AS IDENTITY")
		mode := identityAlways
		if identity < 0 {
			identity = strings.Index(strings.ToUpper(body), "GENERATED BY DEFAULT AS IDENTITY")
			mode = identityByDefault
		}
		if identity >= 0 {
			columnText := strings.TrimSpace(body[:identity])
			if comma := strings.LastIndexByte(columnText, ','); comma >= 0 {
				columnText = columnText[comma+1:]
			}
			column := strings.Fields(columnText)
			if len(column) > 0 {
				facts.identities[identityKey{table: tableKey, column: identifierKey(column[0])}] = mode
			}
		}
		next := strings.Index(strings.ToUpper(body), "CREATE TABLE")
		if next < 0 {
			break
		}
		position += open + 1 + next
	}
	return stripped, facts, nil
}

func stripIdentityClauses(source string) (string, error) {
	result := []byte(source)
	depth, inCreateTable := 0, false
	for index := 0; index < len(source); {
		if source[index] == '-' && index+1 < len(source) && source[index+1] == '-' {
			index = skipLine(source, index)
			continue
		}
		if source[index] == '/' && index+1 < len(source) && source[index+1] == '*' {
			index = skipBlock(source, index)
			continue
		}
		if strings.ContainsRune("'\"`", rune(source[index])) {
			index = skipQuote(source, index, source[index])
			continue
		}
		if source[index] == '$' {
			if end := skipDollar(source, index); end > index {
				index = end
				continue
			}
		}
		if source[index] == '(' {
			depth++
			index++
			continue
		}
		if source[index] == ')' {
			if depth > 0 {
				depth--
			}
			index++
			continue
		}
		if !wordStart(source[index]) {
			index++
			continue
		}
		start, end := word(source, index)
		if strings.EqualFold(source[start:end], "CREATE") {
			inCreateTable = strings.EqualFold(nextWord(source, end), "TABLE")
		}
		if inCreateTable && depth > 0 && strings.EqualFold(source[start:end], "GENERATED") {
			clauseEnd, ok := identityEnd(source, end)
			if ok {
				if next := spaces(source, clauseEnd); next < len(source) && source[next] == '(' {
					return "", fmt.Errorf("postgresql schema: identity option lists require a manual migration")
				}
				for offset := start; offset < clauseEnd; offset++ {
					if result[offset] != '\n' && result[offset] != '\r' {
						result[offset] = ' '
					}
				}
				index = clauseEnd
				continue
			}
		}
		index = end
	}
	actionPattern := regexp.MustCompile(`(?is)\bON\s+(?:DELETE|UPDATE)\s+(?:NO\s+ACTION|CASCADE|RESTRICT|SET\s+(?:NULL|DEFAULT))`)
	for _, match := range actionPattern.FindAllStringIndex(source, -1) {
		for offset := match[0]; offset < match[1]; offset++ {
			if result[offset] != '\n' && result[offset] != '\r' {
				result[offset] = ' '
			}
		}
	}
	return string(result), nil
}

func identityEnd(source string, index int) (int, bool) {
	words := []string{"ALWAYS", "AS", "IDENTITY"}
	if strings.EqualFold(nextWord(source, index), "BY") {
		words = []string{"BY", "DEFAULT", "AS", "IDENTITY"}
	}
	for _, expected := range words {
		index = spaces(source, index)
		start, end := word(source, index)
		if !strings.EqualFold(source[start:end], expected) {
			return index, false
		}
		index = end
	}
	return index, true
}
func nextWord(source string, index int) string {
	index = spaces(source, index)
	start, end := word(source, index)
	return source[start:end]
}
func word(source string, index int) (int, int) {
	start := index
	for index < len(source) && (unicode.IsLetter(rune(source[index])) || unicode.IsDigit(rune(source[index])) || source[index] == '_') {
		index++
	}
	return start, index
}
func wordStart(value byte) bool { return unicode.IsLetter(rune(value)) || value == '_' }
func spaces(source string, index int) int {
	for index < len(source) && unicode.IsSpace(rune(source[index])) {
		index++
	}
	return index
}
func skipLine(source string, index int) int {
	for index < len(source) && source[index] != '\n' {
		index++
	}
	return index
}
func skipBlock(source string, index int) int {
	index += 2
	for index+1 < len(source) && source[index:index+2] != "*/" {
		index++
	}
	if index+1 < len(source) {
		index += 2
	}
	return index
}
func skipQuote(source string, index int, quote byte) int {
	index++
	for index < len(source) {
		if source[index] == quote {
			if index+1 < len(source) && source[index+1] == quote {
				index += 2
				continue
			}
			return index + 1
		}
		index++
	}
	return index
}
func skipDollar(source string, index int) int {
	end := strings.IndexByte(source[index+1:], '$')
	if end < 0 {
		return 0
	}
	tag := source[index : index+end+2]
	close := strings.Index(source[index+end+2:], tag)
	if close < 0 {
		return 0
	}
	return index + end + 2 + close + len(tag)
}
