package postgresql

import (
	"reflect"
	"strings"
	"testing"

	pgquery "github.com/lestrrat-go/rasql-pg/query"
	"github.com/lestrrat-go/rasql/migrate/diff"
	"github.com/lestrrat-go/rasql/sqltext"
)

func TestScanPostgreSQLClauses(t *testing.T) {
	source := "CREATE TABLE tasks (id bigint GENERATED ALWAYS AS IDENTITY, note text DEFAULT 'GENERATED ALWAYS AS IDENTITY');"
	stripped, facts, err := scanPostgreSQLClauses(source)
	if err != nil {
		t.Fatal(err)
	}
	if len(stripped) != len(source) || !strings.Contains(stripped, "'GENERATED ALWAYS AS IDENTITY'") {
		t.Fatal("scanner changed opaque source")
	}
	table := facts.tables["5:tasks"]
	if table.identities["2:id"] != identityAlways {
		t.Fatalf("identity facts: %#v", table.identities)
	}
	if strings.Contains(stripped[:strings.Index(stripped, ",")], "GENERATED") {
		t.Fatal("identity clause was not removed")
	}
}

func TestScanPostgreSQLClausesFullFactMatrix(t *testing.T) {
	tests := []struct {
		name    string
		source  string
		facts   scannedPostgreSQLFacts
		removed []string
	}{
		{"always", "CREATE TABLE tasks (id bigint GENERATED ALWAYS AS IDENTITY);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"5:tasks": {identities: map[string]identityMode{"2:id": identityAlways}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}}}, []string{"GENERATED ALWAYS AS IDENTITY"}},
		{"default", "CREATE TABLE tasks (id bigint GENERATED BY DEFAULT AS IDENTITY);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"5:tasks": {identities: map[string]identityMode{"2:id": identityByDefault}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}}}, []string{"GENERATED BY DEFAULT AS IDENTITY"}},
		{"two columns", "CREATE TABLE t (a bigint GENERATED ALWAYS AS IDENTITY, b bigint GENERATED BY DEFAULT AS IDENTITY);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"1:t": {identities: map[string]identityMode{"1:a": identityAlways, "1:b": identityByDefault}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}}}, []string{"GENERATED ALWAYS AS IDENTITY", "GENERATED BY DEFAULT AS IDENTITY"}},
		{"multiple tables", "CREATE TABLE a (id bigint GENERATED ALWAYS AS IDENTITY); CREATE TABLE b (id bigint GENERATED BY DEFAULT AS IDENTITY);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"1:a": {identities: map[string]identityMode{"2:id": identityAlways}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}, "1:b": {identities: map[string]identityMode{"2:id": identityByDefault}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}}}, []string{"GENERATED ALWAYS AS IDENTITY", "GENERATED BY DEFAULT AS IDENTITY"}},
		{"canonical quoted distinction", "CREATE TABLE APP.\"Tasks\" (ID bigint GENERATED ALWAYS AS IDENTITY, \"ID\" bigint GENERATED BY DEFAULT AS IDENTITY);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"3:app5:Tasks": {identities: map[string]identityMode{"2:id": identityAlways, "2:ID": identityByDefault}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}}}, []string{"GENERATED ALWAYS AS IDENTITY", "GENERATED BY DEFAULT AS IDENTITY"}},
		{"named foreign key", "CREATE TABLE t (x bigint, CONSTRAINT fk FOREIGN KEY (x) REFERENCES p(id) ON DELETE CASCADE ON UPDATE SET NULL);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"1:t": {identities: map[string]identityMode{}, foreignKeys: map[foreignKeyKey]foreignKeyActions{{table: "1:t", constraint: "2:fk"}: {onDelete: referenceCascade, onUpdate: referenceSetNull}}}}}, []string{"ON DELETE CASCADE", "ON UPDATE SET NULL"}},
		{"inline foreign key", "CREATE TABLE t (x bigint REFERENCES p(id) ON DELETE RESTRICT);", scannedPostgreSQLFacts{tables: map[string]tableFacts{"1:t": {identities: map[string]identityMode{}, foreignKeys: map[foreignKeyKey]foreignKeyActions{{table: "1:t", constraint: "1:x", inline: true}: {onDelete: referenceRestrict, onUpdate: referenceNoAction}}}}}, []string{"ON DELETE RESTRICT"}},
		{"default foreign key", "CREATE TABLE t (x bigint REFERENCES p(id));", scannedPostgreSQLFacts{tables: map[string]tableFacts{"1:t": {identities: map[string]identityMode{}, foreignKeys: map[foreignKeyKey]foreignKeyActions{{table: "1:t", constraint: "1:x", inline: true}: {onDelete: referenceNoAction, onUpdate: referenceNoAction}}}}}, nil},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			stripped, facts, err := scanPostgreSQLClauses(test.source)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(facts, test.facts) {
				t.Fatalf("facts differ: got %#v want %#v", facts, test.facts)
			}
			expected := test.source
			for _, clause := range test.removed {
				expected = strings.Replace(expected, clause, strings.Repeat(" ", len(clause)), 1)
			}
			if stripped != expected {
				t.Fatalf("stripped differs:\ngot  %q\nwant %q", stripped, expected)
			}
		})
	}
}

func TestScanPostgreSQLClausesForeignKeysAndNames(t *testing.T) {
	_, facts, err := scanPostgreSQLClauses("CREATE TABLE APP.\"Tasks\" (\"ID\" bigint GENERATED BY DEFAULT AS IDENTITY, x bigint REFERENCES p(id) ON DELETE RESTRICT);")
	if err != nil {
		t.Fatal(err)
	}
	if facts.tables["3:app5:Tasks"].identities["2:ID"] != identityByDefault {
		t.Fatal("quoted identity was not retained")
	}
	fk := facts.tables["3:app5:Tasks"].foreignKeys[foreignKeyKey{"3:app5:Tasks", "1:x", true}]
	if fk.onDelete != referenceRestrict || fk.onUpdate != referenceNoAction {
		t.Fatalf("foreign key facts: %#v", fk)
	}
}

func TestScanPostgreSQLClausesRejectsIdentityOptions(t *testing.T) {
	_, _, err := scanPostgreSQLClauses("CREATE TABLE tasks (id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1));")
	if err == nil || !strings.Contains(err.Error(), "option lists") {
		t.Fatal("identity options were accepted")
	}
}

func TestScanPostgreSQLClausesOpaqueContextsAndMultipleTables(t *testing.T) {
	source := "CREATE TABLE a (\r\n" +
		"  id bigint GENERATED ALWAYS AS IDENTITY,\r\n" +
		"  single_text text DEFAULT 'CREATE TABLE GENERATED ALWAYS AS IDENTITY REFERENCES p(id) ON DELETE CASCADE',\r\n" +
		"  empty_dollar text DEFAULT $$$$,\r\n" +
		"  tagged_dollar text DEFAULT $tag$CREATE TABLE GENERATED BY DEFAULT AS IDENTITY ON UPDATE SET NULL$tag$,\r\n" +
		"  \"CREATE TABLE GENERATED FOREIGN KEY ON DELETE\" text,\r\n" +
		"  checked int DEFAULT ((1 + (2))),\r\n" +
		"  CONSTRAINT ck CHECK ((checked > 0) AND ('REFERENCES q(id) ON DELETE RESTRICT' <> '')),\r\n" +
		"  x bigint REFERENCES p(id) ON DELETE CASCADE -- GENERATED ALWAYS AS IDENTITY ON UPDATE SET NULL\r\n" +
		"  /* CREATE TABLE hidden (z int GENERATED ALWAYS AS IDENTITY); FOREIGN KEY ON DELETE */\r\n" +
		");\r\n" +
		"CREATE TABLE b (id bigint GENERATED BY DEFAULT AS IDENTITY);\r\n"
	stripped, facts, err := scanPostgreSQLClauses(source)
	if err != nil {
		t.Fatal(err)
	}
	wantFacts := scannedPostgreSQLFacts{tables: map[string]tableFacts{
		"1:a": {identities: map[string]identityMode{"2:id": identityAlways}, foreignKeys: map[foreignKeyKey]foreignKeyActions{{table: "1:a", constraint: "1:x", inline: true}: {onDelete: referenceCascade, onUpdate: referenceNoAction}}},
		"1:b": {identities: map[string]identityMode{"2:id": identityByDefault}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}},
	}}
	wantStripped := source
	for _, marker := range []struct{ before, clause string }{{"  id bigint ", "GENERATED ALWAYS AS IDENTITY"}, {"  x bigint REFERENCES p(id) ", "ON DELETE CASCADE"}, {"CREATE TABLE b (id bigint ", "GENERATED BY DEFAULT AS IDENTITY"}} {
		at := strings.Index(wantStripped, marker.before) + len(marker.before)
		wantStripped = wantStripped[:at] + strings.Repeat(" ", len(marker.clause)) + wantStripped[at+len(marker.clause):]
	}
	if stripped != wantStripped {
		t.Fatalf("stripped differs:\ngot  %q\nwant %q", stripped, wantStripped)
	}
	if !reflect.DeepEqual(facts, wantFacts) {
		t.Fatalf("facts differ: got %#v want %#v", facts, wantFacts)
	}
	for index, value := range []byte(source) {
		if value == '\r' || value == '\n' {
			if stripped[index] != value {
				t.Fatalf("line ending changed at byte %d", index)
			}
		}
	}
}

func TestScanPostgreSQLClausesRejectsDuplicateActionsAndUnterminatedInput(t *testing.T) {
	cases := []string{
		"CREATE TABLE t (x int REFERENCES p(id) ON DELETE NO ACTION ON DELETE CASCADE);",
		"CREATE TABLE t (x int REFERENCES p(id) ON UPDATE NO ACTION ON UPDATE CASCADE);",
		"CREATE TABLE t (x int DEFAULT 'unterminated);",
		"CREATE TABLE t (x int DEFAULT $$unterminated);",
		"CREATE TABLE t (x int /* unterminated);",
		"CREATE TABLE t (x int",
		"CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY GENERATED BY DEFAULT AS IDENTITY);",
		"CREATE TABLE t (x int REFERENCES p(id) ON DELETE LATER);",
		"CREATE TABLE t (x int REFERENCES p(id) ON DELETE);",
		"CREATE TABLE t (x int, FOREIGN KEY (x) REFERENCES p(id) ON DELETE CASCADE);",
		"CREATE TABLE t (\"unterminated int);",
	}
	for _, source := range cases {
		if _, _, err := scanPostgreSQLClauses(source); err == nil {
			t.Errorf("source was accepted: %q", source)
		}
	}
}

func TestScanPostgreSQLClausesPreservesCRLF(t *testing.T) {
	source := "CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY, x int REFERENCES p(id) ON DELETE CASCADE ON UPDATE SET NULL);\r\n"
	stripped, _, err := scanPostgreSQLClauses(source)
	if err != nil {
		t.Fatal(err)
	}
	if len(stripped) != len(source) || stripped[strings.Index(source, "\r\n"):strings.Index(source, "\r\n")+2] != "\r\n" {
		t.Fatal("CRLF offsets changed")
	}
}

func TestScanPostgreSQLClausesKeepsParserLineAfterRemovedFacts(t *testing.T) {
	source := "CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY);\r\nCREATE TABLE broken (x int @);\r\n"
	stripped, _, err := scanPostgreSQLClauses(source)
	if err != nil {
		t.Fatal(err)
	}
	if len(stripped) != len(source) {
		t.Fatal("scanner changed source length")
	}
	for index, value := range []byte(source) {
		if value == '\r' || value == '\n' {
			if stripped[index] != value {
				t.Fatalf("line ending changed at byte %d", index)
			}
		}
	}
	if _, err := pgquery.Parse(stripped); err == nil || !strings.Contains(err.Error(), "byte 85") {
		t.Fatalf("parser error lost source line: %v", err)
	}
}

func TestPostgreSQLFactAttachmentRoutesTablesAndRejectsMismatches(t *testing.T) {
	snapshot, err := New().Parse([]diff.Source{{Path: "schema.sql", SQL: sqltext.Text([]byte("CREATE TABLE a (id bigint GENERATED ALWAYS AS IDENTITY); CREATE TABLE b (id bigint GENERATED BY DEFAULT AS IDENTITY);"))}})
	if err != nil {
		t.Fatal(err)
	}
	tables := snapshot.(*schemaSnapshot).tables
	if tables["1:a"].identities["2:id"] != identityAlways || tables["1:b"].identities["2:id"] != identityByDefault {
		t.Fatalf("facts attached to wrong tables: %#v", tables)
	}
	if len(tables["1:a"].foreignKeys) != 0 || len(tables["1:b"].foreignKeys) != 0 {
		t.Fatal("unexpected foreign-key facts")
	}
	parsed, err := pgquery.Parse("CREATE TABLE t (id int);")
	if err != nil {
		t.Fatal(err)
	}
	table := parsed.Statements[0].(*pgquery.CreateTableStatement)
	if _, _, err := attachFacts("mismatch.sql", table, "1:t", tableFacts{identities: map[string]identityMode{"2:missing": identityAlways}, foreignKeys: map[foreignKeyKey]foreignKeyActions{}}); err == nil {
		t.Fatal("unmatched identity was accepted")
	}
	if _, _, err := attachFacts("mismatch.sql", table, "1:t", tableFacts{identities: map[string]identityMode{}, foreignKeys: map[foreignKeyKey]foreignKeyActions{{table: "1:t", constraint: "2:missing"}: {onDelete: referenceNoAction, onUpdate: referenceNoAction}}}); err == nil {
		t.Fatal("unmatched foreign key was accepted")
	}
	ambiguous, err := pgquery.Parse("CREATE TABLE t (x int REFERENCES p(id), CONSTRAINT fk FOREIGN KEY (x) REFERENCES p(id));")
	if err != nil {
		t.Fatal(err)
	}
	if _, _, err := attachFacts("mismatch.sql", ambiguous.Statements[0].(*pgquery.CreateTableStatement), "1:t", tableFacts{identities: map[string]identityMode{}, foreignKeys: map[foreignKeyKey]foreignKeyActions{{table: "1:t", constraint: "1:x", inline: true}: {}}}); err == nil {
		t.Fatal("ambiguous inline reference was accepted")
	}
	if _, err := pgquery.Parse("CREATE TABLE t (x int"); err == nil {
		t.Fatal("parser accepted malformed source")
	}
	quotedSource := `CREATE TABLE APP."Tasks" (
  ID bigint GENERATED ALWAYS AS IDENTITY,
  "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
  x bigint REFERENCES p(id) ON DELETE RESTRICT,
  CONSTRAINT "FK" FOREIGN KEY (x) REFERENCES q(id) ON UPDATE CASCADE
);
CREATE TABLE app.tasks (id bigint);`
	quotedSnapshot, err := New().Parse([]diff.Source{{Path: "quoted.sql", SQL: sqltext.Text([]byte(quotedSource))}})
	if err != nil {
		t.Fatal(err)
	}
	tables = quotedSnapshot.(*schemaSnapshot).tables
	if len(tables) != 2 {
		t.Fatalf("got %d tables", len(tables))
	}
	wantQuotedIdentities := map[string]identityMode{"2:id": identityAlways, "2:ID": identityByDefault}
	wantQuotedForeignKeys := map[foreignKeyKey]foreignKeyActions{
		{table: "3:app5:Tasks", constraint: "1:x", inline: true}:   {onDelete: referenceRestrict, onUpdate: referenceNoAction},
		{table: "3:app5:Tasks", constraint: "2:FK", inline: false}: {onDelete: referenceNoAction, onUpdate: referenceCascade},
	}
	if !reflect.DeepEqual(tables["3:app5:Tasks"].identities, wantQuotedIdentities) || !reflect.DeepEqual(tables["3:app5:Tasks"].foreignKeys, wantQuotedForeignKeys) {
		t.Fatalf("quoted facts differ: %#v", tables["3:app5:Tasks"])
	}
	if !reflect.DeepEqual(tables["3:app5:tasks"].identities, map[string]identityMode{}) || !reflect.DeepEqual(tables["3:app5:tasks"].foreignKeys, map[foreignKeyKey]foreignKeyActions{}) {
		t.Fatalf("folded facts differ: %#v", tables["3:app5:tasks"])
	}
	if err := rejectUnconsumedTables("mismatch.sql", scannedPostgreSQLFacts{tables: map[string]tableFacts{"1:a": {}, "1:b": {}}}, map[string]struct{}{"1:a": {}}); err == nil || !strings.Contains(err.Error(), "mismatch.sql") || !strings.Contains(err.Error(), "1:b") || !strings.Contains(err.Error(), "was not parsed") {
		t.Fatalf("unexpected unconsumed error: %v", err)
	}
}
