package postgresql

import (
	"strings"
	"testing"
)

func TestStripIdentityClausesScansSQLContext(t *testing.T) {
	source := "CREATE TABLE members (id bigint GENERATED ALWAYS AS IDENTITY, note text DEFAULT 'GENERATED ALWAYS AS IDENTITY');"
	stripped, err := stripIdentityClauses(source)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stripped, "GENERATED ALWAYS AS IDENTITY") {
		t.Fatal("quoted identity text was changed")
	}
	if strings.Contains(stripped[:strings.Index(stripped, ",")], "GENERATED") {
		t.Fatal("identity clause was not removed")
	}
	if len(stripped) != len(source) {
		t.Fatal("source offsets changed")
	}
}

func TestStripIdentityClausesRejectsOptionsAndPreservesComments(t *testing.T) {
	_, err := stripIdentityClauses("CREATE TABLE members (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1));")
	if err == nil || !strings.Contains(err.Error(), "option lists") {
		t.Fatal("identity options were accepted")
	}
	source := "CREATE TABLE members (note text DEFAULT $$GENERATED ALWAYS AS IDENTITY$$, id bigint GENERATED ALWAYS AS IDENTITY);"
	stripped, err := stripIdentityClauses(source)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stripped, "$$GENERATED ALWAYS AS IDENTITY$$") {
		t.Fatal("dollar quote was changed")
	}
}
