package rasqlgen

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lestrrat-go/rasql/generate"
	"github.com/lestrrat-go/rasql/internal/schemasource"
	"github.com/stretchr/testify/require"
)

func TestCompactSchemaUpdateOfflineQueryConsumer(t *testing.T) {
	fixture := newCompactWorkflowFixture(t, "user_by_id_gen.go")
	var output, diagnostics bytes.Buffer
	command := fixture.command(t, &output, &diagnostics)

	require.NoError(t, command.run([]string{"schema", "update", "-config", fixture.configPath}), diagnostics.String())
	onlineFiles := snapshotGeneratedFiles(t, fixture.root)
	require.Contains(t, sortedFileNames(onlineFiles), "internal/store/user_by_id_gen.go")
	querySource := string(onlineFiles["internal/store/user_by_id_gen.go"])
	require.Contains(t, querySource, "func UserByID(id int64)")
	require.Contains(t, querySource, "type user_by_idResult struct")
	onlineLock := workflowRead(t, filepath.Join(fixture.root, "rasql.lock.json"))

	writeCompactConsumerModule(t, fixture.root)
	runCompactConsumer(t, fixture.root)

	for name := range onlineFiles {
		require.NoError(t, os.Remove(filepath.Join(fixture.root, filepath.FromSlash(name))))
	}
	poison := &materializationCounters{}
	command.schemaDependencies = func() schemasource.Dependencies {
		poison.provider++
		return poison.dependencies()
	}
	output.Reset()
	diagnostics.Reset()
	require.NoError(t, command.run([]string{"generate", "-config", fixture.configPath}), diagnostics.String())
	require.Equal(t, 0, poison.provider)
	require.Equal(t, 0, poison.factory)
	require.Equal(t, 0, poison.opener)
	require.Equal(t, 0, poison.process)
	require.Equal(t, 0, poison.analyzer)
	require.Equal(t, onlineFiles, snapshotGeneratedFiles(t, fixture.root))
	require.Equal(t, onlineLock, workflowRead(t, filepath.Join(fixture.root, "rasql.lock.json")))

	output.Reset()
	diagnostics.Reset()
	require.NoError(t, command.run([]string{"check", "-config", fixture.configPath}), diagnostics.String())
	require.Equal(t, onlineFiles, snapshotGeneratedFiles(t, fixture.root))
	require.Equal(t, onlineLock, workflowRead(t, filepath.Join(fixture.root, "rasql.lock.json")))
}

func TestCompactTypedQueryPlanOwnsExistingFiles(t *testing.T) {
	fixture := newCompactWorkflowFixture(t, "user_by_id_gen.go")
	var output, diagnostics bytes.Buffer
	command := fixture.command(t, &output, &diagnostics)
	require.NoError(t, command.run([]string{"schema", "update", "-config", fixture.configPath}), diagnostics.String())

	queryPath := filepath.Join(fixture.root, "internal", "store", "user_by_id_gen.go")
	queryBytes := workflowRead(t, queryPath)
	require.NoError(t, os.WriteFile(queryPath, append(queryBytes, []byte("\n// stale\n")...), 0o600))
	output.Reset()
	diagnostics.Reset()
	err := command.run([]string{"check", "-config", fixture.configPath})
	require.ErrorIs(t, err, generate.ErrStale)
	require.Equal(t, append(queryBytes, []byte("\n// stale\n")...), workflowRead(t, queryPath))

	require.NoError(t, os.WriteFile(queryPath, queryBytes, 0o600))
	orphanPath := filepath.Join(fixture.root, "internal", "store", "old_gen.go")
	require.NoError(t, os.WriteFile(orphanPath, []byte("// Code generated by rasqlgen; DO NOT EDIT.\n\npackage store\n"), 0o600))
	output.Reset()
	diagnostics.Reset()
	err = command.run([]string{"check", "-config", fixture.configPath})
	require.ErrorIs(t, err, generate.ErrStale)
	require.Contains(t, err.Error(), "old_gen.go")

	output.Reset()
	diagnostics.Reset()
	require.NoError(t, command.run([]string{"generate", "-config", fixture.configPath}), diagnostics.String())
	require.NoFileExists(t, orphanPath)

	foreignPath := filepath.Join(fixture.root, "internal", "store", "foreign.go")
	require.NoError(t, os.WriteFile(foreignPath, []byte("package foreign\n"), 0o600))
	beforeFiles := snapshotGeneratedFiles(t, fixture.root)
	beforeLock := workflowRead(t, filepath.Join(fixture.root, "rasql.lock.json"))
	output.Reset()
	diagnostics.Reset()
	err = command.run([]string{"generate", "-config", fixture.configPath})
	require.Error(t, err)
	require.Contains(t, err.Error(), "foreign.go")
	require.Equal(t, beforeFiles, snapshotGeneratedFiles(t, fixture.root))
	require.Equal(t, beforeLock, workflowRead(t, filepath.Join(fixture.root, "rasql.lock.json")))
}

func TestCompactTypedQueryCollisionStopsBeforePublication(t *testing.T) {
	fixture := newCompactWorkflowFixture(t, "users_gen.go")
	var output, diagnostics bytes.Buffer
	command := fixture.command(t, &output, &diagnostics)
	err := command.run([]string{"schema", "update", "-config", fixture.configPath})
	require.Error(t, err)
	require.Contains(t, err.Error(), "Go model failed")
	require.NoDirExists(t, filepath.Join(fixture.root, "internal", "store"))
	require.NoFileExists(t, filepath.Join(fixture.root, "rasql.lock.json"))
	require.NoFileExists(t, filepath.Join(fixture.root, pendingMarkerName))
}

type compactWorkflowFixture struct {
	root, configPath, queryPath string
}

func newCompactWorkflowFixture(t *testing.T, queryOutput string) compactWorkflowFixture {
	t.Helper()
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, "migrations"), 0o700))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "queries"), 0o700))
	query := "SELECT id, email FROM users WHERE id = {{bind \"id\" users.id}}\n"
	queryPath := filepath.Join(root, "queries", "user_by_id.sql")
	require.NoError(t, os.WriteFile(queryPath, []byte(query), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(root, "migrations", "001_init.sql"), []byte("CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL);\n"), 0o600))
	config := map[string]any{
		"engine":  map[string]string{"dialect": "sqlite", "profile": "sqlite-3.35"},
		"schema":  map[string]any{"kind": "migrations", "identity": "compact-workflow", "paths": []string{"migrations/*.sql"}},
		"package": "store", "output": "internal/store", "emitter": "compact",
		"queries": []any{map[string]any{
			"id": "user_by_id", "input": "queries/user_by_id.sql", "engine": "sqlite", "function": "UserByID", "output": queryOutput,
			"operation": "select", "cardinality": "one",
			"parameters": []any{map[string]any{"name": "id", "scalar": "integer", "nullable": false}},
			"results": []any{
				map[string]any{"name": "id", "scalar": "integer", "nullable": false},
				map[string]any{"name": "email", "scalar": "text", "nullable": false},
			},
		}},
	}
	configBytes, err := json.Marshal(config)
	require.NoError(t, err)
	configPath := filepath.Join(root, "rasql.json")
	require.NoError(t, os.WriteFile(configPath, configBytes, 0o600))
	return compactWorkflowFixture{root: root, configPath: configPath, queryPath: queryPath}
}

func (f compactWorkflowFixture) command(t *testing.T, output, diagnostics *bytes.Buffer) *command {
	t.Helper()
	return &command{program: "rasql", output: output, diagnostics: diagnostics, ctx: t.Context()}
}

func writeCompactConsumerModule(t *testing.T, root string) {
	t.Helper()
	repository := repoRoot(t)
	goMod := workflowRead(t, filepath.Join(repository, "go.mod"))
	goMod = []byte(strings.Replace(string(goMod), "module github.com/lestrrat-go/rasql\n", "module example.test/compact-workflow\n", 1))
	goMod = append(goMod, []byte("\nrequire github.com/lestrrat-go/rasql v0.0.0\nreplace github.com/lestrrat-go/rasql => "+filepath.ToSlash(repository)+"\n")...)
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), goMod, 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.sum"), workflowRead(t, filepath.Join(repository, "go.sum")), 0o600))
	consumerDir := filepath.Join(root, "consumer")
	require.NoError(t, os.MkdirAll(consumerDir, 0o700))
	const source = `package consumer_test

import (
	"database/sql"
	"testing"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/dialect"
	store "example.test/compact-workflow/internal/store"
	_ "modernc.org/sqlite"
)

func TestGeneratedCompactQueryExecutes(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil { t.Fatal(err) }
	defer db.Close()
	if _, err = db.ExecContext(t.Context(), "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL); INSERT INTO users VALUES (7, 'ada@example.test')"); err != nil { t.Fatal(err) }
	rdb, err := rasql.New(db, dialect.SQLite())
	if err != nil { t.Fatal(err) }
	profile, err := rasql.EngineProfileFromVersion("sqlite-3.35", 3, 35, 1)
	if err != nil { t.Fatal(err) }
	executor, err := rasql.AsExecutor(rdb, profile)
	if err != nil { t.Fatal(err) }
	query, err := store.UserByID(7)
	if err != nil { t.Fatal(err) }
	row, err := rasql.One(t.Context(), executor, query)
	if err != nil { t.Fatal(err) }
	if row.ID != 7 || row.Email != "ada@example.test" { t.Fatalf("row = %#v", row) }
}
`
	require.NoError(t, os.WriteFile(filepath.Join(consumerDir, "consumer_test.go"), []byte(source), 0o600))
}

func runCompactConsumer(t *testing.T, root string) {
	t.Helper()
	command := exec.CommandContext(t.Context(), "go", "test", "-mod=mod", "./consumer")
	command.Dir = root
	// GOCACHE is deliberately not overridden here: the ambient build cache
	// already holds rasql and its dependencies from the surrounding `go test
	// ./...` run, and a fresh per-call GOCACHE bought no isolation this
	// correctness check needs -- it only forced dependency compilation from
	// scratch on every call.
	command.Env = append(os.Environ(), "GOFLAGS=-buildvcs=false")
	output, err := command.CombinedOutput()
	require.NoError(t, err, "%s", output)
}
