//go:build unix

package rasqlgen

import (
	"io/fs"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"testing"

	"github.com/stretchr/testify/require"
)

// These tests use Unix-only resource limits, signals, and symbolic links.
const generatedSource = "// Code generated by rasqlgen; DO NOT EDIT.\n\npackage generated\n"

func TestWriteGeneratedFilePreservesExistingOutputWhenWriteFails(t *testing.T) {
	directory, err := os.MkdirTemp(".", ".tmp-generated-file-*")
	require.NoError(t, err)
	t.Cleanup(func() {
		require.NoError(t, os.RemoveAll(directory))
	})
	output := filepath.Join(directory, "output_gen.go")
	sentinel := []byte("SENTINEL-DATA-DO-NOT-TRUNCATE")
	require.NoError(t, os.WriteFile(output, sentinel, 0o600))

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGXFSZ)
	t.Cleanup(func() {
		signal.Stop(signals)
	})
	var limit syscall.Rlimit
	require.NoError(t, syscall.Getrlimit(syscall.RLIMIT_FSIZE, &limit))
	original := limit
	limit.Cur = 1
	require.NoError(t, syscall.Setrlimit(syscall.RLIMIT_FSIZE, &limit))
	t.Cleanup(func() {
		require.NoError(t, syscall.Setrlimit(syscall.RLIMIT_FSIZE, &original))
	})

	err = writeGeneratedFile(output, []byte(generatedSource))
	require.Error(t, err)
	got, err := os.ReadFile(output)
	require.NoError(t, err)
	require.Equal(t, sentinel, got)
}

func TestWriteGeneratedFileKeepsOutputModeBits(t *testing.T) {
	for _, tc := range []struct {
		name     string
		existing fs.FileMode
		want     fs.FileMode
	}{
		{name: "new output is created at 0600", want: 0o600},
		{name: "existing 0644 output keeps 0644", existing: 0o644, want: 0o644},
		{name: "existing sticky output keeps the sticky bit", existing: 0o755 | fs.ModeSticky, want: 0o755 | fs.ModeSticky},
		{name: "existing setuid output does not keep setuid", existing: 0o755 | fs.ModeSetuid, want: 0o755},
		{name: "existing setgid output does not keep setgid", existing: 0o755 | fs.ModeSetgid, want: 0o755},
	} {
		t.Run(tc.name, func(t *testing.T) {
			directory, err := os.MkdirTemp(".", ".tmp-generated-file-*")
			require.NoError(t, err)
			t.Cleanup(func() {
				require.NoError(t, os.RemoveAll(directory))
			})
			output := filepath.Join(directory, "output_gen.go")
			if tc.existing != 0 {
				require.NoError(t, os.WriteFile(output, []byte("// stale\n"), tc.existing))
				require.NoError(t, os.Chmod(output, tc.existing))
			}

			require.NoError(t, writeGeneratedFile(output, []byte(generatedSource)))
			info, err := os.Stat(output)
			require.NoError(t, err)
			require.Equal(t, tc.want, info.Mode()&(fs.ModePerm|fs.ModeSticky|fs.ModeSetuid|fs.ModeSetgid))
		})
	}
}

func TestWriteGeneratedFileRejectsDirectory(t *testing.T) {
	directory, err := os.MkdirTemp(".", ".tmp-generated-file-*")
	require.NoError(t, err)
	t.Cleanup(func() {
		require.NoError(t, os.RemoveAll(directory))
	})
	output := filepath.Join(directory, "outdir")
	require.NoError(t, os.Mkdir(output, 0o700))

	err = writeGeneratedFile(output, []byte(generatedSource))
	require.ErrorContains(t, err, "is a directory")
	require.Empty(t, mustReadDir(t, output))
}

func TestWriteGeneratedFileRejectsSymlinkToDirectory(t *testing.T) {
	directory, err := os.MkdirTemp(".", ".tmp-generated-file-*")
	require.NoError(t, err)
	t.Cleanup(func() {
		require.NoError(t, os.RemoveAll(directory))
	})
	target := filepath.Join(directory, "target")
	require.NoError(t, os.Mkdir(target, 0o700))
	output := filepath.Join(directory, "output_gen.go")
	require.NoError(t, os.Symlink("target", output))

	err = writeGeneratedFile(output, []byte(generatedSource))
	require.ErrorContains(t, err, "is a directory")
	info, err := os.Lstat(output)
	require.NoError(t, err)
	require.NotZero(t, info.Mode()&fs.ModeSymlink)
	require.Empty(t, mustReadDir(t, target))
}

func TestWriteGeneratedFileWritesThroughOutputSymlink(t *testing.T) {
	directory, err := os.MkdirTemp(".", ".tmp-generated-file-*")
	require.NoError(t, err)
	t.Cleanup(func() {
		require.NoError(t, os.RemoveAll(directory))
	})
	target := filepath.Join(directory, "target_gen.go")
	output := filepath.Join(directory, "output_gen.go")
	require.NoError(t, os.WriteFile(target, []byte("// stale\n"), 0o644))
	require.NoError(t, os.Chmod(target, 0o644))
	require.NoError(t, os.Symlink("target_gen.go", output))

	require.NoError(t, writeGeneratedFile(output, []byte(generatedSource)))
	info, err := os.Lstat(output)
	require.NoError(t, err)
	require.NotZero(t, info.Mode()&fs.ModeSymlink)
	source, err := os.ReadFile(target)
	require.NoError(t, err)
	require.Equal(t, []byte(generatedSource), source)
	info, err = os.Stat(target)
	require.NoError(t, err)
	require.Equal(t, fs.FileMode(0o644), info.Mode().Perm())
}

func TestWriteGeneratedFileRejectsOutputSymlinkCycle(t *testing.T) {
	directory, err := os.MkdirTemp(".", ".tmp-generated-file-*")
	require.NoError(t, err)
	t.Cleanup(func() {
		require.NoError(t, os.RemoveAll(directory))
	})
	output := filepath.Join(directory, "output_gen.go")
	other := filepath.Join(directory, "other_gen.go")
	require.NoError(t, os.Symlink("other_gen.go", output))
	require.NoError(t, os.Symlink("output_gen.go", other))

	err = writeGeneratedFile(output, []byte(generatedSource))
	require.ErrorContains(t, err, "too many levels of symbolic links")
}

func TestRunSchemaWritesToOutputDirectorySymlink(t *testing.T) {
	directory, err := os.MkdirTemp(".", ".tmp-schema-output-directory-*")
	require.NoError(t, err)
	t.Cleanup(func() {
		require.NoError(t, os.RemoveAll(directory))
	})
	input := filepath.Join(directory, "schema.json")
	require.NoError(t, os.WriteFile(input, []byte(`[{"Name":"users","Columns":[{"Name":"id","Type":{"Kind":"integer","Unsigned":false}}],"PrimaryKey":["id"]}]`), 0o600))
	target := filepath.Join(directory, "generated")
	require.NoError(t, os.Mkdir(target, 0o700))
	output := filepath.Join(directory, "output")
	require.NoError(t, os.Symlink("generated", output))

	require.NoError(t, run([]string{"schema", "-input", input, "-package", "generated", "-output", output}))
	require.FileExists(t, filepath.Join(target, "users_gen.go"))
}
