// Code generated by rasqlgen schema; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
)

type MembersRow struct {
	ID    int64
	Name  string
	Email string
}

// ScanRow scans each result column directly into its field.
func (r *MembersRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.Name, &r.Email)
}

// ScanDestinations maps result-column names to fields on r.
func (r *MembersRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexName
		scanIndexEmail
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(3)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "name":
			if !scanned.Mark(scanIndexName) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Name
		case "email":
			if !scanned.Mark(scanIndexEmail) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Email
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r MembersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "name":
		return r.Name, true
	case "email":
		return r.Email, true
	}
	return nil, false
}

// MembersTable is the generated table type for the "members" table.
type MembersTable struct {
	rasql.Table[MembersRow]
}

// ID returns a reference to the "id" column.
func (t MembersTable) ID() query.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// Name returns a reference to the "name" column.
func (t MembersTable) Name() query.ColumnRef { return rasql.ColumnOf(t.Table, "name") }

// Email returns a reference to the "email" column.
func (t MembersTable) Email() query.ColumnRef { return rasql.ColumnOf(t.Table, "email") }

// Members returns the descriptor for the "members" table.
func Members() MembersTable {
	return membersTable
}

// As returns the table under alias.
func (t MembersTable) As(alias string) (MembersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return MembersTable{}, err
	}
	return MembersTable{Table: aliased}, nil
}
