// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/row"
	"github.com/lestrrat-go/rasql/schema"
)

type MembersRow struct {
	ID    int64
	Name  string
	Email string
}

// DecodeRow assigns each result column to its field.
func (r *MembersRow) DecodeRow(src row.Dynamic) error {
	if err := row.Assign(src, "id", &r.ID); err != nil {
		return err
	}
	if err := row.Assign(src, "name", &r.Name); err != nil {
		return err
	}
	return row.Assign(src, "email", &r.Email)
}

// ScanRow scans each result column directly into its field.
func (r *MembersRow) ScanRow(src row.ScanSource) error {
	return src.Scan(&r.ID, &r.Name, &r.Email)
}

// IsGeneratedRow marks this row as generated by rasqlgen.
func (*MembersRow) IsGeneratedRow() {}

// ScanDestinations maps result-column names to fields on r.
func (r *MembersRow) ScanDestinations(columns []string) ([]any, error) {
	destinations := make([]any, len(columns))
	var scanned uint64
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if scanned&(uint64(1)<<0) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 0
			destinations[index] = &r.ID
		case "name":
			if scanned&(uint64(1)<<1) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 1
			destinations[index] = &r.Name
		case "email":
			if scanned&(uint64(1)<<2) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 2
			destinations[index] = &r.Email
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r MembersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "name":
		return r.Name, true
	case "email":
		return r.Email, true
	}
	return nil, false
}

// MembersTable is the generated table type for the "members" table.
type MembersTable struct {
	rasql.Table[MembersRow]
	ID    query.ColumnRef
	Name  query.ColumnRef
	Email query.ColumnRef
}

func newMembersTable(table rasql.Table[MembersRow]) MembersTable {
	return MembersTable{
		Table: table,
		ID:    rasql.MustColumn(table, "id"),
		Name:  rasql.MustColumn(table, "name"),
		Email: rasql.MustColumn(table, "email"),
	}
}

var membersTable = newMembersTable(rasql.MustTableOf[MembersRow](schema.MustTable("members",
	schema.Integer("id"),
	schema.Text("name"),
	schema.Text("email"),
	schema.PrimaryKey("id"),
)))

// Members returns the descriptor for the "members" table.
func Members() MembersTable {
	return membersTable
}

// As returns the table under alias, with every column rebound to it.
func (t MembersTable) As(alias string) (MembersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return MembersTable{}, err
	}
	return newMembersTable(aliased), nil
}
