// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
	"time"
)

type overdue_countResult struct {
	Overdue int64
}

type OverdueCountBindings struct{}
type OverdueCountExpressions struct {
	Overdue rasql.Column[overdue_countResult, int64]
}

func (OverdueCountBindings) Bind(source rasql.TypedSource[overdue_countResult]) (OverdueCountExpressions, error) {
	valueOverdue, err := rasql.BindResultColumn[overdue_countResult, int64](source, "overdue")
	if err != nil {
		return OverdueCountExpressions{}, err
	}
	return OverdueCountExpressions{Overdue: valueOverdue}, nil
}

type overdue_countDecoder struct{}

func (overdue_countDecoder) ResultSchema() rasql.ResultSchema { return overdue_countDecoderSchema() }
func (overdue_countDecoder) Presence() []rasql.Presence       { return nil }
func (overdue_countDecoder) DecodeRow(s rasql.ScanSource, r *overdue_countResult) error {
	if err := s.Scan(&r.Overdue); err != nil {
		return err
	}
	return nil
}

func overdue_countDecoderSchema() rasql.ResultSchema {
	s, _ := rasql.NewResultSchema(
		rasql.ResultColumn{Name: "overdue", Type: schema.IntegerType{}, Nullable: false, Codec: ""},
	)
	return s
}

func OverdueCount(on time.Time) (rasql.Query[overdue_countResult], error) {
	projection, err := rasql.NativeProjection[overdue_countResult](overdue_countDecoder{})
	if err != nil {
		return rasql.Query[overdue_countResult]{}, err
	}
	return rasql.Native[overdue_countResult](rasql.NativeStatement{Engine: "postgresql", SQL: "SELECT COUNT(*) AS overdue\nFROM tasks\nWHERE is_open AND due_on IS NOT NULL AND due_on < CAST($1 AS date)\n", Args: []rasql.NativeArgument{{Value: on, Codec: ""}}}, projection, rasql.ExactlyOne)
}
