// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"context"
	"fmt"

	"github.com/lestrrat-go/rasql"
)

type ProjectsRow struct {
	ID   int64
	Name string
}

// ScanRow scans each result column directly into its field.
func (r *ProjectsRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.Name)
}

// ScanDestinations maps result-column names to fields on r.
func (r *ProjectsRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexName
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(2)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "name":
			if !scanned.Mark(scanIndexName) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Name
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r ProjectsRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "name":
		return r.Name, true
	}
	return nil, false
}

// ProjectsTable is the generated table type for the "projects" table.
type ProjectsTable struct {
	rasql.Table[ProjectsRow]
}

// ID returns a reference to the "id" column.
func (t ProjectsTable) ID() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// Name returns a reference to the "name" column.
func (t ProjectsTable) Name() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "name") }

// Projects returns the descriptor for the "projects" table.
func Projects() ProjectsTable {
	return projectsTable
}

// As returns the table under alias.
func (t ProjectsTable) As(alias string) (ProjectsTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return ProjectsTable{}, err
	}
	return ProjectsTable{Table: aliased}, nil
}

// ProjectsTableTasksRelation describes the Tasks relationship from ProjectsTable.
type ProjectsTableTasksRelation struct {
	Parent    ProjectsTable
	Child     TasksTable
	ParentKey rasql.ColumnRef
	ChildKey  rasql.ColumnRef
}

// Tasks returns the generated relationship descriptor.
func (t ProjectsTable) Tasks() ProjectsTableTasksRelation {
	child := Tasks()
	parent := t
	return ProjectsTableTasksRelation{Parent: parent, Child: child, ParentKey: parent.ID(), ChildKey: child.ProjectID()}
}

// Join returns an INNER JOIN for the relationship.
func (r ProjectsTableTasksRelation) Join() rasql.Join {
	return rasql.InnerJoin(r.Child, rasql.Equal(r.ParentKey, r.ChildKey))
}

// Load fetches all children for parents in one query and groups them by parent key.
func (r ProjectsTableTasksRelation) Load(ctx context.Context, db rasql.DB, parents []ProjectsRow) (map[int64][]TasksRow, error) {
	return rasql.LoadHasMany[ProjectsRow, TasksRow, int64](ctx, db, r.Child, r.ChildKey, parents, func(row ProjectsRow) int64 { return row.ID }, func(row TasksRow) int64 { return row.ProjectID })
}
