// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/row"
	"github.com/lestrrat-go/rasql/schema"
)

type ProjectsRow struct {
	ID       int64
	OwnerID  int64
	Name     string
	Archived bool
}

// DecodeRow assigns each result column to its field.
func (r *ProjectsRow) DecodeRow(src row.Dynamic) error {
	if err := row.Assign(src, "id", &r.ID); err != nil {
		return err
	}
	if err := row.Assign(src, "owner_id", &r.OwnerID); err != nil {
		return err
	}
	if err := row.Assign(src, "name", &r.Name); err != nil {
		return err
	}
	return row.Assign(src, "archived", &r.Archived)
}

// ScanRow scans each result column directly into its field.
func (r *ProjectsRow) ScanRow(src row.ScanSource) error {
	return src.Scan(&r.ID, &r.OwnerID, &r.Name, &r.Archived)
}

// ScanDestinations maps result-column names to fields on r.
func (r *ProjectsRow) ScanDestinations(columns []string) ([]any, error) {
	destinations := make([]any, len(columns))
	var scannedID bool
	var scannedOwnerID bool
	var scannedName bool
	var scannedArchived bool
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if scannedID {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scannedID = true
			destinations[index] = &r.ID
		case "owner_id":
			if scannedOwnerID {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scannedOwnerID = true
			destinations[index] = &r.OwnerID
		case "name":
			if scannedName {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scannedName = true
			destinations[index] = &r.Name
		case "archived":
			if scannedArchived {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scannedArchived = true
			destinations[index] = &r.Archived
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r ProjectsRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "owner_id":
		return r.OwnerID, true
	case "name":
		return r.Name, true
	case "archived":
		return r.Archived, true
	}
	return nil, false
}

// ProjectsTable is the generated table type for the "projects" table.
type ProjectsTable struct {
	rasql.Table[ProjectsRow]
	ID       query.Column
	OwnerID  query.Column
	Name     query.Column
	Archived query.Column
}

func newProjectsTable(table rasql.Table[ProjectsRow]) ProjectsTable {
	return ProjectsTable{
		Table:    table,
		ID:       rasql.MustColumn(table, "id"),
		OwnerID:  rasql.MustColumn(table, "owner_id"),
		Name:     rasql.MustColumn(table, "name"),
		Archived: rasql.MustColumn(table, "archived"),
	}
}

var projectsTable = newProjectsTable(rasql.MustTable[ProjectsRow](schema.Table{
	Name: "projects",
	Columns: []schema.Column{
		{Name: "id", Type: schema.TypeInteger},
		{Name: "owner_id", Type: schema.TypeInteger},
		{Name: "name", Type: schema.TypeText},
		{Name: "archived", Type: schema.TypeBoolean, Default: "FALSE"},
	},
	PrimaryKey: []string{"id"},
}))

// Projects returns the descriptor for the "projects" table.
func Projects() ProjectsTable {
	return projectsTable
}

// As returns the table under alias, with every column rebound to it.
func (t ProjectsTable) As(alias string) (ProjectsTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return ProjectsTable{}, err
	}
	return newProjectsTable(aliased), nil
}
