// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
)

var membersDef = schema.TableDef{
	Schema: "main",
	Name:   "members",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "name", Type: schema.TextType{}},
		{Name: "email", Type: schema.TextType{}},
	},
	PrimaryKey: []string{"id"},
	UniqueConstraints: []schema.UniqueDef{
		{Columns: []string{"email"}},
	},
}

var membersTable = MembersTable{rasql.TableFrom[MembersRow](membersDef)}

// MembersDef returns a copy of the descriptor for the "members" table.
func MembersDef() schema.TableDef { return membersDef.Clone() }

var projectsDef = schema.TableDef{
	Schema: "main",
	Name:   "projects",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "owner_id", Type: schema.IntegerType{}},
		{Name: "name", Type: schema.TextType{}},
		{Name: "archived", Type: schema.BooleanType{}, Default: "FALSE"},
	},
	PrimaryKey: []string{"id"},
	ForeignKeys: []schema.ForeignKeyDef{
		{Columns: []string{"owner_id"}, ReferencedTable: "members", ReferencedColumns: []string{"id"}, OnDelete: schema.NoAction, OnUpdate: schema.NoAction},
	},
	Relationships: []schema.RelationshipDef{
		{Name: "Owner", Kind: schema.RelationshipBelongsTo, Columns: []string{"owner_id"}, ReferencedTable: "members", ReferencedColumns: []string{"id"}},
	},
}

var projectsTable = ProjectsTable{rasql.TableFrom[ProjectsRow](projectsDef)}

// ProjectsDef returns a copy of the descriptor for the "projects" table.
func ProjectsDef() schema.TableDef { return projectsDef.Clone() }

var tasksDef = schema.TableDef{
	Schema: "main",
	Name:   "tasks",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "project_id", Type: schema.IntegerType{}},
		{Name: "assignee_id", Type: schema.IntegerType{}},
		{Name: "title", Type: schema.TextType{}},
		{Name: "status", Type: schema.TextType{}},
		{Name: "priority", Type: schema.IntegerType{}},
	},
	PrimaryKey: []string{"id"},
	Checks: []schema.CheckDef{
		{Expression: "status IN ('todo', 'in_progress', 'done')"},
	},
	Indexes: []schema.IndexDef{
		{Name: "tasks_open_by_project", Columns: []string{"project_id", "status", "priority"}},
	},
	ForeignKeys: []schema.ForeignKeyDef{
		{Columns: []string{"assignee_id"}, ReferencedTable: "members", ReferencedColumns: []string{"id"}, OnDelete: schema.NoAction, OnUpdate: schema.NoAction},
		{Columns: []string{"project_id"}, ReferencedTable: "projects", ReferencedColumns: []string{"id"}, OnDelete: schema.NoAction, OnUpdate: schema.NoAction},
	},
	Relationships: []schema.RelationshipDef{
		{Name: "Assignee", Kind: schema.RelationshipBelongsTo, Columns: []string{"assignee_id"}, ReferencedTable: "members", ReferencedColumns: []string{"id"}},
		{Name: "Project", Kind: schema.RelationshipBelongsTo, Columns: []string{"project_id"}, ReferencedTable: "projects", ReferencedColumns: []string{"id"}},
	},
}

var tasksTable = TasksTable{rasql.TableFrom[TasksRow](tasksDef)}

// TasksDef returns a copy of the descriptor for the "tasks" table.
func TasksDef() schema.TableDef { return tasksDef.Clone() }
