// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/row"
	"github.com/lestrrat-go/rasql/schema"
)

type TasksRow struct {
	ID         int64
	ProjectID  int64
	AssigneeID int64
	Title      string
	Status     string
	Priority   int64
}

// ScanRow scans each result column directly into its field.
func (r *TasksRow) ScanRow(src row.ScanSource) error {
	return src.Scan(&r.ID, &r.ProjectID, &r.AssigneeID, &r.Title, &r.Status, &r.Priority)
}

// ScanDestinations maps result-column names to fields on r.
func (r *TasksRow) ScanDestinations(columns []string) ([]any, error) {
	destinations := make([]any, len(columns))
	var scanned uint64
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if scanned&(uint64(1)<<0) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 0
			destinations[index] = &r.ID
		case "project_id":
			if scanned&(uint64(1)<<1) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 1
			destinations[index] = &r.ProjectID
		case "assignee_id":
			if scanned&(uint64(1)<<2) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 2
			destinations[index] = &r.AssigneeID
		case "title":
			if scanned&(uint64(1)<<3) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 3
			destinations[index] = &r.Title
		case "status":
			if scanned&(uint64(1)<<4) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 4
			destinations[index] = &r.Status
		case "priority":
			if scanned&(uint64(1)<<5) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 5
			destinations[index] = &r.Priority
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r TasksRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "project_id":
		return r.ProjectID, true
	case "assignee_id":
		return r.AssigneeID, true
	case "title":
		return r.Title, true
	case "status":
		return r.Status, true
	case "priority":
		return r.Priority, true
	}
	return nil, false
}

// TasksTable is the generated table type for the "tasks" table.
type TasksTable struct {
	rasql.Table[TasksRow]
	ID         query.ColumnRef
	ProjectID  query.ColumnRef
	AssigneeID query.ColumnRef
	Title      query.ColumnRef
	Status     query.ColumnRef
	Priority   query.ColumnRef
}

func newTasksTable(table rasql.Table[TasksRow]) TasksTable {
	return TasksTable{
		Table:      table,
		ID:         rasql.MustColumn(table, "id"),
		ProjectID:  rasql.MustColumn(table, "project_id"),
		AssigneeID: rasql.MustColumn(table, "assignee_id"),
		Title:      rasql.MustColumn(table, "title"),
		Status:     rasql.MustColumn(table, "status"),
		Priority:   rasql.MustColumn(table, "priority"),
	}
}

var tasksTable = newTasksTable(rasql.MustTableOf[TasksRow](schema.MustTableDef("tasks",
	schema.InSchema("main"),
	schema.Integer("id"),
	schema.Integer("project_id"),
	schema.Integer("assignee_id"),
	schema.Text("title"),
	schema.Text("status"),
	schema.Integer("priority"),
	schema.PrimaryKey("id"),
	schema.Check("status IN ('todo', 'in_progress', 'done')"),
	schema.Index("tasks_open_by_project", "project_id", "status", "priority"),
	schema.ForeignKey("assignee_id", schema.References("members", "id"), schema.OnDelete(schema.NoAction), schema.OnUpdate(schema.NoAction), schema.RelationshipNamed("Assignee")),
	schema.ForeignKey("project_id", schema.References("projects", "id"), schema.OnDelete(schema.NoAction), schema.OnUpdate(schema.NoAction), schema.RelationshipNamed("Project")),
)))

// Tasks returns the descriptor for the "tasks" table.
func Tasks() TasksTable {
	return tasksTable
}

// As returns the table under alias, with every column rebound to it.
func (t TasksTable) As(alias string) (TasksTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return TasksTable{}, err
	}
	return newTasksTable(aliased), nil
}
