// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
)

type MembersRow struct {
	ID   int64
	Name string
}

var membersDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "members",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "name", Type: schema.TextType{Width: schema.NewTextWidth(64)}},
	},
	PrimaryKey: []string{"id"},
}

var membersTable = rasql.MustTableOf[MembersRow](membersDefinition)

type membersTableHandle = rasql.Table[MembersRow]

type MembersTable struct {
	membersTableHandle
}

func Members() MembersTable { return MembersTable{membersTableHandle: membersTable} }

func (t MembersTable) Ref() query.TableRef { return t.membersTableHandle.Ref() }

func (t MembersTable) As(alias string) (MembersTable, error) {
	aliased, err := t.membersTableHandle.As(alias)
	if err != nil {
		return MembersTable{}, err
	}
	return MembersTable{membersTableHandle: aliased}, nil
}

func (t MembersTable) Table() rasql.Table[MembersRow] { return t.membersTableHandle }

func (t MembersTable) InSchema(namespace string) (MembersTable, error) {
	moved, err := t.membersTableHandle.InSchema(namespace)
	if err != nil {
		return MembersTable{}, err
	}
	return MembersTable{membersTableHandle: moved}, nil
}

type MembersColumns struct{}

type MembersExpressions struct {
	ID   rasql.Column[MembersRow, int64]
	Name rasql.Column[MembersRow, string]
}

type OptionalMembersExpressions struct {
	ID   rasql.NullColumn[MembersRow, int64]
	Name rasql.NullColumn[MembersRow, string]
}

func (MembersColumns) Bind(source rasql.Table[MembersRow]) (MembersExpressions, error) {
	var err error
	result := MembersExpressions{
		ID:   rasqlgenBind(&err, source, "id", "", rasql.BindColumn[MembersRow, int64]),
		Name: rasqlgenBind(&err, source, "name", "", rasql.BindColumn[MembersRow, string]),
	}
	return result, err
}

func (MembersColumns) BindOptional(source rasql.OptionalRelation[MembersRow]) (OptionalMembersExpressions, error) {
	var err error
	result := OptionalMembersExpressions{
		ID:   rasqlgenBind(&err, source, "id", "", rasql.BindOptionalColumn[MembersRow, int64]),
		Name: rasqlgenBind(&err, source, "name", "", rasql.BindOptionalColumn[MembersRow, string]),
	}
	return result, err
}

var membersResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "name", Type: schema.TextType{Width: schema.NewTextWidth(64)}, Codec: ""},
}
var membersResultSchema = rasqlgenResultSchema(membersResultColumns)

type membersDecoder struct{}

func (membersDecoder) ResultSchema() rasql.ResultSchema { return membersResultSchema }
func (membersDecoder) Presence() []rasql.Presence       { return nil }
func (membersDecoder) DecodeRow(source rasql.ScanSource, row *MembersRow) error {
	return source.Scan(&row.ID, &row.Name)
}

func (row *MembersRow) ScanRow(source rasql.ScanSource) error {
	return membersDecoder{}.DecodeRow(source, row)
}

var membersOptionalResultSchema = rasqlgenOptionalResultSchema(membersResultColumns)

type membersOptionalDecoder struct{}

func (membersOptionalDecoder) ResultSchema() rasql.ResultSchema { return membersOptionalResultSchema }
func (membersOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Members", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (membersOptionalDecoder) DecodeRow(source rasql.ScanSource, row *MembersRow) error {
	var IDValue rasql.Nullable[int64]
	var NameValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &NameValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(NameValue, &row.Name)
	return nil
}

func MembersProjection(expressions MembersExpressions) (rasql.Projection[MembersRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", expressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("name", expressions.Name.Expr(), schema.TextType{Width: schema.NewTextWidth(64)}, ""),
	}
	return rasql.NewProjection(items, membersDecoder{})
}

func OptionalMembersProjection(expressions OptionalMembersExpressions) (rasql.Projection[MembersRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", expressions.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("name", expressions.Name.NullExpr(), schema.TextType{Width: schema.NewTextWidth(64)}, ""),
	}
	return rasql.NewProjection(items, membersOptionalDecoder{})
}

func MembersGraphKey(source rasql.Table[MembersRow]) (rasql.GraphKey[MembersRow], error) {
	expressions, err := (MembersColumns{}).Bind(source)
	if err != nil {
		return rasql.GraphKey[MembersRow]{}, err
	}
	return rasql.NewGraphKey[MembersRow](rasql.KeyPart[MembersRow, int64](expressions.ID, func(row MembersRow) int64 { return row.ID }))
}

func MembersIDPageKey(source rasql.Table[MembersRow], direction rasql.PageDirection) (rasql.PageKey[MembersRow], error) {
	expressions, err := (MembersColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.ID.Expr(), func(row MembersRow) int64 { return row.ID })
}

func MembersNamePageKey(source rasql.Table[MembersRow], direction rasql.PageDirection) (rasql.PageKey[MembersRow], error) {
	expressions, err := (MembersColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.Name.Expr(), func(row MembersRow) string { return row.Name })
}

func MembersTasksEdge[G, CG any](parentSource rasql.Table[MembersRow], childSource rasql.Table[TasksRow], children rasql.GraphPlan[TasksRow, CG], options rasql.EdgeOptions, attach func(*G, rasql.LoadedMany[CG])) (rasql.GraphEdge[MembersRow, G], error) {
	parentExpressions, err := (MembersColumns{}).Bind(parentSource)
	if err != nil {
		return nil, err
	}
	childExpressions, err := (TasksColumns{}).Bind(childSource)
	if err != nil {
		return nil, err
	}
	parent, err := rasql.NewGraphKey[MembersRow](rasql.KeyPart[MembersRow, int64](parentExpressions.ID, func(row MembersRow) int64 { return row.ID }))
	if err != nil {
		return nil, err
	}
	child, err := rasql.NewGraphKey[TasksRow](rasql.NullKeyPart[TasksRow, int64](childExpressions.AssigneeID, func(row TasksRow) rasql.Nullable[int64] { return row.AssigneeID }))
	if err != nil {
		return nil, err
	}
	return rasql.HasMany("Tasks", parent, child, children, options, attach)
}

var membersMutationColumns = func() MembersExpressions {
	value, err := (MembersColumns{}).Bind(Members().Table())
	if err != nil {
		panic(err)
	}
	return value
}()

type MembersCreate struct {
	table  rasql.Table[MembersRow]
	fields []rasql.MutationField[MembersRow]
}

func (v MembersCreate) ID(value int64) MembersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(membersMutationColumns.ID, value))
	return v
}
func (v MembersCreate) Name(value string) MembersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(membersMutationColumns.Name, value))
	return v
}
func (v MembersCreate) Plan() (rasql.CreatePlan[MembersRow], error) {
	return rasql.NewCreatePlan(v.table, v.fields...)
}

func (t MembersTable) Create() MembersCreate { return MembersCreate{table: t.membersTableHandle} }

type MembersPatch struct {
	table  rasql.Table[MembersRow]
	fields []rasql.MutationField[MembersRow]
}

func (v MembersPatch) ID(value int64) MembersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(membersMutationColumns.ID, value))
	return v
}
func (v MembersPatch) Name(value string) MembersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(membersMutationColumns.Name, value))
	return v
}
func (v MembersPatch) Where(value rasql.Predicate) (rasql.PatchPlan[MembersRow], error) {
	return rasql.NewPatchPlan(v.table, value, v.fields...)
}

func (t MembersTable) Patch() MembersPatch { return MembersPatch{table: t.membersTableHandle} }

func (t MembersTable) Delete(where rasql.Predicate) (rasql.DeletePlan[MembersRow], error) {
	return rasql.NewDeletePlan(t.membersTableHandle, where)
}
