//go:build unix

package render_test

import (
	"context"
	"testing"

	gomysql "github.com/go-sql-driver/mysql"
	"github.com/lestrrat-go/rasql/dialect"
	"github.com/lestrrat-go/rasql/internal/dbtest"
	"github.com/lestrrat-go/rasql/render"
	"github.com/lestrrat-go/rasql/schema"
	"github.com/stretchr/testify/require"
)

// TestCreateTableRendersIdentityColumnAgainstLivePostgreSQL proves that
// render.CreateTable's own output for a descriptor naming both identity
// generations is DDL a real PostgreSQL server accepts, and that the
// resulting catalog reports the same identity facts back -- a fixture test
// only asserts the rendered SQL string, never that a server accepts it.
func TestCreateTableRendersIdentityColumnAgainstLivePostgreSQL(t *testing.T) {
	ctx := context.Background()
	database := dbtest.PostgreSQLDB(t)

	table := schema.TableDef{
		Name: "live_render_members",
		Columns: []schema.ColumnDef{
			{Name: "id", Type: schema.IntegerType{}, Identity: schema.IdentityAlways},
			{Name: "legacy_id", Type: schema.IntegerType{}, Identity: schema.IdentityByDefault},
		},
		PrimaryKey: []string{"id"},
	}

	rendered, err := render.CreateTable(dialect.PostgreSQL(), table)
	require.NoError(t, err)

	_, err = database.ExecContext(ctx, rendered.SQL(), rendered.Args()...)
	require.NoError(t, err, "PostgreSQL must accept render.CreateTable's own output for an identity descriptor")

	rows, err := database.QueryContext(ctx, "SELECT column_name, is_identity, identity_generation FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'live_render_members' ORDER BY ordinal_position")
	require.NoError(t, err)
	defer func() { _ = rows.Close() }()

	facts := map[string][2]string{}
	for rows.Next() {
		var name, isIdentity, identityGeneration string
		require.NoError(t, rows.Scan(&name, &isIdentity, &identityGeneration))
		facts[name] = [2]string{isIdentity, identityGeneration}
	}
	require.NoError(t, rows.Err())

	require.Equal(t, [2]string{"YES", "ALWAYS"}, facts["id"], "the catalog must report id as GENERATED ALWAYS AS IDENTITY")
	require.Equal(t, [2]string{"YES", "BY DEFAULT"}, facts["legacy_id"], "the catalog must report legacy_id as GENERATED BY DEFAULT AS IDENTITY")
}

// TestCreateTableRendersAutoIncrementAgainstLiveMySQL proves that
// render.CreateTable's AUTO_INCREMENT output for a BY DEFAULT identity
// column is DDL a real MySQL server accepts, and that the resulting
// catalog reports it back.
func TestCreateTableRendersAutoIncrementAgainstLiveMySQL(t *testing.T) {
	ctx := context.Background()
	database := dbtest.MySQLDB(t)

	table := schema.TableDef{
		Name: "live_render_members",
		Columns: []schema.ColumnDef{
			{Name: "id", Type: schema.IntegerType{}, Identity: schema.IdentityByDefault},
		},
		PrimaryKey: []string{"id"},
	}

	rendered, err := render.CreateTable(dialect.MySQL(), table)
	require.NoError(t, err)

	_, err = database.ExecContext(ctx, rendered.SQL(), rendered.Args()...)
	require.NoError(t, err, "MySQL must accept render.CreateTable's own AUTO_INCREMENT output")

	var extra string
	err = database.QueryRowContext(ctx, "SELECT extra FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'live_render_members' AND column_name = 'id'").Scan(&extra)
	require.NoError(t, err)
	require.Equal(t, "auto_increment", extra, "the catalog must report id as auto_increment")
}

// TestUnkeyedAutoIncrementColumnFailsWithMySQLError1075 pins the MySQL
// rule render.writeCreateTable's own keyness check (see
// checkMySQLIdentityKeyness in render/schema.go) exists to pre-empt: an
// AUTO_INCREMENT column that is not the leading column of any key fails
// with MySQL's own error 1075, not a generic syntax error. The DDL here is
// issued directly, bypassing render, precisely because render already
// refuses this shape before it would ever reach the server -- this test
// pins the assumption that refusal rests on, the same way
// TestIndexedTextRequiresWidthOnMySQL pins error 1170 for the check
// render's own MySQL text-width refusal rests on.
func TestUnkeyedAutoIncrementColumnFailsWithMySQLError1075(t *testing.T) {
	ctx := context.Background()
	database := dbtest.MySQLDB(t)

	_, err := database.ExecContext(ctx, "CREATE TABLE live_render_unkeyed_auto (a BIGINT NOT NULL, id BIGINT NOT NULL AUTO_INCREMENT, PRIMARY KEY (a)) ENGINE=InnoDB")
	require.Error(t, err, "MySQL must refuse an AUTO_INCREMENT column that leads no key")

	var mysqlErr *gomysql.MySQLError
	require.ErrorAs(t, err, &mysqlErr, "the refusal must come from MySQL itself, not from a connection or driver failure")
	require.EqualValues(t, 1075, mysqlErr.Number, "MySQL's own error for \"there can be only one auto column and it must be defined as a key\"")
}
