// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
)

var usersDef = schema.TableDef{
	Name: "users",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "email", Type: schema.TextType{Width: schema.NewTextWidth(255)}},
	},
	PrimaryKey: []string{"id"},
}

var usersTable = UsersTable{rasql.TableFrom[UsersRow](usersDef)}

// UsersDef returns a copy of the descriptor for the "users" table.
func UsersDef() schema.TableDef { return usersDef.Clone() }

// Tables returns a clone of every table's descriptor, in the order this
// file declares them.
func Tables() []schema.TableDef {
	return []schema.TableDef{
		usersDef.Clone(),
	}
}
