// Code generated by rasqlgen; DO NOT EDIT.

package tables

import "github.com/lestrrat-go/rasql/schema"

// Tables returns every table this package describes, in the order
// bootstrap wrote them, with every entry in Hints applied.
func Tables() []schema.TableDef {
	tables := []schema.TableDef{
		UsersDef(),
	}
	for index, table := range tables {
		if hint, ok := Hints[table.Name]; ok {
			tables[index] = hint.Apply(table)
		}
	}
	return tables
}
