// Code generated by rasqlgen; DO NOT EDIT.

package tables

import "github.com/lestrrat-go/rasql/schema"

// UsersDef returns the schema.TableDef bootstrap inspected for the "users" table.
func UsersDef() schema.TableDef {
	return schema.TableDef{
		Schema: "main",
		Name:   "users",
		Columns: []schema.ColumnDef{
			{Name: "id", Type: schema.IntegerType{}},
			{Name: "email", Type: schema.TextType{}},
		},
		PrimaryKey: []string{"id"},
	}
}
