// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
	"time"
)

type maybe_overdue_taskResult struct {
	ID         int64
	ProjectID  int64
	AssigneeID rasql.Nullable[int64]
	Title      string
	IsOpen     bool
	DueOn      rasql.Nullable[time.Time]
	CreatedAt  time.Time
}

type MaybeOverdueTaskBindings struct{}
type MaybeOverdueTaskExpressions struct {
	ID         rasql.Column[maybe_overdue_taskResult, int64]
	ProjectID  rasql.Column[maybe_overdue_taskResult, int64]
	AssigneeID rasql.NullColumn[maybe_overdue_taskResult, int64]
	Title      rasql.Column[maybe_overdue_taskResult, string]
	IsOpen     rasql.Column[maybe_overdue_taskResult, bool]
	DueOn      rasql.NullColumn[maybe_overdue_taskResult, time.Time]
	CreatedAt  rasql.Column[maybe_overdue_taskResult, time.Time]
}

func (MaybeOverdueTaskBindings) Bind(source rasql.TypedSource[maybe_overdue_taskResult]) (MaybeOverdueTaskExpressions, error) {
	valueID, err := rasql.BindResultColumn[maybe_overdue_taskResult, int64](source, "id")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	valueProjectID, err := rasql.BindResultColumn[maybe_overdue_taskResult, int64](source, "project_id")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	valueAssigneeID, err := rasql.BindNullResultColumn[maybe_overdue_taskResult, int64](source, "assignee_id")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	valueTitle, err := rasql.BindResultColumn[maybe_overdue_taskResult, string](source, "title")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	valueIsOpen, err := rasql.BindResultColumn[maybe_overdue_taskResult, bool](source, "is_open")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	valueDueOn, err := rasql.BindNullResultColumn[maybe_overdue_taskResult, time.Time](source, "due_on")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	valueCreatedAt, err := rasql.BindResultColumn[maybe_overdue_taskResult, time.Time](source, "created_at")
	if err != nil {
		return MaybeOverdueTaskExpressions{}, err
	}
	return MaybeOverdueTaskExpressions{ID: valueID, ProjectID: valueProjectID, AssigneeID: valueAssigneeID, Title: valueTitle, IsOpen: valueIsOpen, DueOn: valueDueOn, CreatedAt: valueCreatedAt}, nil
}

type maybe_overdue_taskDecoder struct{}

func (maybe_overdue_taskDecoder) ResultSchema() rasql.ResultSchema {
	return maybe_overdue_taskDecoderSchema()
}
func (maybe_overdue_taskDecoder) Presence() []rasql.Presence { return nil }
func (maybe_overdue_taskDecoder) DecodeRow(s rasql.ScanSource, r *maybe_overdue_taskResult) error {
	if err := s.Scan(&r.ID, &r.ProjectID, &r.AssigneeID, &r.Title, &r.IsOpen, &r.DueOn, &r.CreatedAt); err != nil {
		return err
	}
	return nil
}

func maybe_overdue_taskDecoderSchema() rasql.ResultSchema {
	s, _ := rasql.NewResultSchema(
		rasql.ResultColumn{Name: "id", Type: schema.IntegerType{}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "project_id", Type: schema.IntegerType{}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "assignee_id", Type: schema.IntegerType{}, Nullable: true, Codec: ""},
		rasql.ResultColumn{Name: "title", Type: schema.TextType{}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "is_open", Type: schema.BooleanType{}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "due_on", Type: schema.TimeType{}, Nullable: true, Codec: ""},
		rasql.ResultColumn{Name: "created_at", Type: schema.TimeType{}, Nullable: false, Codec: ""},
	)
	return s
}

func MaybeOverdueTask(projectID int64, open bool, cutoff time.Time) (rasql.Query[maybe_overdue_taskResult], error) {
	projection, err := rasql.NativeProjection[maybe_overdue_taskResult](maybe_overdue_taskDecoder{})
	if err != nil {
		return rasql.Query[maybe_overdue_taskResult]{}, err
	}
	return rasql.Native[maybe_overdue_taskResult](rasql.NativeStatement{Engine: "sqlite", SQL: "SELECT id, project_id, assignee_id, title, is_open, due_on, created_at\nFROM tasks\nWHERE project_id = ?\n  AND is_open = ?\n  AND due_on IS NOT NULL\n  AND due_on < ?\nORDER BY id\n", Args: []rasql.NativeArgument{{Value: projectID, Codec: ""}, {Value: open, Codec: ""}, {Value: cutoff, Codec: ""}}}, projection, rasql.AtMostOne)
}
