// Package genfile writes generated Go source without ever truncating an
// existing file in place. It is internal because both generate and
// cli/rasqlgen need it and no caller outside this module does.
package genfile

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Write writes source to path without ever truncating an
// existing file in place. Its resolved destination must end in _gen.go, or
// in _gen_test.go for a generated test file, and, when it already exists,
// must be a file rasqlgen itself wrote; see ResolveDestination for both
// checks.
// When path is a symbolic link it writes through
// the link to the file the link points at, leaving the link itself intact.
// A path that names a directory, or a symbolic link that resolves to one,
// is rejected with an error instead of being written into, regardless of
// whether path ends in a trailing slash.
// It writes to a temporary file in the same directory as that resolved
// destination, then renames the temporary file over the destination only
// after the write fully succeeds, so a failure at any point along the way
// leaves the destination untouched instead of empty or partially written.
// When the destination already exists, the mode bits generatedFileMode
// reports for it are copied to the temporary file before the rename, so
// regenerating never changes the mode of an existing output file; a file
// that did not exist is created at 0600.
//
// The rename is only atomic on Unix platforms. os.Rename documents that
// even within a single directory it is not an atomic operation on
// non-Unix platforms, so a run interrupted there can leave the destination
// missing or still holding its old contents.
func Write(artifact Artifact, path string, source []byte) error {
	// Both the temporary file's directory and the rename destination come
	// from the resolved path. Resolving only the destination would put the
	// temporary file beside the link instead of beside its target, and
	// renaming across filesystems fails with EXDEV.
	destination, err := ResolveDestination(artifact, path)
	if err != nil {
		return err
	}
	mode, err := generatedFileMode(destination)
	if err != nil {
		return err
	}
	directory := filepath.Dir(destination)
	temporary, err := os.CreateTemp(directory, "."+filepath.Base(destination)+".tmp*")
	if err != nil {
		return err
	}
	removeTemporary := true
	defer func() {
		if removeTemporary {
			_ = os.Remove(temporary.Name())
		}
	}()

	if _, err := temporary.Write(source); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	// chmod before the rename, so the destination is never visible with
	// the temporary file's mode instead of the mode it had before.
	if err := os.Chmod(temporary.Name(), mode); err != nil {
		return err
	}
	if err := os.Rename(temporary.Name(), destination); err != nil {
		return err
	}
	removeTemporary = false
	return nil
}

// Artifact names which rasqlgen command owns a generated file. The
// marker each one writes is the only thing that tells a bootstrap
// descriptor apart from a query function that happens to land on the
// same path, so Write and ResolveDestination refuse a destination
// carrying another family's marker.
type Artifact int

const (
	Bootstrap Artifact = iota
	Schema
	Query
)

// Marker returns the first line every file a writes.
//
// The generators write this line themselves rather than reading it from
// here, because they are separate packages this one must not reach into.
// TestGeneratedOutputCarriesTheMarker holds the two sides together by
// running both commands and checking the first line of everything they
// write, so a generator that changed its header fails there.
func (a Artifact) Marker() string {
	switch a {
	case Bootstrap:
		return "// Code generated by rasqlgen bootstrap; DO NOT EDIT."
	case Schema:
		return "// Code generated by rasqlgen schema; DO NOT EDIT."
	case Query:
		return "// Code generated by rasqlgen query; DO NOT EDIT."
	default:
		panic(fmt.Sprintf("genfile: unknown Artifact %d", int(a)))
	}
}

// String returns the command name, for error messages.
func (a Artifact) String() string {
	switch a {
	case Bootstrap:
		return "bootstrap"
	case Schema:
		return "schema"
	case Query:
		return "query"
	default:
		panic(fmt.Sprintf("genfile: unknown Artifact %d", int(a)))
	}
}

// preSplitMarker is the single marker every rasqlgen command wrote before
// each family gained its own. A destination that still carries this line
// cannot be attributed to any one family, so requireMarker refuses it and
// tells the reader to delete and regenerate rather than guessing which
// command owns it.
const preSplitMarker = "// Code generated by rasqlgen; DO NOT EDIT."

// allArtifacts lists every known Artifact, for matching a destination's
// first line against each family's marker in turn.
var allArtifacts = []Artifact{Bootstrap, Schema, Query}

// ResolveDestination reports the file Write must replace for the requested
// output path, and refuses a destination that artifact may not replace.
//
// A destination must end in _gen.go, or in _gen_test.go for a generated
// test file. A destination that does not exist yet is free to be created. A
// destination that does exist must open with artifact.Marker() as its whole
// first line: without that check a hand-written file, or a file written by
// a different rasqlgen command, sitting where generated output lands is
// destroyed by the rename, silently and with a successful exit status, and
// the only copy of it is gone.
//
// Callers that write several files in one run resolve every destination
// before writing any of them, so a refusal cannot leave a package half
// regenerated.
func ResolveDestination(artifact Artifact, path string) (string, error) {
	destination, err := resolveOutputPath(path)
	if err != nil {
		return "", err
	}
	if !strings.HasSuffix(destination, "_gen.go") && !strings.HasSuffix(destination, "_gen_test.go") {
		return "", fmt.Errorf("generated output %q must end in _gen.go", destination)
	}
	if err := requireMarker(artifact, destination); err != nil {
		return "", err
	}
	return destination, nil
}

// requireMarker reports whether destination is safe for artifact to
// replace, which it is when it does not exist yet or when artifact.Marker()
// stands on its first line.
//
// The mode is checked before the file is opened. A destination that is not
// a regular file cannot carry a first line to begin with, and opening a
// fifo would block here until something opened the other end.
func requireMarker(artifact Artifact, destination string) error {
	info, err := os.Stat(destination)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return err
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("refusing to overwrite %s: it already exists and is not a regular file", destination)
	}
	file, err := os.Open(destination)
	if err != nil {
		return err
	}
	defer func() { _ = file.Close() }()

	// One byte past the longest known marker separates a first line that
	// is exactly a marker from a longer line that merely starts with one.
	longest := len(preSplitMarker)
	for _, other := range allArtifacts {
		if l := len(other.Marker()); l > longest {
			longest = l
		}
	}
	head := make([]byte, longest+1)
	read, err := io.ReadFull(file, head)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return err
	}
	head = head[:read]

	if firstLineIs(head, artifact.Marker()) {
		return nil
	}
	for _, other := range allArtifacts {
		if other == artifact {
			continue
		}
		if firstLineIs(head, other.Marker()) {
			return fmt.Errorf("refusing to overwrite %s: it was generated by rasqlgen %s, not rasqlgen %s", destination, other, artifact)
		}
	}
	if firstLineIs(head, preSplitMarker) {
		return fmt.Errorf("refusing to overwrite %s: it was generated by a rasqlgen that did not record which command wrote it; delete it and regenerate", destination)
	}
	return fmt.Errorf("refusing to overwrite %s: it was not generated by rasqlgen, because its first line is not %q", destination, artifact.Marker())
}

// firstLineIs reports whether head, the first bytes of a file, begin with
// marker standing alone on its first line. A file holding nothing but the
// marker has no line ending to check, so an exhausted head counts as the
// end of that line.
func firstLineIs(head []byte, marker string) bool {
	if !bytes.HasPrefix(head, []byte(marker)) {
		return false
	}
	rest := head[len(marker):]
	return len(rest) == 0 || rest[0] == '\n' || rest[0] == '\r'
}

// maxOutputSymlinkDepth caps how many symbolic links resolveOutputPath
// follows, so a link that points at itself or at another link in a cycle
// reports an error instead of looping forever. Linux allows 40 links in a
// single resolution, so this matches what an ordinary open would accept:
// the destination the fortieth link names is still used, and only a
// forty-first link that must be resolved is too many.
const maxOutputSymlinkDepth = 40

// resolveOutputPath reports the file Write must replace for
// the requested output path. A path that is not a symbolic link is its own
// destination. A symbolic link resolves to whatever it points at, so the
// generated source lands in the file the link names and the link itself
// survives the rename; writing to the link's own path would instead delete
// the link and leave its target holding stale content.
//
// A path that names a directory, or a symbolic link that resolves to one,
// is rejected instead of being treated as a destination. os.Lstat follows
// a trailing slash through to the directory even when the final component
// is a link, so this one check catches a directory named with or without a
// trailing slash and a directory reached through a link either way; without
// it, withResolvedParent would rewrite a path such as "outdir/" into a new
// child file "outdir/outdir" inside that directory and report success on
// what was almost certainly a typo.
//
// A link that points at a path which does not exist resolves to that
// missing path, matching what writing through the link would have done:
// the missing file is created, with the 0600 that generatedFileMode gives
// any new file, and the link keeps pointing at it. filepath.EvalSymlinks
// cannot resolve the whole path here, because it fails on such a dangling
// link; it is used only on directories, which always exist by the time
// they are resolved.
func resolveOutputPath(path string) (string, error) {
	current := path
	// followed counts the links already resolved. Testing it before the
	// next Readlink rather than after the last one keeps the destination
	// the fortieth link names in play, so a chain the kernel would accept
	// is accepted here too.
	for followed := 0; ; followed++ {
		info, err := os.Lstat(current)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				return withResolvedParent(current), nil
			}
			return "", err
		}
		if info.IsDir() {
			return "", fmt.Errorf("resolve output %s: is a directory", path)
		}
		if info.Mode()&fs.ModeSymlink == 0 {
			return withResolvedParent(current), nil
		}
		if followed == maxOutputSymlinkDepth {
			return "", fmt.Errorf("resolve output %s: too many levels of symbolic links", path)
		}
		target, err := os.Readlink(current)
		if err != nil {
			return "", err
		}
		if filepath.IsAbs(target) {
			current = target
			continue
		}
		// A relative link is relative to the directory holding the link,
		// and that is the directory the filesystem reaches rather than the
		// one filepath.Dir spells. Joining against the lexical parent
		// collapses a leading ".." in the target against a parent that is
		// itself a link, which lands the resolved path beside the link
		// instead of beside the directory the link points at. The Lstat
		// above succeeded, so that parent exists and resolves.
		parent, err := filepath.EvalSymlinks(filepath.Dir(current))
		if err != nil {
			return "", err
		}
		current = filepath.Join(parent, target)
	}
}

// withResolvedParent reports path with the directory holding it replaced
// by the directory the filesystem reaches, so Write creates
// its temporary file in, and renames over, the directory an ordinary open
// of path would have used. A parent that cannot be resolved is left as it
// was spelled, which leaves the resulting open to report the ENOENT an
// ordinary open would have reported.
//
// path is never itself a directory here: resolveOutputPath rejects that
// case before calling this, so filepath.Base(path) always names the file
// the caller asked for rather than the directory holding it.
func withResolvedParent(path string) string {
	parent, err := filepath.EvalSymlinks(filepath.Dir(path))
	if err != nil {
		return path
	}
	return filepath.Join(parent, filepath.Base(path))
}

// generatedFileMode reports the mode bits Write must give
// path. An existing file keeps the bits it already has, because the
// generated output's mode is the caller's to choose. Only a path that does
// not exist yet gets os.CreateTemp's 0600.
//
// The sticky bit travels with the permission bits, because writing the
// file in place kept it and replacing the file must not quietly drop it.
// Setuid and setgid deliberately do not travel: Linux clears both when an
// unprivileged process writes a file, so writing in place lost them too,
// and carrying them across here would make regenerating a file stricter
// than writing it directly.
func generatedFileMode(path string) (fs.FileMode, error) {
	info, err := os.Stat(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return 0o600, nil
		}
		return 0, err
	}
	return info.Mode() & (fs.ModePerm | fs.ModeSticky), nil
}
