// Package schemasource is a schema package: the one file a user maintains
// when they keep their schema as Go and generate from it with
// `rasqlgen schema -source`. It is input only; the generated code never
// imports it.
package schemasource

// The directive the documentation shows, kept here rather than written out
// in prose so the example is generated by the exact line a reader copies.
// It runs with this directory as its working directory, which is what makes
// the relative output path in gen/main.go resolve.
//
//go:generate go run ./gen

// BEGIN(schema_source_tables)
import "github.com/lestrrat-go/rasql/schema"

func Tables() []schema.TableDef {
	return []schema.TableDef{
		schema.MustTableDef("users",
			schema.Integer("id"),
			schema.Text("email", schema.Width(255)),
			schema.PrimaryKey("id"),
		),
	}
}

// END(schema_source_tables)
