// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
)

type DefaultUsersRow struct {
	ID     int64
	Email  string
	Status string
}

// ScanRow scans each result column directly into its field.
func (r *DefaultUsersRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.Email, &r.Status)
}

// ScanDestinations maps result-column names to fields on r.
func (r *DefaultUsersRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexEmail
		scanIndexStatus
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(3)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "email":
			if !scanned.Mark(scanIndexEmail) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Email
		case "status":
			if !scanned.Mark(scanIndexStatus) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Status
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r DefaultUsersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "email":
		return r.Email, true
	case "status":
		return r.Status, true
	}
	return nil, false
}

// DefaultUsersTable is the generated table type for the "default_users" table.
type DefaultUsersTable struct {
	rasql.Table[DefaultUsersRow]
}

// ID returns a reference to the "id" column.
func (t DefaultUsersTable) ID() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// Email returns a reference to the "email" column.
func (t DefaultUsersTable) Email() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "email") }

// Status returns a reference to the "status" column.
func (t DefaultUsersTable) Status() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "status") }

// DefaultUsers returns the descriptor for the "default_users" table.
func DefaultUsers() DefaultUsersTable {
	return defaultUsersTable
}

// As returns the table under alias.
func (t DefaultUsersTable) As(alias string) (DefaultUsersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return DefaultUsersTable{}, err
	}
	return DefaultUsersTable{Table: aliased}, nil
}
