// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
)

type EmployeesRow struct {
	ID        int64
	Name      string
	ManagerID rasql.Nullable[int64]
}

var employeesDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "employees",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "name", Type: schema.TextType{}},
		{Name: "manager_id", Type: schema.IntegerType{}, Nullable: true},
	},
	PrimaryKey: []string{"id"},
}

var employeesTable = rasql.MustTableOf[EmployeesRow](employeesDefinition)

type EmployeesTable struct{ rasql.Table[EmployeesRow] }

func Employees() EmployeesTable { return EmployeesTable{Table: employeesTable} }

func (t EmployeesTable) Source(alias string) (rasql.TypedRelation[EmployeesRow], error) {
	return rasql.SourceOf[EmployeesRow](t.Table, alias)
}

type EmployeesColumns struct{}

type EmployeesExpressions struct {
	ID        rasql.Column[EmployeesRow, int64]
	Name      rasql.Column[EmployeesRow, string]
	ManagerID rasql.NullColumn[EmployeesRow, int64]
}

type OptionalEmployeesExpressions struct {
	ID        rasql.NullColumn[EmployeesRow, int64]
	Name      rasql.NullColumn[EmployeesRow, string]
	ManagerID rasql.NullColumn[EmployeesRow, int64]
}

func (EmployeesColumns) Bind(source rasql.TypedRelation[EmployeesRow]) (EmployeesExpressions, error) {
	var err error
	result := EmployeesExpressions{
		ID:        rasqlgenBind(&err, source, "id", "", rasql.BindColumn[EmployeesRow, int64]),
		Name:      rasqlgenBind(&err, source, "name", "", rasql.BindColumn[EmployeesRow, string]),
		ManagerID: rasqlgenBind(&err, source, "manager_id", "", rasql.BindNullColumn[EmployeesRow, int64]),
	}
	return result, err
}

func (EmployeesColumns) BindOptional(source rasql.OptionalRelation[EmployeesRow]) (OptionalEmployeesExpressions, error) {
	var err error
	result := OptionalEmployeesExpressions{
		ID:        rasqlgenBind(&err, source, "id", "", rasql.BindOptionalColumn[EmployeesRow, int64]),
		Name:      rasqlgenBind(&err, source, "name", "", rasql.BindOptionalColumn[EmployeesRow, string]),
		ManagerID: rasqlgenBind(&err, source, "manager_id", "", rasql.BindOptionalColumn[EmployeesRow, int64]),
	}
	return result, err
}

var employeesResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "name", Type: schema.TextType{}, Codec: ""},
	{Name: "manager_id", Type: schema.IntegerType{}, Nullable: true, Codec: ""},
}
var employeesResultSchema = rasqlgenResultSchema(employeesResultColumns)

type employeesDecoder struct{}

func (employeesDecoder) ResultSchema() rasql.ResultSchema { return employeesResultSchema }
func (employeesDecoder) Presence() []rasql.Presence       { return nil }
func (employeesDecoder) DecodeRow(source rasql.ScanSource, row *EmployeesRow) error {
	return source.Scan(&row.ID, &row.Name, &row.ManagerID)
}

func (row *EmployeesRow) ScanRow(source rasql.ScanSource) error {
	return employeesDecoder{}.DecodeRow(source, row)
}

var employeesOptionalResultSchema = rasqlgenOptionalResultSchema(employeesResultColumns)

type employeesOptionalDecoder struct{}

func (employeesOptionalDecoder) ResultSchema() rasql.ResultSchema {
	return employeesOptionalResultSchema
}
func (employeesOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Employees", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (employeesOptionalDecoder) DecodeRow(source rasql.ScanSource, row *EmployeesRow) error {
	var IDValue rasql.Nullable[int64]
	var NameValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &NameValue, &row.ManagerID); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(NameValue, &row.Name)
	return nil
}

func EmployeesProjection(expressions EmployeesExpressions) (rasql.Projection[EmployeesRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", expressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("name", expressions.Name.Expr(), schema.TextType{}, ""),
		rasql.NullItem("manager_id", expressions.ManagerID.NullExpr(), schema.IntegerType{}, ""),
	}
	return rasql.NewProjection(items, employeesDecoder{})
}

func OptionalEmployeesProjection(expressions OptionalEmployeesExpressions) (rasql.Projection[EmployeesRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", expressions.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("name", expressions.Name.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("manager_id", expressions.ManagerID.NullExpr(), schema.IntegerType{}, ""),
	}
	return rasql.NewProjection(items, employeesOptionalDecoder{})
}

func EmployeesGraphKey(source rasql.TypedRelation[EmployeesRow]) (rasql.GraphKey[EmployeesRow], error) {
	expressions, err := (EmployeesColumns{}).Bind(source)
	if err != nil {
		return rasql.GraphKey[EmployeesRow]{}, err
	}
	return rasql.NewGraphKey[EmployeesRow](rasql.KeyPart[EmployeesRow, int64](expressions.ID, func(row EmployeesRow) int64 { return row.ID }))
}

func EmployeesIDPageKey(source rasql.TypedRelation[EmployeesRow], direction rasql.PageDirection) (rasql.PageKey[EmployeesRow], error) {
	expressions, err := (EmployeesColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.ID.Expr(), func(row EmployeesRow) int64 { return row.ID })
}

func EmployeesNamePageKey(source rasql.TypedRelation[EmployeesRow], direction rasql.PageDirection) (rasql.PageKey[EmployeesRow], error) {
	expressions, err := (EmployeesColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.Name.Expr(), func(row EmployeesRow) string { return row.Name })
}

func EmployeesManagerIDPageKey(source rasql.TypedRelation[EmployeesRow], direction rasql.PageDirection, nulls rasql.NullOrder) (rasql.PageKey[EmployeesRow], error) {
	expressions, err := (EmployeesColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenNullablePageKey(direction, expressions.ManagerID.NullExpr(), func(row EmployeesRow) rasql.Nullable[int64] { return row.ManagerID }, nulls)
}

var employeesMutationColumns = func() EmployeesExpressions {
	source, err := Employees().Source("")
	if err != nil {
		panic(err)
	}
	value, err := (EmployeesColumns{}).Bind(source)
	if err != nil {
		panic(err)
	}
	return value
}()

type EmployeesCreate struct {
	fields []rasql.MutationField[EmployeesRow]
}

func NewEmployeesCreate() EmployeesCreate { return EmployeesCreate{} }
func (v EmployeesCreate) ID(value int64) EmployeesCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(employeesMutationColumns.ID, value))
	return v
}
func (v EmployeesCreate) Name(value string) EmployeesCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(employeesMutationColumns.Name, value))
	return v
}
func (v EmployeesCreate) ManagerID(value int64) EmployeesCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetNullableField(employeesMutationColumns.ManagerID, value))
	return v
}
func (v EmployeesCreate) ClearManagerID() EmployeesCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.ClearField(employeesMutationColumns.ManagerID))
	return v
}
func (v EmployeesCreate) Plan() (rasql.CreatePlan[EmployeesRow], error) {
	return rasql.NewCreatePlan(Employees().Table, v.fields...)
}

type EmployeesPatch struct {
	fields []rasql.MutationField[EmployeesRow]
}

func NewEmployeesPatch() EmployeesPatch { return EmployeesPatch{} }
func (v EmployeesPatch) ID(value int64) EmployeesPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(employeesMutationColumns.ID, value))
	return v
}
func (v EmployeesPatch) Name(value string) EmployeesPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(employeesMutationColumns.Name, value))
	return v
}
func (v EmployeesPatch) ManagerID(value int64) EmployeesPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetNullableField(employeesMutationColumns.ManagerID, value))
	return v
}
func (v EmployeesPatch) ClearManagerID() EmployeesPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.ClearField(employeesMutationColumns.ManagerID))
	return v
}
func (v EmployeesPatch) Where(value rasql.Predicate) (rasql.PatchPlan[EmployeesRow], error) {
	return rasql.NewPatchPlan(Employees().Table, value, v.fields...)
}
