// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
)

// EmployeesRow is one row of the "employees" table.
type EmployeesRow struct {
	ID        int64
	Name      string
	ManagerID *int64
}

// ScanRow scans each result column directly into its field.
func (r *EmployeesRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.Name, &r.ManagerID)
}

// ScanDestinations maps result-column names to fields on r.
func (r *EmployeesRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexName
		scanIndexManagerID
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(3)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "name":
			if !scanned.Mark(scanIndexName) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Name
		case "manager_id":
			if !scanned.Mark(scanIndexManagerID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ManagerID
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// EmployeesTable is the generated table type for the "employees" table.
type EmployeesTable struct {
	rasql.Table[EmployeesRow]
}

// ID returns a reference to the "id" column.
func (t EmployeesTable) ID() query.TypedColumn[EmployeesRow, int64] {
	return query.TypedColumnOf[EmployeesRow, int64](t.Column("id"))
}
func (t EmployeesTable) IDRef() rasql.ColumnRef { return t.Column("id") }

// Name returns a reference to the "name" column.
func (t EmployeesTable) Name() query.TypedColumn[EmployeesRow, string] {
	return query.TypedColumnOf[EmployeesRow, string](t.Column("name"))
}
func (t EmployeesTable) NameRef() rasql.ColumnRef { return t.Column("name") }

// ManagerID returns a reference to the "manager_id" column.
func (t EmployeesTable) ManagerID() query.NullableColumn[EmployeesRow, *int64] {
	return query.NullableColumnOf[EmployeesRow, *int64](t.Column("manager_id"))
}
func (t EmployeesTable) ManagerIDRef() rasql.ColumnRef { return t.Column("manager_id") }

// Employees returns the descriptor for the "employees" table.
func Employees() EmployeesTable {
	return employeesTable
}

// As returns the table under alias.
func (t EmployeesTable) As(alias string) (EmployeesTable, error) {
	aliased, err := t.Table.As(alias)
	if err != nil {
		return EmployeesTable{}, err
	}
	return EmployeesTable{Table: aliased}, nil
}

type EmployeesCreate struct {
	fields []rasql.MutationField[EmployeesRow]
}

func NewEmployeesCreate() EmployeesCreate { return EmployeesCreate{} }

func (p EmployeesCreate) ID(value int64) EmployeesCreate {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[EmployeesRow](Employees().ID(), value))
	return EmployeesCreate{fields: fields}
}
func (p EmployeesCreate) Name(value string) EmployeesCreate {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[EmployeesRow](Employees().Name(), value))
	return EmployeesCreate{fields: fields}
}
func (p EmployeesCreate) ManagerID(value *int64) EmployeesCreate {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.SetNullableField[EmployeesRow](Employees().ManagerID(), value))
	return EmployeesCreate{fields: fields}
}
func (p EmployeesCreate) ClearManagerID() EmployeesCreate {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.ClearField[EmployeesRow](Employees().ManagerID()))
	return EmployeesCreate{fields: fields}
}
func (p EmployeesCreate) Plan() rasql.CreatePlan[EmployeesRow] {
	plan, _ := rasql.NewCreatePlan[EmployeesRow](Employees().Table, p.fields...)
	return plan
}

type EmployeesPatch struct {
	fields []rasql.MutationField[EmployeesRow]
}

func NewEmployeesPatch() EmployeesPatch { return EmployeesPatch{} }

func (p EmployeesPatch) Name(value string) EmployeesPatch {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[EmployeesRow](Employees().Name(), value))
	return EmployeesPatch{fields: fields}
}
func (p EmployeesPatch) ManagerID(value *int64) EmployeesPatch {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.SetNullableField[EmployeesRow](Employees().ManagerID(), value))
	return EmployeesPatch{fields: fields}
}
func (p EmployeesPatch) ClearManagerID() EmployeesPatch {
	fields := append([]rasql.MutationField[EmployeesRow](nil), p.fields...)
	fields = append(fields, rasql.ClearField[EmployeesRow](Employees().ManagerID()))
	return EmployeesPatch{fields: fields}
}
func (p EmployeesPatch) Where(predicate query.Predicate) (rasql.PatchPlan[EmployeesRow], error) {
	return rasql.NewPatchPlan[EmployeesRow](Employees().Table, predicate, p.fields...)
}
