// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
)

// OrdersRow is one row of the "orders" table.
type OrdersRow struct {
	ID     int64
	UserID int64
	Total  int64
}

// ScanRow scans each result column directly into its field.
func (r *OrdersRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.UserID, &r.Total)
}

// ScanDestinations maps result-column names to fields on r.
func (r *OrdersRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexUserID
		scanIndexTotal
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(3)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "user_id":
			if !scanned.Mark(scanIndexUserID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.UserID
		case "total":
			if !scanned.Mark(scanIndexTotal) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Total
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r OrdersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "user_id":
		return r.UserID, true
	case "total":
		return r.Total, true
	}
	return nil, false
}

// OrdersTable is the generated table type for the "orders" table.
type OrdersTable struct {
	rasql.Table[OrdersRow]
}

// ID returns a reference to the "id" column.
func (t OrdersTable) ID() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// UserID returns a reference to the "user_id" column.
func (t OrdersTable) UserID() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "user_id") }

// Total returns a reference to the "total" column.
func (t OrdersTable) Total() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "total") }

// Orders returns the descriptor for the "orders" table.
func Orders() OrdersTable {
	return ordersTable
}

// As returns the table under alias.
func (t OrdersTable) As(alias string) (OrdersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return OrdersTable{}, err
	}
	return OrdersTable{Table: aliased}, nil
}
