// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
)

type OrdersRow struct {
	ID, UserID, Total int64
}

var ordersDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "orders",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "user_id", Type: schema.IntegerType{}},
		{Name: "total", Type: schema.IntegerType{}},
	},
	PrimaryKey: []string{"id"},
}

var ordersTable = rasql.MustTableOf[OrdersRow](ordersDefinition)

type ordersTableHandle = rasql.Table[OrdersRow]

type OrdersTable struct {
	ordersTableHandle
	OrdersExpressions
}

func newOrdersTable(handle ordersTableHandle) OrdersTable {
	return OrdersTable{ordersTableHandle: handle, OrdersExpressions: bindOrdersExpressions(handle)}
}

func Orders() OrdersTable { return newOrdersTable(ordersTable) }

func (t OrdersTable) Ref() query.TableRef { return t.ordersTableHandle.Ref() }

func (t OrdersTable) As(alias string) (OrdersTable, error) {
	aliased, err := t.ordersTableHandle.As(alias)
	if err != nil {
		return OrdersTable{}, err
	}
	return newOrdersTable(aliased), nil
}

func (t OrdersTable) InSchema(namespace string) (OrdersTable, error) {
	moved, err := t.ordersTableHandle.InSchema(namespace)
	if err != nil {
		return OrdersTable{}, err
	}
	return newOrdersTable(moved), nil
}

type OrdersExpressions struct {
	ID, UserID, Total rasql.Column[OrdersRow, int64]
}

type OptionalOrdersExpressions struct {
	ID, UserID, Total rasql.NullColumn[OrdersRow, int64]
}

func bindOrdersExpressions(source ordersTableHandle) OrdersExpressions {
	return OrdersExpressions{
		ID:     rasqlgenColumn(source, "id", "", rasql.BindColumn[OrdersRow, int64]),
		UserID: rasqlgenColumn(source, "user_id", "", rasql.BindColumn[OrdersRow, int64]),
		Total:  rasqlgenColumn(source, "total", "", rasql.BindColumn[OrdersRow, int64]),
	}
}

// Optional names every column of t as it appears on the nullable side
// of an outer join, where the whole row may be absent.
func (t OrdersTable) Optional() OptionalOrdersExpressions {
	source := rasql.Optional[OrdersRow](t.ordersTableHandle)
	return OptionalOrdersExpressions{
		ID:     rasqlgenColumn(source, "id", "", rasql.BindOptionalColumn[OrdersRow, int64]),
		UserID: rasqlgenColumn(source, "user_id", "", rasql.BindOptionalColumn[OrdersRow, int64]),
		Total:  rasqlgenColumn(source, "total", "", rasql.BindOptionalColumn[OrdersRow, int64]),
	}
}

var ordersResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "user_id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "total", Type: schema.IntegerType{}, Codec: ""},
}
var ordersResultSchema = rasqlgenResultSchema(ordersResultColumns)

type ordersDecoder struct{}

func (ordersDecoder) ResultSchema() rasql.ResultSchema { return ordersResultSchema }
func (ordersDecoder) Presence() []rasql.Presence       { return nil }
func (ordersDecoder) DecodeRow(source rasql.ScanSource, row *OrdersRow) error {
	return source.Scan(&row.ID, &row.UserID, &row.Total)
}

func (row *OrdersRow) ScanRow(source rasql.ScanSource) error {
	return ordersDecoder{}.DecodeRow(source, row)
}

var ordersOptionalResultSchema = rasqlgenOptionalResultSchema(ordersResultColumns)

type ordersOptionalDecoder struct{}

func (ordersOptionalDecoder) ResultSchema() rasql.ResultSchema { return ordersOptionalResultSchema }
func (ordersOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Orders", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (ordersOptionalDecoder) DecodeRow(source rasql.ScanSource, row *OrdersRow) error {
	var IDValue, UserIDValue, TotalValue rasql.Nullable[int64]
	if err := source.Scan(&IDValue, &UserIDValue, &TotalValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(UserIDValue, &row.UserID)
	rasqlgenAssignNullable(TotalValue, &row.Total)
	return nil
}

func OrdersProjection(source OrdersTable) (rasql.Projection[OrdersRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", source.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("user_id", source.UserID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("total", source.Total.Expr(), schema.IntegerType{}, ""),
	}
	return rasql.NewProjection(items, ordersDecoder{})
}

func OptionalOrdersProjection(source OptionalOrdersExpressions) (rasql.Projection[OrdersRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", source.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("user_id", source.UserID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("total", source.Total.NullExpr(), schema.IntegerType{}, ""),
	}
	return rasql.NewProjection(items, ordersOptionalDecoder{})
}

func OrdersGraphKey(source OrdersTable) (rasql.GraphKey[OrdersRow], error) {
	return rasql.NewGraphKey[OrdersRow](rasql.KeyPart[OrdersRow, int64](source.ID, func(row OrdersRow) int64 { return row.ID }))
}

func OrdersIDPageKey(source OrdersTable, direction rasql.PageDirection) (rasql.PageKey[OrdersRow], error) {
	return rasqlgenPageKey(direction, source.ID.Expr(), func(row OrdersRow) int64 { return row.ID })
}

func OrdersUserIDPageKey(source OrdersTable, direction rasql.PageDirection) (rasql.PageKey[OrdersRow], error) {
	return rasqlgenPageKey(direction, source.UserID.Expr(), func(row OrdersRow) int64 { return row.UserID })
}

func OrdersTotalPageKey(source OrdersTable, direction rasql.PageDirection) (rasql.PageKey[OrdersRow], error) {
	return rasqlgenPageKey(direction, source.Total.Expr(), func(row OrdersRow) int64 { return row.Total })
}

var ordersMutationColumns = bindOrdersExpressions(ordersTable)

type OrdersCreate struct {
	table  rasql.Table[OrdersRow]
	fields []rasql.MutationField[OrdersRow]
}

func (v OrdersCreate) ID(value int64) OrdersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(ordersMutationColumns.ID, value))
	return v
}
func (v OrdersCreate) UserID(value int64) OrdersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(ordersMutationColumns.UserID, value))
	return v
}
func (v OrdersCreate) Total(value int64) OrdersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(ordersMutationColumns.Total, value))
	return v
}
func (v OrdersCreate) Plan() (rasql.CreatePlan[OrdersRow], error) {
	return rasql.NewCreatePlan(v.table, v.fields...)
}

func (t OrdersTable) Create() OrdersCreate { return OrdersCreate{table: t.ordersTableHandle} }

type OrdersPatch struct {
	table  rasql.Table[OrdersRow]
	fields []rasql.MutationField[OrdersRow]
}

func (v OrdersPatch) ID(value int64) OrdersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(ordersMutationColumns.ID, value))
	return v
}
func (v OrdersPatch) UserID(value int64) OrdersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(ordersMutationColumns.UserID, value))
	return v
}
func (v OrdersPatch) Total(value int64) OrdersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(ordersMutationColumns.Total, value))
	return v
}
func (v OrdersPatch) Where(value rasql.Predicate) (rasql.PatchPlan[OrdersRow], error) {
	return rasql.NewPatchPlan(v.table, value, v.fields...)
}

func (t OrdersTable) Patch() OrdersPatch { return OrdersPatch{table: t.ordersTableHandle} }

func (t OrdersTable) Delete(where rasql.Predicate) (rasql.DeletePlan[OrdersRow], error) {
	return rasql.NewDeletePlan(t.ordersTableHandle, where)
}
