// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
)

// OrdersRow is one row of the "orders" table.
type OrdersRow struct {
	ID     int64
	UserID int64
	Total  int64
}

// ScanRow scans each result column directly into its field.
func (r *OrdersRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.UserID, &r.Total)
}

// ScanDestinations maps result-column names to fields on r.
func (r *OrdersRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexUserID
		scanIndexTotal
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(3)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "user_id":
			if !scanned.Mark(scanIndexUserID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.UserID
		case "total":
			if !scanned.Mark(scanIndexTotal) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Total
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r OrdersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "user_id":
		return r.UserID, true
	case "total":
		return r.Total, true
	}
	return nil, false
}

// OrdersTable is the generated table type for the "orders" table.
type OrdersTable struct {
	rasql.Table[OrdersRow]
}

// ID returns a reference to the "id" column.
func (t OrdersTable) ID() query.TypedColumn[OrdersRow, int64] {
	return query.TypedColumnOf[OrdersRow, int64](rasql.ColumnOf(t.Table, "id"))
}
func (t OrdersTable) IDRef() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// UserID returns a reference to the "user_id" column.
func (t OrdersTable) UserID() query.TypedColumn[OrdersRow, int64] {
	return query.TypedColumnOf[OrdersRow, int64](rasql.ColumnOf(t.Table, "user_id"))
}
func (t OrdersTable) UserIDRef() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "user_id") }

// Total returns a reference to the "total" column.
func (t OrdersTable) Total() query.TypedColumn[OrdersRow, int64] {
	return query.TypedColumnOf[OrdersRow, int64](rasql.ColumnOf(t.Table, "total"))
}
func (t OrdersTable) TotalRef() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "total") }

// Orders returns the descriptor for the "orders" table.
func Orders() OrdersTable {
	return ordersTable
}

// As returns the table under alias.
func (t OrdersTable) As(alias string) (OrdersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return OrdersTable{}, err
	}
	return OrdersTable{Table: aliased}, nil
}

type OrdersCreate struct {
	fields []rasql.MutationField[OrdersRow]
}

func NewOrdersCreate() OrdersCreate { return OrdersCreate{} }

func (p OrdersCreate) ID(value int64) OrdersCreate {
	fields := append([]rasql.MutationField[OrdersRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[OrdersRow](Orders().ID(), value))
	return OrdersCreate{fields: fields}
}
func (p OrdersCreate) UserID(value int64) OrdersCreate {
	fields := append([]rasql.MutationField[OrdersRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[OrdersRow](Orders().UserID(), value))
	return OrdersCreate{fields: fields}
}
func (p OrdersCreate) Total(value int64) OrdersCreate {
	fields := append([]rasql.MutationField[OrdersRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[OrdersRow](Orders().Total(), value))
	return OrdersCreate{fields: fields}
}
func (p OrdersCreate) Plan() rasql.CreatePlan[OrdersRow] {
	plan, _ := rasql.NewCreatePlan[OrdersRow](Orders(), p.fields...)
	return plan
}

type OrdersPatch struct {
	fields []rasql.MutationField[OrdersRow]
}

func NewOrdersPatch() OrdersPatch { return OrdersPatch{} }

func (p OrdersPatch) UserID(value int64) OrdersPatch {
	fields := append([]rasql.MutationField[OrdersRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[OrdersRow](Orders().UserID(), value))
	return OrdersPatch{fields: fields}
}
func (p OrdersPatch) Total(value int64) OrdersPatch {
	fields := append([]rasql.MutationField[OrdersRow](nil), p.fields...)
	fields = append(fields, rasql.SetField[OrdersRow](Orders().Total(), value))
	return OrdersPatch{fields: fields}
}
func (p OrdersPatch) Where(predicate query.Predicate) (rasql.PatchPlan[OrdersRow], error) {
	return rasql.NewPatchPlan[OrdersRow](Orders(), predicate, p.fields...)
}
