// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"context"
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
)

type ReservedRow struct {
	ID                 int64
	Ref, ScanRow, Plan string
}

var reservedDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "reserved",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "ref", Type: schema.TextType{}},
		{Name: "scan_row", Type: schema.TextType{}},
		{Name: "plan", Type: schema.TextType{}},
	},
	PrimaryKey:              []string{"id"},
	PrimaryKeyAutoincrement: true,
}

var reservedTable = rasql.MustTableOf[ReservedRow](reservedDefinition)

type reservedTableHandle = rasql.Table[ReservedRow]

type ReservedTable struct {
	reservedTableHandle
	ReservedExpressions
}

func newReservedTable(handle reservedTableHandle) ReservedTable {
	return ReservedTable{reservedTableHandle: handle, ReservedExpressions: bindReservedExpressions(handle)}
}

func Reserved() ReservedTable { return newReservedTable(reservedTable) }

func (t ReservedTable) Ref() query.TableRef { return t.reservedTableHandle.Ref() }

func (t ReservedTable) As(alias string) (ReservedTable, error) {
	aliased, err := t.reservedTableHandle.As(alias)
	if err != nil {
		return ReservedTable{}, err
	}
	return newReservedTable(aliased), nil
}

func (t ReservedTable) InSchema(namespace string) (ReservedTable, error) {
	moved, err := t.reservedTableHandle.InSchema(namespace)
	if err != nil {
		return ReservedTable{}, err
	}
	return newReservedTable(moved), nil
}

// ReservedHandle returns the typed table inside t, which the constructors in
// the rasql package take: rasql.NewCreatePlan, rasql.NewPatchPlan and
// rasql.NewDeletePlan. Reach for it to write a column whose builder setter
// this package could not generate.
func ReservedHandle(t ReservedTable) rasql.Table[ReservedRow] { return t.reservedTableHandle }

type ReservedExpressions struct {
	ID                 rasql.Column[ReservedRow, int64]
	Ref, ScanRow, Plan rasql.Column[ReservedRow, string]
}

type OptionalReservedExpressions struct {
	ID                 rasql.NullColumn[ReservedRow, int64]
	Ref, ScanRow, Plan rasql.NullColumn[ReservedRow, string]
}

func bindReservedExpressions(source reservedTableHandle) ReservedExpressions {
	return ReservedExpressions{
		ID:      rasqlgenColumn(source, "id", "", rasql.BindColumn[ReservedRow, int64]),
		Ref:     rasqlgenColumn(source, "ref", "", rasql.BindColumn[ReservedRow, string]),
		ScanRow: rasqlgenColumn(source, "scan_row", "", rasql.BindColumn[ReservedRow, string]),
		Plan:    rasqlgenColumn(source, "plan", "", rasql.BindColumn[ReservedRow, string]),
	}
}

// Optional names every column of t as it appears on the nullable side
// of an outer join, where the whole row may be absent.
func (t ReservedTable) Optional() OptionalReservedExpressions {
	source := rasql.Optional[ReservedRow](t.reservedTableHandle)
	return OptionalReservedExpressions{
		ID:      rasqlgenColumn(source, "id", "", rasql.BindOptionalColumn[ReservedRow, int64]),
		Ref:     rasqlgenColumn(source, "ref", "", rasql.BindOptionalColumn[ReservedRow, string]),
		ScanRow: rasqlgenColumn(source, "scan_row", "", rasql.BindOptionalColumn[ReservedRow, string]),
		Plan:    rasqlgenColumn(source, "plan", "", rasql.BindOptionalColumn[ReservedRow, string]),
	}
}

var reservedResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "ref", Type: schema.TextType{}, Codec: ""},
	{Name: "scan_row", Type: schema.TextType{}, Codec: ""},
	{Name: "plan", Type: schema.TextType{}, Codec: ""},
}
var reservedResultSchema = rasqlgenResultSchema(reservedResultColumns)

type reservedDecoder struct{}

func (reservedDecoder) ResultSchema() rasql.ResultSchema { return reservedResultSchema }
func (reservedDecoder) Presence() []rasql.Presence       { return nil }
func (reservedDecoder) DecodeRow(source rasql.ScanSource, row *ReservedRow) error {
	return source.Scan(&row.ID, &row.Ref, &row.ScanRow, &row.Plan)
}

var reservedOptionalResultSchema = rasqlgenOptionalResultSchema(reservedResultColumns)

type reservedOptionalDecoder struct{}

func (reservedOptionalDecoder) ResultSchema() rasql.ResultSchema { return reservedOptionalResultSchema }
func (reservedOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Reserved", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (reservedOptionalDecoder) DecodeRow(source rasql.ScanSource, row *ReservedRow) error {
	var IDValue rasql.Nullable[int64]
	var RefValue, ScanRowValue, PlanValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &RefValue, &ScanRowValue, &PlanValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(RefValue, &row.Ref)
	rasqlgenAssignNullable(ScanRowValue, &row.ScanRow)
	rasqlgenAssignNullable(PlanValue, &row.Plan)
	return nil
}

func ReservedProjection(source ReservedTable) (rasql.Projection[ReservedRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", source.ReservedExpressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("ref", source.ReservedExpressions.Ref.Expr(), schema.TextType{}, ""),
		rasql.Item("scan_row", source.ReservedExpressions.ScanRow.Expr(), schema.TextType{}, ""),
		rasql.Item("plan", source.ReservedExpressions.Plan.Expr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, reservedDecoder{})
}

func OptionalReservedProjection(source OptionalReservedExpressions) (rasql.Projection[ReservedRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", source.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("ref", source.Ref.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("scan_row", source.ScanRow.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("plan", source.Plan.NullExpr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, reservedOptionalDecoder{})
}

func ReservedGraphKey(source ReservedTable) (rasql.GraphKey[ReservedRow], error) {
	return rasql.NewGraphKey[ReservedRow](rasql.KeyPart[ReservedRow, int64](source.ReservedExpressions.ID, func(row ReservedRow) int64 { return row.ID }))
}

func ReservedIDPageKey(source ReservedTable, direction rasql.PageDirection) (rasql.PageKey[ReservedRow], error) {
	return rasqlgenPageKey(direction, source.ReservedExpressions.ID.Expr(), func(row ReservedRow) int64 { return row.ID })
}

func ReservedRefPageKey(source ReservedTable, direction rasql.PageDirection) (rasql.PageKey[ReservedRow], error) {
	return rasqlgenPageKey(direction, source.ReservedExpressions.Ref.Expr(), func(row ReservedRow) string { return row.Ref })
}

func ReservedScanRowPageKey(source ReservedTable, direction rasql.PageDirection) (rasql.PageKey[ReservedRow], error) {
	return rasqlgenPageKey(direction, source.ReservedExpressions.ScanRow.Expr(), func(row ReservedRow) string { return row.ScanRow })
}

func ReservedPlanPageKey(source ReservedTable, direction rasql.PageDirection) (rasql.PageKey[ReservedRow], error) {
	return rasqlgenPageKey(direction, source.ReservedExpressions.Plan.Expr(), func(row ReservedRow) string { return row.Plan })
}

var reservedMutationColumns = bindReservedExpressions(reservedTable)

type ReservedCreate struct {
	table  rasql.Table[ReservedRow]
	fields []rasql.MutationField[ReservedRow]
}

func (v ReservedCreate) ID(value int64) ReservedCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(reservedMutationColumns.ID, value))
	return v
}
func (v ReservedCreate) Ref(value string) ReservedCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(reservedMutationColumns.Ref, value))
	return v
}
func (v ReservedCreate) ScanRow(value string) ReservedCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(reservedMutationColumns.ScanRow, value))
	return v
}

// ReservedCreate has no Plan setter: that name is already this builder's own. Write the
// "plan" column with rasql.SetField against the column field on the table,
// which rasql.NewCreatePlan and rasql.NewPatchPlan both take.

func (v ReservedCreate) Plan() (rasql.CreatePlan[ReservedRow], error) {
	return rasql.NewCreatePlan(v.table, v.fields...)
}

func (v ReservedCreate) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t ReservedTable) Create() ReservedCreate { return ReservedCreate{table: t.reservedTableHandle} }

type ReservedPatch struct {
	table  rasql.Table[ReservedRow]
	fields []rasql.MutationField[ReservedRow]
	where  rasql.Predicate
}

func (v ReservedPatch) ID(value int64) ReservedPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(reservedMutationColumns.ID, value))
	return v
}
func (v ReservedPatch) Ref(value string) ReservedPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(reservedMutationColumns.Ref, value))
	return v
}
func (v ReservedPatch) ScanRow(value string) ReservedPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(reservedMutationColumns.ScanRow, value))
	return v
}

// ReservedPatch has no Plan setter: that name is already this builder's own. Write the
// "plan" column with rasql.SetField against the column field on the table,
// which rasql.NewCreatePlan and rasql.NewPatchPlan both take.

func (v ReservedPatch) Where(value rasql.Predicate) ReservedPatch { v.where = value; return v }

func (v ReservedPatch) Plan() (rasql.PatchPlan[ReservedRow], error) {
	return rasql.NewPatchPlan(v.table, v.where, v.fields...)
}

func (v ReservedPatch) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t ReservedTable) Patch() ReservedPatch { return ReservedPatch{table: t.reservedTableHandle} }

type ReservedDelete struct {
	table rasql.Table[ReservedRow]
	where rasql.Predicate
}

func (t ReservedTable) Delete() ReservedDelete { return ReservedDelete{table: t.reservedTableHandle} }

func (v ReservedDelete) Where(value rasql.Predicate) ReservedDelete { v.where = value; return v }

func (v ReservedDelete) Plan() (rasql.DeletePlan[ReservedRow], error) {
	return rasql.NewDeletePlan(v.table, v.where)
}

func (v ReservedDelete) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}
