// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"testing"

	"github.com/lestrrat-go/rasql/schema"
)

func TestGeneratedDefinitionsAreValid(t *testing.T) {
	for _, definition := range []schema.TableDef{usersDef} {
		if err := definition.Validate(); err != nil {
			t.Errorf("%s: %s", definition.Name, err)
		}
	}
}
