// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
)

type TasksRow struct {
	ID     int64
	Status string
}

// ScanRow scans each result column directly into its field.
func (r *TasksRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.Status)
}

// ScanDestinations maps result-column names to fields on r.
func (r *TasksRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexStatus
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(2)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "status":
			if !scanned.Mark(scanIndexStatus) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Status
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r TasksRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "status":
		return r.Status, true
	}
	return nil, false
}

// TasksTable is the generated table type for the "tasks" table.
type TasksTable struct {
	rasql.Table[TasksRow]
}

// ID returns a reference to the "id" column.
func (t TasksTable) ID() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// Status returns a reference to the "status" column.
func (t TasksTable) Status() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "status") }

// Tasks returns the descriptor for the "tasks" table.
func Tasks() TasksTable {
	return tasksTable
}

// As returns the table under alias.
func (t TasksTable) As(alias string) (TasksTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return TasksTable{}, err
	}
	return TasksTable{Table: aliased}, nil
}
