// Code generated by rasqlgen; DO NOT EDIT.

package store

import rasqlstmt "github.com/lestrrat-go/rasql/stmt"

func UserByID(id int64) rasqlstmt.Statement {
	return rasqlstmt.New("SELECT id, email FROM users WHERE id = $1\n", id)
}
