// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/row"
	"github.com/lestrrat-go/rasql/schema"
)

type UsersRow struct {
	ID    int64
	Email string
}

// DecodeRow assigns each result column to its field.
func (r *UsersRow) DecodeRow(src row.Dynamic) error {
	if err := row.Assign(src, "id", &r.ID); err != nil {
		return err
	}
	return row.Assign(src, "email", &r.Email)
}

// ScanRow scans each result column directly into its field.
func (r *UsersRow) ScanRow(src row.ScanSource) error {
	return src.Scan(&r.ID, &r.Email)
}

// ScanDestinations maps result-column names to fields on r.
func (r *UsersRow) ScanDestinations(columns []string) ([]any, error) {
	destinations := make([]any, len(columns))
	var scanned uint64
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if scanned&(uint64(1)<<0) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 0
			destinations[index] = &r.ID
		case "email":
			if scanned&(uint64(1)<<1) != 0 {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			scanned |= uint64(1) << 1
			destinations[index] = &r.Email
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r UsersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "email":
		return r.Email, true
	}
	return nil, false
}

// UsersTable is the generated table type for the "users" table.
type UsersTable struct {
	rasql.Table[UsersRow]
	ID    query.ColumnRef
	Email query.ColumnRef
}

func newUsersTable(table rasql.Table[UsersRow]) UsersTable {
	return UsersTable{
		Table: table,
		ID:    rasql.MustColumn(table, "id"),
		Email: rasql.MustColumn(table, "email"),
	}
}

var usersTable = newUsersTable(rasql.MustTableOf[UsersRow](schema.MustTableDef("users",
	schema.Integer("id"),
	schema.Text("email"),
	schema.PrimaryKey("id"),
)))

// Users returns the descriptor for the "users" table.
func Users() UsersTable {
	return usersTable
}

// As returns the table under alias, with every column rebound to it.
func (t UsersTable) As(alias string) (UsersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return UsersTable{}, err
	}
	return newUsersTable(aliased), nil
}
