// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"context"
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
)

type UsersRow struct {
	ID                          int64
	Email                       string
	Nickname                    rasql.Nullable[string]
	Status, FirstName, LastName string
}

var usersDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "users",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "email", Type: schema.TextType{}},
		{Name: "nickname", Type: schema.TextType{}, Nullable: true},
		{Name: "status", Type: schema.TextType{}, Default: "'pending'"},
		{Name: "first_name", Type: schema.TextType{}},
		{Name: "last_name", Type: schema.TextType{}},
	},
	PrimaryKey:              []string{"id"},
	PrimaryKeyAutoincrement: true,
}

var usersTable = rasql.MustTableOf[UsersRow](usersDefinition)

type usersTableHandle = rasql.Table[UsersRow]

type UsersTable struct {
	usersTableHandle
	UsersExpressions
}

func newUsersTable(handle usersTableHandle) UsersTable {
	return UsersTable{usersTableHandle: handle, UsersExpressions: bindUsersExpressions(handle)}
}

func Users() UsersTable { return newUsersTable(usersTable) }

func (t UsersTable) Ref() query.TableRef { return t.usersTableHandle.Ref() }

func (t UsersTable) As(alias string) (UsersTable, error) {
	aliased, err := t.usersTableHandle.As(alias)
	if err != nil {
		return UsersTable{}, err
	}
	return newUsersTable(aliased), nil
}

func (t UsersTable) InSchema(namespace string) (UsersTable, error) {
	moved, err := t.usersTableHandle.InSchema(namespace)
	if err != nil {
		return UsersTable{}, err
	}
	return newUsersTable(moved), nil
}

// UsersHandle returns the typed table inside t, which the constructors in
// the rasql package take: rasql.NewCreatePlan, rasql.NewPatchPlan and
// rasql.NewDeletePlan. Reach for it to write a column whose builder setter
// this package could not generate.
func UsersHandle(t UsersTable) rasql.Table[UsersRow] { return t.usersTableHandle }

type UsersExpressions struct {
	ID                          rasql.Column[UsersRow, int64]
	Email                       rasql.Column[UsersRow, string]
	Nickname                    rasql.NullColumn[UsersRow, string]
	Status, FirstName, LastName rasql.Column[UsersRow, string]
}

type OptionalUsersExpressions struct {
	ID                                           rasql.NullColumn[UsersRow, int64]
	Email, Nickname, Status, FirstName, LastName rasql.NullColumn[UsersRow, string]
}

func bindUsersExpressions(source usersTableHandle) UsersExpressions {
	return UsersExpressions{
		ID:        rasqlgenColumn(source, "id", "", rasql.BindColumn[UsersRow, int64]),
		Email:     rasqlgenColumn(source, "email", "", rasql.BindColumn[UsersRow, string]),
		Nickname:  rasqlgenColumn(source, "nickname", "", rasql.BindNullColumn[UsersRow, string]),
		Status:    rasqlgenColumn(source, "status", "", rasql.BindColumn[UsersRow, string]),
		FirstName: rasqlgenColumn(source, "first_name", "", rasql.BindColumn[UsersRow, string]),
		LastName:  rasqlgenColumn(source, "last_name", "", rasql.BindColumn[UsersRow, string]),
	}
}

// Optional names every column of t as it appears on the nullable side
// of an outer join, where the whole row may be absent.
func (t UsersTable) Optional() OptionalUsersExpressions {
	source := rasql.Optional[UsersRow](t.usersTableHandle)
	return OptionalUsersExpressions{
		ID:        rasqlgenColumn(source, "id", "", rasql.BindOptionalColumn[UsersRow, int64]),
		Email:     rasqlgenColumn(source, "email", "", rasql.BindOptionalColumn[UsersRow, string]),
		Nickname:  rasqlgenColumn(source, "nickname", "", rasql.BindOptionalColumn[UsersRow, string]),
		Status:    rasqlgenColumn(source, "status", "", rasql.BindOptionalColumn[UsersRow, string]),
		FirstName: rasqlgenColumn(source, "first_name", "", rasql.BindOptionalColumn[UsersRow, string]),
		LastName:  rasqlgenColumn(source, "last_name", "", rasql.BindOptionalColumn[UsersRow, string]),
	}
}

var usersResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "email", Type: schema.TextType{}, Codec: ""},
	{Name: "nickname", Type: schema.TextType{}, Nullable: true, Codec: ""},
	{Name: "status", Type: schema.TextType{}, Codec: ""},
	{Name: "first_name", Type: schema.TextType{}, Codec: ""},
	{Name: "last_name", Type: schema.TextType{}, Codec: ""},
}
var usersResultSchema = rasqlgenResultSchema(usersResultColumns)

type usersDecoder struct{}

func (usersDecoder) ResultSchema() rasql.ResultSchema { return usersResultSchema }
func (usersDecoder) Presence() []rasql.Presence       { return nil }
func (usersDecoder) DecodeRow(source rasql.ScanSource, row *UsersRow) error {
	return source.Scan(&row.ID, &row.Email, &row.Nickname, &row.Status, &row.FirstName, &row.LastName)
}

func (row *UsersRow) ScanRow(source rasql.ScanSource) error {
	return usersDecoder{}.DecodeRow(source, row)
}

var usersOptionalResultSchema = rasqlgenOptionalResultSchema(usersResultColumns)

type usersOptionalDecoder struct{}

func (usersOptionalDecoder) ResultSchema() rasql.ResultSchema { return usersOptionalResultSchema }
func (usersOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Users", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (usersOptionalDecoder) DecodeRow(source rasql.ScanSource, row *UsersRow) error {
	var IDValue rasql.Nullable[int64]
	var EmailValue, StatusValue, FirstNameValue, LastNameValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &EmailValue, &row.Nickname, &StatusValue, &FirstNameValue, &LastNameValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(EmailValue, &row.Email)
	rasqlgenAssignNullable(StatusValue, &row.Status)
	rasqlgenAssignNullable(FirstNameValue, &row.FirstName)
	rasqlgenAssignNullable(LastNameValue, &row.LastName)
	return nil
}

func UsersProjection(source UsersTable) (rasql.Projection[UsersRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", source.UsersExpressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("email", source.UsersExpressions.Email.Expr(), schema.TextType{}, ""),
		rasql.NullItem("nickname", source.UsersExpressions.Nickname.NullExpr(), schema.TextType{}, ""),
		rasql.Item("status", source.UsersExpressions.Status.Expr(), schema.TextType{}, ""),
		rasql.Item("first_name", source.UsersExpressions.FirstName.Expr(), schema.TextType{}, ""),
		rasql.Item("last_name", source.UsersExpressions.LastName.Expr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, usersDecoder{})
}

func OptionalUsersProjection(source OptionalUsersExpressions) (rasql.Projection[UsersRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", source.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("email", source.Email.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("nickname", source.Nickname.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("status", source.Status.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("first_name", source.FirstName.NullExpr(), schema.TextType{}, ""),
		rasql.NullItem("last_name", source.LastName.NullExpr(), schema.TextType{}, ""),
	}
	return rasql.NewProjection(items, usersOptionalDecoder{})
}

func UsersGraphKey(source UsersTable) (rasql.GraphKey[UsersRow], error) {
	return rasql.NewGraphKey[UsersRow](rasql.KeyPart[UsersRow, int64](source.UsersExpressions.ID, func(row UsersRow) int64 { return row.ID }))
}

func UsersIDPageKey(source UsersTable, direction rasql.PageDirection) (rasql.PageKey[UsersRow], error) {
	return rasqlgenPageKey(direction, source.UsersExpressions.ID.Expr(), func(row UsersRow) int64 { return row.ID })
}

func UsersEmailPageKey(source UsersTable, direction rasql.PageDirection) (rasql.PageKey[UsersRow], error) {
	return rasqlgenPageKey(direction, source.UsersExpressions.Email.Expr(), func(row UsersRow) string { return row.Email })
}

func UsersNicknamePageKey(source UsersTable, direction rasql.PageDirection, nulls rasql.NullOrder) (rasql.PageKey[UsersRow], error) {
	return rasqlgenNullablePageKey(direction, source.UsersExpressions.Nickname.NullExpr(), func(row UsersRow) rasql.Nullable[string] { return row.Nickname }, nulls)
}

func UsersStatusPageKey(source UsersTable, direction rasql.PageDirection) (rasql.PageKey[UsersRow], error) {
	return rasqlgenPageKey(direction, source.UsersExpressions.Status.Expr(), func(row UsersRow) string { return row.Status })
}

func UsersFirstNamePageKey(source UsersTable, direction rasql.PageDirection) (rasql.PageKey[UsersRow], error) {
	return rasqlgenPageKey(direction, source.UsersExpressions.FirstName.Expr(), func(row UsersRow) string { return row.FirstName })
}

func UsersLastNamePageKey(source UsersTable, direction rasql.PageDirection) (rasql.PageKey[UsersRow], error) {
	return rasqlgenPageKey(direction, source.UsersExpressions.LastName.Expr(), func(row UsersRow) string { return row.LastName })
}

var usersMutationColumns = bindUsersExpressions(usersTable)

type UsersCreate struct {
	table  rasql.Table[UsersRow]
	fields []rasql.MutationField[UsersRow]
}

func (v UsersCreate) ID(value int64) UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.ID, value))
	return v
}
func (v UsersCreate) Email(value string) UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.Email, value))
	return v
}
func (v UsersCreate) Nickname(value string) UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetNullableField(usersMutationColumns.Nickname, value))
	return v
}
func (v UsersCreate) ClearNickname() UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.ClearField(usersMutationColumns.Nickname))
	return v
}
func (v UsersCreate) Status(value string) UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.Status, value))
	return v
}
func (v UsersCreate) DefaultStatus() UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.DefaultField(usersMutationColumns.Status))
	return v
}
func (v UsersCreate) FirstName(value string) UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.FirstName, value))
	return v
}
func (v UsersCreate) LastName(value string) UsersCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.LastName, value))
	return v
}
func (v UsersCreate) Plan() (rasql.CreatePlan[UsersRow], error) {
	return rasql.NewCreatePlan(v.table, v.fields...)
}

func (v UsersCreate) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t UsersTable) Create() UsersCreate { return UsersCreate{table: t.usersTableHandle} }

type UsersPatch struct {
	table  rasql.Table[UsersRow]
	fields []rasql.MutationField[UsersRow]
	where  rasql.Predicate
}

func (v UsersPatch) ID(value int64) UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.ID, value))
	return v
}
func (v UsersPatch) Email(value string) UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.Email, value))
	return v
}
func (v UsersPatch) Nickname(value string) UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetNullableField(usersMutationColumns.Nickname, value))
	return v
}
func (v UsersPatch) ClearNickname() UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.ClearField(usersMutationColumns.Nickname))
	return v
}
func (v UsersPatch) Status(value string) UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.Status, value))
	return v
}
func (v UsersPatch) DefaultStatus() UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.DefaultField(usersMutationColumns.Status))
	return v
}
func (v UsersPatch) FirstName(value string) UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.FirstName, value))
	return v
}
func (v UsersPatch) LastName(value string) UsersPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(usersMutationColumns.LastName, value))
	return v
}
func (v UsersPatch) Where(value rasql.Predicate) UsersPatch { v.where = value; return v }

func (v UsersPatch) Plan() (rasql.PatchPlan[UsersRow], error) {
	return rasql.NewPatchPlan(v.table, v.where, v.fields...)
}

func (v UsersPatch) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t UsersTable) Patch() UsersPatch { return UsersPatch{table: t.usersTableHandle} }

type UsersDelete struct {
	table rasql.Table[UsersRow]
	where rasql.Predicate
}

func (t UsersTable) Delete() UsersDelete { return UsersDelete{table: t.usersTableHandle} }

func (v UsersDelete) Where(value rasql.Predicate) UsersDelete { v.where = value; return v }

func (v UsersDelete) Plan() (rasql.DeletePlan[UsersRow], error) {
	return rasql.NewDeletePlan(v.table, v.where)
}

func (v UsersDelete) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}
