// Code generated by rasqlgen; DO NOT EDIT.

package store

import "github.com/lestrrat-go/rasql/stmt"

func UserByEmail(email any) stmt.Statement {
	return stmt.New("SELECT id, email FROM users WHERE email = $1\n", email)
}
