// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"fmt"

	"github.com/lestrrat-go/rasql"
)

type UsersRow struct {
	ID    int64
	Email string
}

// ScanRow scans each result column directly into its field.
func (r *UsersRow) ScanRow(src rasql.ScanSource) error {
	return src.Scan(&r.ID, &r.Email)
}

// ScanDestinations maps result-column names to fields on r.
func (r *UsersRow) ScanDestinations(columns []string) ([]any, error) {
	const (
		scanIndexID = iota
		scanIndexEmail
	)
	destinations := make([]any, len(columns))
	scanned := rasql.NewScanMask(2)
	var discard any
	for index, column := range columns {
		switch column {
		case "id":
			if !scanned.Mark(scanIndexID) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.ID
		case "email":
			if !scanned.Mark(scanIndexEmail) {
				return nil, fmt.Errorf("duplicate result column %q", column)
			}
			destinations[index] = &r.Email
		default:
			destinations[index] = &discard
		}
	}
	return destinations, nil
}

// ColumnValue returns the value of the named column.
func (r UsersRow) ColumnValue(name string) (any, bool) {
	switch name {
	case "id":
		return r.ID, true
	case "email":
		return r.Email, true
	}
	return nil, false
}

// UsersTable is the generated table type for the "users" table.
type UsersTable struct {
	rasql.Table[UsersRow]
}

// ID returns a reference to the "id" column.
func (t UsersTable) ID() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "id") }

// Email returns a reference to the "email" column.
func (t UsersTable) Email() rasql.ColumnRef { return rasql.ColumnOf(t.Table, "email") }

// Users returns the descriptor for the "users" table.
func Users() UsersTable {
	return usersTable
}

// As returns the table under alias.
func (t UsersTable) As(alias string) (UsersTable, error) {
	aliased, err := rasql.As(t.Table, alias)
	if err != nil {
		return UsersTable{}, err
	}
	return UsersTable{Table: aliased}, nil
}
