// Code generated by rasqlgen; DO NOT EDIT.

package store

import "github.com/lestrrat-go/rasql/stmt"

func UserByID(id int64) stmt.Statement {
	return stmt.New("SELECT id, email FROM users WHERE id = $1\n", id)
}
