// Code generated by rasqlgen; DO NOT EDIT.

package store

import rasqlstatement "github.com/lestrrat-go/rasql/statement"

func UserByEmail(email any) rasqlstatement.Statement {
	return rasqlstatement.New("SELECT id, email FROM users WHERE email = $1\n", email)
}
