// Code generated by rasqlgen query; DO NOT EDIT.

package store

import rasqlrender "github.com/lestrrat-go/rasql/render"

func UserByEmail(email any) (rasqlrender.Statement, error) {
	return rasqlrender.Precompiled("SELECT id, email FROM users WHERE email = $1\n", email)
}
