// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
	"time"
)

type overdue_taskResult struct {
	ID         int64
	ProjectID  int64
	AssigneeID rasql.Nullable[int64]
	Title      string
	IsOpen     bool
	DueOn      rasql.Nullable[time.Time]
	CreatedAt  time.Time
}

type OverdueTaskBindings struct{}
type OverdueTaskExpressions struct {
	ID         rasql.Column[overdue_taskResult, int64]
	ProjectID  rasql.Column[overdue_taskResult, int64]
	AssigneeID rasql.NullColumn[overdue_taskResult, int64]
	Title      rasql.Column[overdue_taskResult, string]
	IsOpen     rasql.Column[overdue_taskResult, bool]
	DueOn      rasql.NullColumn[overdue_taskResult, time.Time]
	CreatedAt  rasql.Column[overdue_taskResult, time.Time]
}

func (OverdueTaskBindings) Bind(source rasql.TypedSource[overdue_taskResult]) (OverdueTaskExpressions, error) {
	valueID, err := rasql.BindResultColumn[overdue_taskResult, int64](source, "id")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	valueProjectID, err := rasql.BindResultColumn[overdue_taskResult, int64](source, "project_id")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	valueAssigneeID, err := rasql.BindNullResultColumn[overdue_taskResult, int64](source, "assignee_id")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	valueTitle, err := rasql.BindResultColumn[overdue_taskResult, string](source, "title")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	valueIsOpen, err := rasql.BindResultColumn[overdue_taskResult, bool](source, "is_open")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	valueDueOn, err := rasql.BindNullResultColumn[overdue_taskResult, time.Time](source, "due_on")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	valueCreatedAt, err := rasql.BindResultColumn[overdue_taskResult, time.Time](source, "created_at")
	if err != nil {
		return OverdueTaskExpressions{}, err
	}
	return OverdueTaskExpressions{ID: valueID, ProjectID: valueProjectID, AssigneeID: valueAssigneeID, Title: valueTitle, IsOpen: valueIsOpen, DueOn: valueDueOn, CreatedAt: valueCreatedAt}, nil
}

type overdue_taskDecoder struct{}

func (overdue_taskDecoder) ResultSchema() rasql.ResultSchema { return overdue_taskDecoderSchema() }
func (overdue_taskDecoder) Presence() []rasql.Presence       { return nil }
func (overdue_taskDecoder) DecodeRow(s rasql.ScanSource, r *overdue_taskResult) error {
	if err := s.Scan(&r.ID, &r.ProjectID, &r.AssigneeID, &r.Title, &r.IsOpen, &r.DueOn, &r.CreatedAt); err != nil {
		return err
	}
	return nil
}

func overdue_taskDecoderSchema() rasql.ResultSchema {
	s, _ := rasql.NewResultSchema(
		rasql.ResultColumn{Name: "id", Type: schema.IntegerType{Unsigned: false, ZeroFill: false}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "project_id", Type: schema.IntegerType{Unsigned: false, ZeroFill: false}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "assignee_id", Type: schema.IntegerType{Unsigned: false, ZeroFill: false}, Nullable: true, Codec: ""},
		rasql.ResultColumn{Name: "title", Type: schema.TextType{}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "is_open", Type: schema.BooleanType{}, Nullable: false, Codec: ""},
		rasql.ResultColumn{Name: "due_on", Type: schema.TimeType{}, Nullable: true, Codec: ""},
		rasql.ResultColumn{Name: "created_at", Type: schema.TimeType{}, Nullable: false, Codec: ""},
	)
	return s
}

func OverdueTask(projectID int64, open bool, cutoff time.Time) (rasql.Query[overdue_taskResult], error) {
	projection, err := rasql.NativeProjection[overdue_taskResult](overdue_taskDecoder{})
	if err != nil {
		return rasql.Query[overdue_taskResult]{}, err
	}
	return rasql.Native[overdue_taskResult](rasql.NativeStatement{Engine: "postgresql", SQL: "SELECT id, project_id, assignee_id, title, is_open, due_on, created_at\nFROM tasks\nWHERE project_id = $1\n  AND is_open = $2\n  AND due_on IS NOT NULL\n  AND due_on < $3\nORDER BY id\n", Args: []rasql.NativeArgument{{Value: projectID, Codec: ""}, {Value: open, Codec: ""}, {Value: cutoff, Codec: ""}}}, projection, rasql.ExactlyOne)
}
