// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"context"
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/query"
	"github.com/lestrrat-go/rasql/schema"
)

type ProjectsRow struct {
	ID   int64
	Name string
}

var projectsDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "projects",
	Columns: []schema.ColumnDef{
		{Name: "id", Type: schema.IntegerType{}},
		{Name: "name", Type: schema.TextType{Width: schema.NewTextWidth(64)}},
	},
	PrimaryKey: []string{"id"},
}

var projectsTable = rasql.MustTableOf[ProjectsRow](projectsDefinition)

type projectsTableHandle = rasql.Table[ProjectsRow]

type ProjectsTable struct {
	projectsTableHandle
}

func Projects() ProjectsTable { return ProjectsTable{projectsTableHandle: projectsTable} }

func (t ProjectsTable) Ref() query.TableRef { return t.projectsTableHandle.Ref() }

func (t ProjectsTable) As(alias string) (ProjectsTable, error) {
	aliased, err := t.projectsTableHandle.As(alias)
	if err != nil {
		return ProjectsTable{}, err
	}
	return ProjectsTable{projectsTableHandle: aliased}, nil
}

func (t ProjectsTable) InSchema(namespace string) (ProjectsTable, error) {
	moved, err := t.projectsTableHandle.InSchema(namespace)
	if err != nil {
		return ProjectsTable{}, err
	}
	return ProjectsTable{projectsTableHandle: moved}, nil
}

type ProjectsColumns struct{}

type ProjectsExpressions struct {
	ID   rasql.Column[ProjectsRow, int64]
	Name rasql.Column[ProjectsRow, string]
}

type OptionalProjectsExpressions struct {
	ID   rasql.NullColumn[ProjectsRow, int64]
	Name rasql.NullColumn[ProjectsRow, string]
}

func (ProjectsColumns) Bind(source ProjectsTable) (ProjectsExpressions, error) {
	var err error
	result := ProjectsExpressions{
		ID:   rasqlgenBind(&err, source, "id", "", rasql.BindColumn[ProjectsRow, int64]),
		Name: rasqlgenBind(&err, source, "name", "", rasql.BindColumn[ProjectsRow, string]),
	}
	return result, err
}

func (ProjectsColumns) BindOptional(source rasql.OptionalRelation[ProjectsRow]) (OptionalProjectsExpressions, error) {
	var err error
	result := OptionalProjectsExpressions{
		ID:   rasqlgenBind(&err, source, "id", "", rasql.BindOptionalColumn[ProjectsRow, int64]),
		Name: rasqlgenBind(&err, source, "name", "", rasql.BindOptionalColumn[ProjectsRow, string]),
	}
	return result, err
}

var projectsResultColumns = []rasql.ResultColumn{
	{Name: "id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "name", Type: schema.TextType{Width: schema.NewTextWidth(64)}, Codec: ""},
}
var projectsResultSchema = rasqlgenResultSchema(projectsResultColumns)

type projectsDecoder struct{}

func (projectsDecoder) ResultSchema() rasql.ResultSchema { return projectsResultSchema }
func (projectsDecoder) Presence() []rasql.Presence       { return nil }
func (projectsDecoder) DecodeRow(source rasql.ScanSource, row *ProjectsRow) error {
	return source.Scan(&row.ID, &row.Name)
}

func (row *ProjectsRow) ScanRow(source rasql.ScanSource) error {
	return projectsDecoder{}.DecodeRow(source, row)
}

var projectsOptionalResultSchema = rasqlgenOptionalResultSchema(projectsResultColumns)

type projectsOptionalDecoder struct{}

func (projectsOptionalDecoder) ResultSchema() rasql.ResultSchema { return projectsOptionalResultSchema }
func (projectsOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Projects", "id")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (projectsOptionalDecoder) DecodeRow(source rasql.ScanSource, row *ProjectsRow) error {
	var IDValue rasql.Nullable[int64]
	var NameValue rasql.Nullable[string]
	if err := source.Scan(&IDValue, &NameValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(IDValue, &row.ID)
	rasqlgenAssignNullable(NameValue, &row.Name)
	return nil
}

func ProjectsProjection(expressions ProjectsExpressions) (rasql.Projection[ProjectsRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("id", expressions.ID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("name", expressions.Name.Expr(), schema.TextType{Width: schema.NewTextWidth(64)}, ""),
	}
	return rasql.NewProjection(items, projectsDecoder{})
}

func OptionalProjectsProjection(expressions OptionalProjectsExpressions) (rasql.Projection[ProjectsRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("id", expressions.ID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("name", expressions.Name.NullExpr(), schema.TextType{Width: schema.NewTextWidth(64)}, ""),
	}
	return rasql.NewProjection(items, projectsOptionalDecoder{})
}

func ProjectsGraphKey(source ProjectsTable) (rasql.GraphKey[ProjectsRow], error) {
	expressions, err := (ProjectsColumns{}).Bind(source)
	if err != nil {
		return rasql.GraphKey[ProjectsRow]{}, err
	}
	return rasql.NewGraphKey[ProjectsRow](rasql.KeyPart[ProjectsRow, int64](expressions.ID, func(row ProjectsRow) int64 { return row.ID }))
}

func ProjectsIDPageKey(source ProjectsTable, direction rasql.PageDirection) (rasql.PageKey[ProjectsRow], error) {
	expressions, err := (ProjectsColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.ID.Expr(), func(row ProjectsRow) int64 { return row.ID })
}

func ProjectsNamePageKey(source ProjectsTable, direction rasql.PageDirection) (rasql.PageKey[ProjectsRow], error) {
	expressions, err := (ProjectsColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.Name.Expr(), func(row ProjectsRow) string { return row.Name })
}

func ProjectsTasksEdge[G, CG any](parentSource ProjectsTable, childSource TasksTable, children rasql.GraphPlan[TasksRow, CG], options rasql.EdgeOptions, attach func(*G, rasql.LoadedMany[CG])) (rasql.GraphEdge[ProjectsRow, G], error) {
	parentExpressions, err := (ProjectsColumns{}).Bind(parentSource)
	if err != nil {
		return nil, err
	}
	childExpressions, err := (TasksColumns{}).Bind(childSource)
	if err != nil {
		return nil, err
	}
	parent, err := rasql.NewGraphKey[ProjectsRow](rasql.KeyPart[ProjectsRow, int64](parentExpressions.ID, func(row ProjectsRow) int64 { return row.ID }))
	if err != nil {
		return nil, err
	}
	child, err := rasql.NewGraphKey[TasksRow](rasql.KeyPart[TasksRow, int64](childExpressions.ProjectID, func(row TasksRow) int64 { return row.ProjectID }))
	if err != nil {
		return nil, err
	}
	return rasql.HasMany("Tasks", parent, child, children, options, attach)
}

var projectsMutationColumns = func() ProjectsExpressions {
	value, err := (ProjectsColumns{}).Bind(Projects())
	if err != nil {
		panic(err)
	}
	return value
}()

type ProjectsCreate struct {
	table  rasql.Table[ProjectsRow]
	fields []rasql.MutationField[ProjectsRow]
}

func (v ProjectsCreate) ID(value int64) ProjectsCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(projectsMutationColumns.ID, value))
	return v
}
func (v ProjectsCreate) Name(value string) ProjectsCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(projectsMutationColumns.Name, value))
	return v
}
func (v ProjectsCreate) Plan() (rasql.CreatePlan[ProjectsRow], error) {
	return rasql.NewCreatePlan(v.table, v.fields...)
}

func (v ProjectsCreate) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t ProjectsTable) Create() ProjectsCreate { return ProjectsCreate{table: t.projectsTableHandle} }

type ProjectsPatch struct {
	table  rasql.Table[ProjectsRow]
	fields []rasql.MutationField[ProjectsRow]
	where  rasql.Predicate
}

func (v ProjectsPatch) ID(value int64) ProjectsPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(projectsMutationColumns.ID, value))
	return v
}
func (v ProjectsPatch) Name(value string) ProjectsPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(projectsMutationColumns.Name, value))
	return v
}
func (v ProjectsPatch) Where(value rasql.Predicate) ProjectsPatch { v.where = value; return v }

func (v ProjectsPatch) Plan() (rasql.PatchPlan[ProjectsRow], error) {
	return rasql.NewPatchPlan(v.table, v.where, v.fields...)
}

func (v ProjectsPatch) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}

func (t ProjectsTable) Patch() ProjectsPatch { return ProjectsPatch{table: t.projectsTableHandle} }

type ProjectsDelete struct {
	table rasql.Table[ProjectsRow]
	where rasql.Predicate
}

func (t ProjectsTable) Delete() ProjectsDelete { return ProjectsDelete{table: t.projectsTableHandle} }

func (v ProjectsDelete) Where(value rasql.Predicate) ProjectsDelete { v.where = value; return v }

func (v ProjectsDelete) Plan() (rasql.DeletePlan[ProjectsRow], error) {
	return rasql.NewDeletePlan(v.table, v.where)
}

func (v ProjectsDelete) Exec(ctx context.Context, executor rasql.Executor) (rasql.MutationOutcome, error) {
	plan, err := v.Plan()
	if err != nil {
		return rasql.MutationOutcome{}, err
	}
	return rasql.Exec(ctx, executor, plan)
}
