// Code generated by rasqlgen; DO NOT EDIT.

package store

import (
	"github.com/lestrrat-go/rasql"
	"github.com/lestrrat-go/rasql/schema"
)

type Task_labelsRow struct {
	TaskID int64
	Label  string
}

var task_labelsDefinition = schema.TableDef{
	Kind: schema.ObjectKind("table"),
	Name: "task_labels",
	Columns: []schema.ColumnDef{
		{Name: "task_id", Type: schema.IntegerType{}},
		{Name: "label", Type: schema.TextType{Width: schema.NewTextWidth(32)}},
	},
	PrimaryKey: []string{"task_id", "label"},
	ForeignKeys: []schema.ForeignKeyDef{
		{Name: "task_labels_task_id_fkey", Columns: []string{"task_id"}, ReferencedTable: "tasks", ReferencedColumns: []string{"id"}, OnDelete: schema.NoAction, OnUpdate: schema.NoAction},
	},
}

var task_labelsTable = rasql.MustTableOf[Task_labelsRow](task_labelsDefinition)

type Task_labelsTable struct{ rasql.Table[Task_labelsRow] }

func Task_labels() Task_labelsTable { return Task_labelsTable{Table: task_labelsTable} }

func (t Task_labelsTable) Source(alias string) (rasql.TypedRelation[Task_labelsRow], error) {
	return rasql.SourceOf[Task_labelsRow](t.Table, alias)
}

type Task_labelsColumns struct{}

type Task_labelsExpressions struct {
	TaskID rasql.Column[Task_labelsRow, int64]
	Label  rasql.Column[Task_labelsRow, string]
}

type OptionalTask_labelsExpressions struct {
	TaskID rasql.NullColumn[Task_labelsRow, int64]
	Label  rasql.NullColumn[Task_labelsRow, string]
}

func (Task_labelsColumns) Bind(source rasql.TypedRelation[Task_labelsRow]) (Task_labelsExpressions, error) {
	var err error
	result := Task_labelsExpressions{
		TaskID: rasqlgenBind(&err, source, "task_id", "", rasql.BindColumn[Task_labelsRow, int64]),
		Label:  rasqlgenBind(&err, source, "label", "", rasql.BindColumn[Task_labelsRow, string]),
	}
	return result, err
}

func (Task_labelsColumns) BindOptional(source rasql.OptionalRelation[Task_labelsRow]) (OptionalTask_labelsExpressions, error) {
	var err error
	result := OptionalTask_labelsExpressions{
		TaskID: rasqlgenBind(&err, source, "task_id", "", rasql.BindOptionalColumn[Task_labelsRow, int64]),
		Label:  rasqlgenBind(&err, source, "label", "", rasql.BindOptionalColumn[Task_labelsRow, string]),
	}
	return result, err
}

var task_labelsResultColumns = []rasql.ResultColumn{
	{Name: "task_id", Type: schema.IntegerType{}, Codec: ""},
	{Name: "label", Type: schema.TextType{Width: schema.NewTextWidth(32)}, Codec: ""},
}
var task_labelsResultSchema = rasqlgenResultSchema(task_labelsResultColumns)

type task_labelsDecoder struct{}

func (task_labelsDecoder) ResultSchema() rasql.ResultSchema { return task_labelsResultSchema }
func (task_labelsDecoder) Presence() []rasql.Presence       { return nil }
func (task_labelsDecoder) DecodeRow(source rasql.ScanSource, row *Task_labelsRow) error {
	return source.Scan(&row.TaskID, &row.Label)
}

func (row *Task_labelsRow) ScanRow(source rasql.ScanSource) error {
	return task_labelsDecoder{}.DecodeRow(source, row)
}

var task_labelsOptionalResultSchema = rasqlgenOptionalResultSchema(task_labelsResultColumns)

type task_labelsOptionalDecoder struct{}

func (task_labelsOptionalDecoder) ResultSchema() rasql.ResultSchema {
	return task_labelsOptionalResultSchema
}
func (task_labelsOptionalDecoder) Presence() []rasql.Presence {
	p, err := rasql.NewPresence("Task_labels", "task_id", "label")
	if err != nil {
		panic(err)
	}
	return []rasql.Presence{p}
}
func (task_labelsOptionalDecoder) DecodeRow(source rasql.ScanSource, row *Task_labelsRow) error {
	var TaskIDValue rasql.Nullable[int64]
	var LabelValue rasql.Nullable[string]
	if err := source.Scan(&TaskIDValue, &LabelValue); err != nil {
		return err
	}
	rasqlgenAssignNullable(TaskIDValue, &row.TaskID)
	rasqlgenAssignNullable(LabelValue, &row.Label)
	return nil
}

func Task_labelsProjection(expressions Task_labelsExpressions) (rasql.Projection[Task_labelsRow], error) {
	items := []rasql.ProjectionItem{
		rasql.Item("task_id", expressions.TaskID.Expr(), schema.IntegerType{}, ""),
		rasql.Item("label", expressions.Label.Expr(), schema.TextType{Width: schema.NewTextWidth(32)}, ""),
	}
	return rasql.NewProjection(items, task_labelsDecoder{})
}

func OptionalTask_labelsProjection(expressions OptionalTask_labelsExpressions) (rasql.Projection[Task_labelsRow], error) {
	items := []rasql.ProjectionItem{
		rasql.NullItem("task_id", expressions.TaskID.NullExpr(), schema.IntegerType{}, ""),
		rasql.NullItem("label", expressions.Label.NullExpr(), schema.TextType{Width: schema.NewTextWidth(32)}, ""),
	}
	return rasql.NewProjection(items, task_labelsOptionalDecoder{})
}

func Task_labelsGraphKey(source rasql.TypedRelation[Task_labelsRow]) (rasql.GraphKey[Task_labelsRow], error) {
	expressions, err := (Task_labelsColumns{}).Bind(source)
	if err != nil {
		return rasql.GraphKey[Task_labelsRow]{}, err
	}
	return rasql.NewGraphKey[Task_labelsRow](rasql.KeyPart[Task_labelsRow, int64](expressions.TaskID, func(row Task_labelsRow) int64 { return row.TaskID }), rasql.KeyPart[Task_labelsRow, string](expressions.Label, func(row Task_labelsRow) string { return row.Label }))
}

func Task_labelsTaskIDPageKey(source rasql.TypedRelation[Task_labelsRow], direction rasql.PageDirection) (rasql.PageKey[Task_labelsRow], error) {
	expressions, err := (Task_labelsColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.TaskID.Expr(), func(row Task_labelsRow) int64 { return row.TaskID })
}

func Task_labelsLabelPageKey(source rasql.TypedRelation[Task_labelsRow], direction rasql.PageDirection) (rasql.PageKey[Task_labelsRow], error) {
	expressions, err := (Task_labelsColumns{}).Bind(source)
	if err != nil {
		return nil, err
	}
	return rasqlgenPageKey(direction, expressions.Label.Expr(), func(row Task_labelsRow) string { return row.Label })
}

func Task_labelsTaskEdge[G, CG any](parentSource rasql.TypedRelation[Task_labelsRow], childSource rasql.TypedRelation[TasksRow], children rasql.GraphPlan[TasksRow, CG], options rasql.EdgeOptions, attach func(*G, rasql.LoadedOne[CG])) (rasql.GraphEdge[Task_labelsRow, G], error) {
	parentExpressions, err := (Task_labelsColumns{}).Bind(parentSource)
	if err != nil {
		return nil, err
	}
	childExpressions, err := (TasksColumns{}).Bind(childSource)
	if err != nil {
		return nil, err
	}
	parent, err := rasql.NewGraphKey[Task_labelsRow](rasql.KeyPart[Task_labelsRow, int64](parentExpressions.TaskID, func(row Task_labelsRow) int64 { return row.TaskID }))
	if err != nil {
		return nil, err
	}
	child, err := rasql.NewGraphKey[TasksRow](rasql.KeyPart[TasksRow, int64](childExpressions.ID, func(row TasksRow) int64 { return row.ID }))
	if err != nil {
		return nil, err
	}
	return rasql.HasOne("Task", parent, child, children, options, attach)
}

var task_labelsMutationColumns = func() Task_labelsExpressions {
	source, err := Task_labels().Source("")
	if err != nil {
		panic(err)
	}
	value, err := (Task_labelsColumns{}).Bind(source)
	if err != nil {
		panic(err)
	}
	return value
}()

type Task_labelsCreate struct {
	fields []rasql.MutationField[Task_labelsRow]
}

func NewTask_labelsCreate() Task_labelsCreate { return Task_labelsCreate{} }
func (v Task_labelsCreate) TaskID(value int64) Task_labelsCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(task_labelsMutationColumns.TaskID, value))
	return v
}
func (v Task_labelsCreate) Label(value string) Task_labelsCreate {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(task_labelsMutationColumns.Label, value))
	return v
}
func (v Task_labelsCreate) Plan() (rasql.CreatePlan[Task_labelsRow], error) {
	return rasql.NewCreatePlan(Task_labels().Table, v.fields...)
}

type Task_labelsPatch struct {
	fields []rasql.MutationField[Task_labelsRow]
}

func NewTask_labelsPatch() Task_labelsPatch { return Task_labelsPatch{} }
func (v Task_labelsPatch) TaskID(value int64) Task_labelsPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(task_labelsMutationColumns.TaskID, value))
	return v
}
func (v Task_labelsPatch) Label(value string) Task_labelsPatch {
	v.fields = rasqlgenAppendMutationField(v.fields, rasql.SetField(task_labelsMutationColumns.Label, value))
	return v
}
func (v Task_labelsPatch) Where(value rasql.Predicate) (rasql.PatchPlan[Task_labelsRow], error) {
	return rasql.NewPatchPlan(Task_labels().Table, value, v.fields...)
}
